// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: contract.proto

/*
Package types is a generated protocol buffer package.

It is generated from these files:
	contract.proto

It has these top-level messages:
	ContractAction
	ContractCreate
	ContractCancel
	ContractModify
	ContractSign
	ContractReject
	Contract
	Creator
	Signatory
	ReqId
*/
package types

import fmt "fmt"
import go_proto_validators "github.com/mwitkow/go-proto-validators"
import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *ContractAction) Validate() error {
	if oneOfNester, ok := this.GetValue().(*ContractAction_Create); ok {
		if oneOfNester.Create != nil {
			if err := go_proto_validators.CallValidatorIfExists(oneOfNester.Create); err != nil {
				return go_proto_validators.FieldError("Create", err)
			}
		}
	}
	if oneOfNester, ok := this.GetValue().(*ContractAction_Cancel); ok {
		if oneOfNester.Cancel != nil {
			if err := go_proto_validators.CallValidatorIfExists(oneOfNester.Cancel); err != nil {
				return go_proto_validators.FieldError("Cancel", err)
			}
		}
	}
	if oneOfNester, ok := this.GetValue().(*ContractAction_Modify); ok {
		if oneOfNester.Modify != nil {
			if err := go_proto_validators.CallValidatorIfExists(oneOfNester.Modify); err != nil {
				return go_proto_validators.FieldError("Modify", err)
			}
		}
	}
	if oneOfNester, ok := this.GetValue().(*ContractAction_Sign); ok {
		if oneOfNester.Sign != nil {
			if err := go_proto_validators.CallValidatorIfExists(oneOfNester.Sign); err != nil {
				return go_proto_validators.FieldError("Sign", err)
			}
		}
	}
	if oneOfNester, ok := this.GetValue().(*ContractAction_Reject); ok {
		if oneOfNester.Reject != nil {
			if err := go_proto_validators.CallValidatorIfExists(oneOfNester.Reject); err != nil {
				return go_proto_validators.FieldError("Reject", err)
			}
		}
	}
	return nil
}
func (this *ContractCreate) Validate() error {
	if this.OperatorId == "" {
		return go_proto_validators.FieldError("OperatorId", fmt.Errorf(`value '%v' must not be an empty string`, this.OperatorId))
	}
	if this.ContractId == "" {
		return go_proto_validators.FieldError("ContractId", fmt.Errorf(`value '%v' must not be an empty string`, this.ContractId))
	}
	if !(len(this.ContractHash) == 128) {
		return go_proto_validators.FieldError("ContractHash", fmt.Errorf(`ErrHash`))
	}
	if this.ContractName == "" {
		return go_proto_validators.FieldError("ContractName", fmt.Errorf(`value '%v' must not be an empty string`, this.ContractName))
	}
	if !(this.Amount > 0) {
		return go_proto_validators.FieldError("Amount", fmt.Errorf(`value '%v' must be greater than '0'`, this.Amount))
	}
	if len(this.SignatoryIds) < 1 {
		return go_proto_validators.FieldError("SignatoryIds", fmt.Errorf(`value '%v' must contain at least 1 elements`, this.SignatoryIds))
	}
	for _, item := range this.SignatoryIds {
		if item == "" {
			return go_proto_validators.FieldError("SignatoryIds", fmt.Errorf(`value '%v' must not be an empty string`, item))
		}
	}
	if !(this.OperateTime > 0) {
		return go_proto_validators.FieldError("OperateTime", fmt.Errorf(`value '%v' must be greater than '0'`, this.OperateTime))
	}
	return nil
}
func (this *ContractCancel) Validate() error {
	if this.OperatorId == "" {
		return go_proto_validators.FieldError("OperatorId", fmt.Errorf(`value '%v' must not be an empty string`, this.OperatorId))
	}
	if this.ContractId == "" {
		return go_proto_validators.FieldError("ContractId", fmt.Errorf(`value '%v' must not be an empty string`, this.ContractId))
	}
	if !(this.OperateTime > 0) {
		return go_proto_validators.FieldError("OperateTime", fmt.Errorf(`value '%v' must be greater than '0'`, this.OperateTime))
	}
	return nil
}
func (this *ContractModify) Validate() error {
	if this.OperatorId == "" {
		return go_proto_validators.FieldError("OperatorId", fmt.Errorf(`value '%v' must not be an empty string`, this.OperatorId))
	}
	if this.ContractId == "" {
		return go_proto_validators.FieldError("ContractId", fmt.Errorf(`value '%v' must not be an empty string`, this.ContractId))
	}
	for _, item := range this.SignatoryIds {
		if item == "" {
			return go_proto_validators.FieldError("SignatoryIds", fmt.Errorf(`value '%v' must not be an empty string`, item))
		}
	}
	if !(this.OperateTime > 0) {
		return go_proto_validators.FieldError("OperateTime", fmt.Errorf(`value '%v' must be greater than '0'`, this.OperateTime))
	}
	return nil
}
func (this *ContractSign) Validate() error {
	if this.OperatorId == "" {
		return go_proto_validators.FieldError("OperatorId", fmt.Errorf(`value '%v' must not be an empty string`, this.OperatorId))
	}
	if this.ContractId == "" {
		return go_proto_validators.FieldError("ContractId", fmt.Errorf(`value '%v' must not be an empty string`, this.ContractId))
	}
	if !(len(this.SignedContractHash) == 128) {
		return go_proto_validators.FieldError("SignedContractHash", fmt.Errorf(`ErrHash`))
	}
	if !(this.OperateTime > 0) {
		return go_proto_validators.FieldError("OperateTime", fmt.Errorf(`value '%v' must be greater than '0'`, this.OperateTime))
	}
	return nil
}
func (this *ContractReject) Validate() error {
	if this.OperatorId == "" {
		return go_proto_validators.FieldError("OperatorId", fmt.Errorf(`value '%v' must not be an empty string`, this.OperatorId))
	}
	if this.ContractId == "" {
		return go_proto_validators.FieldError("ContractId", fmt.Errorf(`value '%v' must not be an empty string`, this.ContractId))
	}
	if !(this.OperateTime > 0) {
		return go_proto_validators.FieldError("OperateTime", fmt.Errorf(`value '%v' must be greater than '0'`, this.OperateTime))
	}
	return nil
}
func (this *Contract) Validate() error {
	if this.Creator != nil {
		if err := go_proto_validators.CallValidatorIfExists(this.Creator); err != nil {
			return go_proto_validators.FieldError("Creator", err)
		}
	}
	for _, item := range this.Signatories {
		if item != nil {
			if err := go_proto_validators.CallValidatorIfExists(item); err != nil {
				return go_proto_validators.FieldError("Signatories", err)
			}
		}
	}
	return nil
}
func (this *Creator) Validate() error {
	return nil
}
func (this *Signatory) Validate() error {
	return nil
}
func (this *ReqId) Validate() error {
	return nil
}
