// Code generated by protoc-gen-go. DO NOT EDIT.
// source: contract.proto

/*
Package types is a generated protocol buffer package.

It is generated from these files:
	contract.proto

It has these top-level messages:
	ContractAction
	ContractCreate
	ContractCancel
	ContractModify
	ContractSign
	ContractReject
	Contract
	Creator
	Signatory
	ReqId
*/
package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 合同状态
type ContractStatus int32

const (
	ContractStatus_CS_Unknown     ContractStatus = 0
	ContractStatus_CS_Ineffective ContractStatus = 1
	ContractStatus_CS_Effective   ContractStatus = 2
	ContractStatus_CS_Disused     ContractStatus = 3
	ContractStatus_CS_Draft       ContractStatus = 4
	ContractStatus_CS_Canceled    ContractStatus = 5
)

var ContractStatus_name = map[int32]string{
	0: "CS_Unknown",
	1: "CS_Ineffective",
	2: "CS_Effective",
	3: "CS_Disused",
	4: "CS_Draft",
	5: "CS_Canceled",
}
var ContractStatus_value = map[string]int32{
	"CS_Unknown":     0,
	"CS_Ineffective": 1,
	"CS_Effective":   2,
	"CS_Disused":     3,
	"CS_Draft":       4,
	"CS_Canceled":    5,
}

func (x ContractStatus) String() string {
	return proto.EnumName(ContractStatus_name, int32(x))
}
func (ContractStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// 签名状态
type SignStatus int32

const (
	SignStatus_SS_Unknown  SignStatus = 0
	SignStatus_SS_Unsigned SignStatus = 1
	SignStatus_SS_Signed   SignStatus = 2
	SignStatus_SS_Rejected SignStatus = 3
)

var SignStatus_name = map[int32]string{
	0: "SS_Unknown",
	1: "SS_Unsigned",
	2: "SS_Signed",
	3: "SS_Rejected",
}
var SignStatus_value = map[string]int32{
	"SS_Unknown":  0,
	"SS_Unsigned": 1,
	"SS_Signed":   2,
	"SS_Rejected": 3,
}

func (x SignStatus) String() string {
	return proto.EnumName(SignStatus_name, int32(x))
}
func (SignStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ContractActionType int32

const (
	ContractActionType_AT_Unknown  ContractActionType = 0
	ContractActionType_AT_Create   ContractActionType = 1
	ContractActionType_AT_Cancel   ContractActionType = 2
	ContractActionType_AT_Modify   ContractActionType = 3
	ContractActionType_AT_Sign     ContractActionType = 4
	ContractActionType_AT_Reject   ContractActionType = 5
	ContractActionType_AT_Register ContractActionType = 6
)

var ContractActionType_name = map[int32]string{
	0: "AT_Unknown",
	1: "AT_Create",
	2: "AT_Cancel",
	3: "AT_Modify",
	4: "AT_Sign",
	5: "AT_Reject",
	6: "AT_Register",
}
var ContractActionType_value = map[string]int32{
	"AT_Unknown":  0,
	"AT_Create":   1,
	"AT_Cancel":   2,
	"AT_Modify":   3,
	"AT_Sign":     4,
	"AT_Reject":   5,
	"AT_Register": 6,
}

func (x ContractActionType) String() string {
	return proto.EnumName(ContractActionType_name, int32(x))
}
func (ContractActionType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// 合同链动作
type ContractAction struct {
	// Types that are valid to be assigned to Value:
	//	*ContractAction_Create
	//	*ContractAction_Cancel
	//	*ContractAction_Modify
	//	*ContractAction_Sign
	//	*ContractAction_Reject
	Value isContractAction_Value `protobuf_oneof:"value"`
	Ty    int32                  `protobuf:"varint,100,opt,name=ty" json:"ty,omitempty"`
}

func (m *ContractAction) Reset()                    { *m = ContractAction{} }
func (m *ContractAction) String() string            { return proto.CompactTextString(m) }
func (*ContractAction) ProtoMessage()               {}
func (*ContractAction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isContractAction_Value interface {
	isContractAction_Value()
}

type ContractAction_Create struct {
	Create *ContractCreate `protobuf:"bytes,1,opt,name=create,oneof"`
}
type ContractAction_Cancel struct {
	Cancel *ContractCancel `protobuf:"bytes,2,opt,name=cancel,oneof"`
}
type ContractAction_Modify struct {
	Modify *ContractModify `protobuf:"bytes,3,opt,name=modify,oneof"`
}
type ContractAction_Sign struct {
	Sign *ContractSign `protobuf:"bytes,4,opt,name=sign,oneof"`
}
type ContractAction_Reject struct {
	Reject *ContractReject `protobuf:"bytes,5,opt,name=reject,oneof"`
}

func (*ContractAction_Create) isContractAction_Value() {}
func (*ContractAction_Cancel) isContractAction_Value() {}
func (*ContractAction_Modify) isContractAction_Value() {}
func (*ContractAction_Sign) isContractAction_Value()   {}
func (*ContractAction_Reject) isContractAction_Value() {}

func (m *ContractAction) GetValue() isContractAction_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ContractAction) GetCreate() *ContractCreate {
	if x, ok := m.GetValue().(*ContractAction_Create); ok {
		return x.Create
	}
	return nil
}

func (m *ContractAction) GetCancel() *ContractCancel {
	if x, ok := m.GetValue().(*ContractAction_Cancel); ok {
		return x.Cancel
	}
	return nil
}

func (m *ContractAction) GetModify() *ContractModify {
	if x, ok := m.GetValue().(*ContractAction_Modify); ok {
		return x.Modify
	}
	return nil
}

func (m *ContractAction) GetSign() *ContractSign {
	if x, ok := m.GetValue().(*ContractAction_Sign); ok {
		return x.Sign
	}
	return nil
}

func (m *ContractAction) GetReject() *ContractReject {
	if x, ok := m.GetValue().(*ContractAction_Reject); ok {
		return x.Reject
	}
	return nil
}

func (m *ContractAction) GetTy() int32 {
	if m != nil {
		return m.Ty
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ContractAction) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ContractAction_OneofMarshaler, _ContractAction_OneofUnmarshaler, _ContractAction_OneofSizer, []interface{}{
		(*ContractAction_Create)(nil),
		(*ContractAction_Cancel)(nil),
		(*ContractAction_Modify)(nil),
		(*ContractAction_Sign)(nil),
		(*ContractAction_Reject)(nil),
	}
}

func _ContractAction_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ContractAction)
	// value
	switch x := m.Value.(type) {
	case *ContractAction_Create:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Create); err != nil {
			return err
		}
	case *ContractAction_Cancel:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Cancel); err != nil {
			return err
		}
	case *ContractAction_Modify:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Modify); err != nil {
			return err
		}
	case *ContractAction_Sign:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Sign); err != nil {
			return err
		}
	case *ContractAction_Reject:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Reject); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ContractAction.Value has unexpected type %T", x)
	}
	return nil
}

func _ContractAction_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ContractAction)
	switch tag {
	case 1: // value.create
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ContractCreate)
		err := b.DecodeMessage(msg)
		m.Value = &ContractAction_Create{msg}
		return true, err
	case 2: // value.cancel
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ContractCancel)
		err := b.DecodeMessage(msg)
		m.Value = &ContractAction_Cancel{msg}
		return true, err
	case 3: // value.modify
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ContractModify)
		err := b.DecodeMessage(msg)
		m.Value = &ContractAction_Modify{msg}
		return true, err
	case 4: // value.sign
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ContractSign)
		err := b.DecodeMessage(msg)
		m.Value = &ContractAction_Sign{msg}
		return true, err
	case 5: // value.reject
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ContractReject)
		err := b.DecodeMessage(msg)
		m.Value = &ContractAction_Reject{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ContractAction_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ContractAction)
	// value
	switch x := m.Value.(type) {
	case *ContractAction_Create:
		s := proto.Size(x.Create)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ContractAction_Cancel:
		s := proto.Size(x.Cancel)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ContractAction_Modify:
		s := proto.Size(x.Modify)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ContractAction_Sign:
		s := proto.Size(x.Sign)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ContractAction_Reject:
		s := proto.Size(x.Reject)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// 发起合同，操作者签名
type ContractCreate struct {
	OperatorId         string   `protobuf:"bytes,1,opt,name=operatorId" json:"operatorId,omitempty"`
	ContractId         string   `protobuf:"bytes,2,opt,name=contractId" json:"contractId,omitempty"`
	ContractHash       string   `protobuf:"bytes,3,opt,name=contractHash" json:"contractHash,omitempty"`
	ContractName       string   `protobuf:"bytes,4,opt,name=contractName" json:"contractName,omitempty"`
	Amount             uint64   `protobuf:"varint,5,opt,name=amount" json:"amount,omitempty"`
	SignatoryIds       []string `protobuf:"bytes,6,rep,name=signatoryIds" json:"signatoryIds,omitempty"`
	IsDraft            bool     `protobuf:"varint,7,opt,name=isDraft" json:"isDraft,omitempty"`
	SignedContractHash string   `protobuf:"bytes,8,opt,name=signedContractHash" json:"signedContractHash,omitempty"`
	OperateTime        uint64   `protobuf:"varint,9,opt,name=operateTime" json:"operateTime,omitempty"`
}

func (m *ContractCreate) Reset()                    { *m = ContractCreate{} }
func (m *ContractCreate) String() string            { return proto.CompactTextString(m) }
func (*ContractCreate) ProtoMessage()               {}
func (*ContractCreate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ContractCreate) GetOperatorId() string {
	if m != nil {
		return m.OperatorId
	}
	return ""
}

func (m *ContractCreate) GetContractId() string {
	if m != nil {
		return m.ContractId
	}
	return ""
}

func (m *ContractCreate) GetContractHash() string {
	if m != nil {
		return m.ContractHash
	}
	return ""
}

func (m *ContractCreate) GetContractName() string {
	if m != nil {
		return m.ContractName
	}
	return ""
}

func (m *ContractCreate) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ContractCreate) GetSignatoryIds() []string {
	if m != nil {
		return m.SignatoryIds
	}
	return nil
}

func (m *ContractCreate) GetIsDraft() bool {
	if m != nil {
		return m.IsDraft
	}
	return false
}

func (m *ContractCreate) GetSignedContractHash() string {
	if m != nil {
		return m.SignedContractHash
	}
	return ""
}

func (m *ContractCreate) GetOperateTime() uint64 {
	if m != nil {
		return m.OperateTime
	}
	return 0
}

// 撤销合同，操作者签名，仅当所有签署者均未签名时可操作
type ContractCancel struct {
	OperatorId  string `protobuf:"bytes,1,opt,name=operatorId" json:"operatorId,omitempty"`
	ContractId  string `protobuf:"bytes,2,opt,name=contractId" json:"contractId,omitempty"`
	OperateTime uint64 `protobuf:"varint,3,opt,name=operateTime" json:"operateTime,omitempty"`
}

func (m *ContractCancel) Reset()                    { *m = ContractCancel{} }
func (m *ContractCancel) String() string            { return proto.CompactTextString(m) }
func (*ContractCancel) ProtoMessage()               {}
func (*ContractCancel) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ContractCancel) GetOperatorId() string {
	if m != nil {
		return m.OperatorId
	}
	return ""
}

func (m *ContractCancel) GetContractId() string {
	if m != nil {
		return m.ContractId
	}
	return ""
}

func (m *ContractCancel) GetOperateTime() uint64 {
	if m != nil {
		return m.OperateTime
	}
	return 0
}

// 修改合同，操作者签名，仅当所有签署者均未签名时可操作
type ContractModify struct {
	OperatorId         string   `protobuf:"bytes,1,opt,name=operatorId" json:"operatorId,omitempty"`
	ContractId         string   `protobuf:"bytes,2,opt,name=contractId" json:"contractId,omitempty"`
	ContractHash       string   `protobuf:"bytes,3,opt,name=contractHash" json:"contractHash,omitempty"`
	SignedContractHash string   `protobuf:"bytes,4,opt,name=signedContractHash" json:"signedContractHash,omitempty"`
	ContractName       string   `protobuf:"bytes,5,opt,name=contractName" json:"contractName,omitempty"`
	Amount             uint64   `protobuf:"varint,6,opt,name=amount" json:"amount,omitempty"`
	SignatoryIds       []string `protobuf:"bytes,7,rep,name=signatoryIds" json:"signatoryIds,omitempty"`
	OperateTime        uint64   `protobuf:"varint,8,opt,name=operateTime" json:"operateTime,omitempty"`
}

func (m *ContractModify) Reset()                    { *m = ContractModify{} }
func (m *ContractModify) String() string            { return proto.CompactTextString(m) }
func (*ContractModify) ProtoMessage()               {}
func (*ContractModify) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ContractModify) GetOperatorId() string {
	if m != nil {
		return m.OperatorId
	}
	return ""
}

func (m *ContractModify) GetContractId() string {
	if m != nil {
		return m.ContractId
	}
	return ""
}

func (m *ContractModify) GetContractHash() string {
	if m != nil {
		return m.ContractHash
	}
	return ""
}

func (m *ContractModify) GetSignedContractHash() string {
	if m != nil {
		return m.SignedContractHash
	}
	return ""
}

func (m *ContractModify) GetContractName() string {
	if m != nil {
		return m.ContractName
	}
	return ""
}

func (m *ContractModify) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ContractModify) GetSignatoryIds() []string {
	if m != nil {
		return m.SignatoryIds
	}
	return nil
}

func (m *ContractModify) GetOperateTime() uint64 {
	if m != nil {
		return m.OperateTime
	}
	return 0
}

// 签署合同，操作者签名
type ContractSign struct {
	OperatorId         string `protobuf:"bytes,1,opt,name=operatorId" json:"operatorId,omitempty"`
	ContractId         string `protobuf:"bytes,2,opt,name=contractId" json:"contractId,omitempty"`
	SignedContractHash string `protobuf:"bytes,3,opt,name=signedContractHash" json:"signedContractHash,omitempty"`
	OperateTime        uint64 `protobuf:"varint,4,opt,name=operateTime" json:"operateTime,omitempty"`
}

func (m *ContractSign) Reset()                    { *m = ContractSign{} }
func (m *ContractSign) String() string            { return proto.CompactTextString(m) }
func (*ContractSign) ProtoMessage()               {}
func (*ContractSign) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ContractSign) GetOperatorId() string {
	if m != nil {
		return m.OperatorId
	}
	return ""
}

func (m *ContractSign) GetContractId() string {
	if m != nil {
		return m.ContractId
	}
	return ""
}

func (m *ContractSign) GetSignedContractHash() string {
	if m != nil {
		return m.SignedContractHash
	}
	return ""
}

func (m *ContractSign) GetOperateTime() uint64 {
	if m != nil {
		return m.OperateTime
	}
	return 0
}

// 拒绝合同，操作者签名
type ContractReject struct {
	OperatorId  string `protobuf:"bytes,1,opt,name=operatorId" json:"operatorId,omitempty"`
	ContractId  string `protobuf:"bytes,2,opt,name=contractId" json:"contractId,omitempty"`
	OperateTime uint64 `protobuf:"varint,3,opt,name=operateTime" json:"operateTime,omitempty"`
}

func (m *ContractReject) Reset()                    { *m = ContractReject{} }
func (m *ContractReject) String() string            { return proto.CompactTextString(m) }
func (*ContractReject) ProtoMessage()               {}
func (*ContractReject) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ContractReject) GetOperatorId() string {
	if m != nil {
		return m.OperatorId
	}
	return ""
}

func (m *ContractReject) GetContractId() string {
	if m != nil {
		return m.ContractId
	}
	return ""
}

func (m *ContractReject) GetOperateTime() uint64 {
	if m != nil {
		return m.OperateTime
	}
	return 0
}

// 合同信息
type Contract struct {
	ContractId   string         `protobuf:"bytes,1,opt,name=contractId" json:"contractId,omitempty"`
	ContractHash string         `protobuf:"bytes,2,opt,name=contractHash" json:"contractHash,omitempty"`
	ContractName string         `protobuf:"bytes,3,opt,name=contractName" json:"contractName,omitempty"`
	Amount       uint64         `protobuf:"varint,4,opt,name=amount" json:"amount,omitempty"`
	Creator      *Creator       `protobuf:"bytes,5,opt,name=creator" json:"creator,omitempty"`
	Signatories  []*Signatory   `protobuf:"bytes,6,rep,name=signatories" json:"signatories,omitempty"`
	CreateTime   uint64         `protobuf:"varint,7,opt,name=createTime" json:"createTime,omitempty"`
	UpdateTime   uint64         `protobuf:"varint,8,opt,name=updateTime" json:"updateTime,omitempty"`
	Status       ContractStatus `protobuf:"varint,9,opt,name=status,enum=types.ContractStatus" json:"status,omitempty"`
}

func (m *Contract) Reset()                    { *m = Contract{} }
func (m *Contract) String() string            { return proto.CompactTextString(m) }
func (*Contract) ProtoMessage()               {}
func (*Contract) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Contract) GetContractId() string {
	if m != nil {
		return m.ContractId
	}
	return ""
}

func (m *Contract) GetContractHash() string {
	if m != nil {
		return m.ContractHash
	}
	return ""
}

func (m *Contract) GetContractName() string {
	if m != nil {
		return m.ContractName
	}
	return ""
}

func (m *Contract) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Contract) GetCreator() *Creator {
	if m != nil {
		return m.Creator
	}
	return nil
}

func (m *Contract) GetSignatories() []*Signatory {
	if m != nil {
		return m.Signatories
	}
	return nil
}

func (m *Contract) GetCreateTime() uint64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *Contract) GetUpdateTime() uint64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *Contract) GetStatus() ContractStatus {
	if m != nil {
		return m.Status
	}
	return ContractStatus_CS_Unknown
}

// 发起者
type Creator struct {
	Id           string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	ContractHash string `protobuf:"bytes,2,opt,name=contractHash" json:"contractHash,omitempty"`
	//    string name = 3;
	SignStatus SignStatus `protobuf:"varint,3,opt,name=signStatus,enum=types.SignStatus" json:"signStatus,omitempty"`
	SignTime   uint64     `protobuf:"varint,4,opt,name=signTime" json:"signTime,omitempty"`
	CancelTime uint64     `protobuf:"varint,5,opt,name=cancelTime" json:"cancelTime,omitempty"`
}

func (m *Creator) Reset()                    { *m = Creator{} }
func (m *Creator) String() string            { return proto.CompactTextString(m) }
func (*Creator) ProtoMessage()               {}
func (*Creator) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Creator) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Creator) GetContractHash() string {
	if m != nil {
		return m.ContractHash
	}
	return ""
}

func (m *Creator) GetSignStatus() SignStatus {
	if m != nil {
		return m.SignStatus
	}
	return SignStatus_SS_Unknown
}

func (m *Creator) GetSignTime() uint64 {
	if m != nil {
		return m.SignTime
	}
	return 0
}

func (m *Creator) GetCancelTime() uint64 {
	if m != nil {
		return m.CancelTime
	}
	return 0
}

// 签署者
type Signatory struct {
	Id           string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	ContractHash string `protobuf:"bytes,2,opt,name=contractHash" json:"contractHash,omitempty"`
	//    string name = 3;
	SignStatus SignStatus `protobuf:"varint,3,opt,name=signStatus,enum=types.SignStatus" json:"signStatus,omitempty"`
	SignTime   uint64     `protobuf:"varint,4,opt,name=signTime" json:"signTime,omitempty"`
	RejectTime uint64     `protobuf:"varint,5,opt,name=rejectTime" json:"rejectTime,omitempty"`
}

func (m *Signatory) Reset()                    { *m = Signatory{} }
func (m *Signatory) String() string            { return proto.CompactTextString(m) }
func (*Signatory) ProtoMessage()               {}
func (*Signatory) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Signatory) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Signatory) GetContractHash() string {
	if m != nil {
		return m.ContractHash
	}
	return ""
}

func (m *Signatory) GetSignStatus() SignStatus {
	if m != nil {
		return m.SignStatus
	}
	return SignStatus_SS_Unknown
}

func (m *Signatory) GetSignTime() uint64 {
	if m != nil {
		return m.SignTime
	}
	return 0
}

func (m *Signatory) GetRejectTime() uint64 {
	if m != nil {
		return m.RejectTime
	}
	return 0
}

type ReqId struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *ReqId) Reset()                    { *m = ReqId{} }
func (m *ReqId) String() string            { return proto.CompactTextString(m) }
func (*ReqId) ProtoMessage()               {}
func (*ReqId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ReqId) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*ContractAction)(nil), "types.ContractAction")
	proto.RegisterType((*ContractCreate)(nil), "types.ContractCreate")
	proto.RegisterType((*ContractCancel)(nil), "types.ContractCancel")
	proto.RegisterType((*ContractModify)(nil), "types.ContractModify")
	proto.RegisterType((*ContractSign)(nil), "types.ContractSign")
	proto.RegisterType((*ContractReject)(nil), "types.ContractReject")
	proto.RegisterType((*Contract)(nil), "types.Contract")
	proto.RegisterType((*Creator)(nil), "types.Creator")
	proto.RegisterType((*Signatory)(nil), "types.Signatory")
	proto.RegisterType((*ReqId)(nil), "types.ReqId")
	proto.RegisterEnum("types.ContractStatus", ContractStatus_name, ContractStatus_value)
	proto.RegisterEnum("types.SignStatus", SignStatus_name, SignStatus_value)
	proto.RegisterEnum("types.ContractActionType", ContractActionType_name, ContractActionType_value)
}

func init() { proto.RegisterFile("contract.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 847 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0xcb, 0x6e, 0xf3, 0x44,
	0x14, 0x8e, 0x1d, 0x5f, 0x92, 0x93, 0xd4, 0xbf, 0xff, 0x41, 0x80, 0xf9, 0x17, 0x6d, 0xe4, 0x05,
	0x0a, 0x11, 0xa4, 0x22, 0x88, 0x07, 0x48, 0xd2, 0x4a, 0xcd, 0xa2, 0x2c, 0xc6, 0x41, 0xea, 0x2e,
	0x98, 0x78, 0x52, 0x0c, 0x8d, 0x1d, 0x6c, 0xa7, 0x28, 0x1b, 0xd4, 0x0d, 0x1b, 0x9e, 0x80, 0x87,
	0x40, 0x3c, 0x06, 0x1b, 0x1e, 0x80, 0x65, 0xa5, 0x3e, 0x09, 0x9a, 0x33, 0xbe, 0xe3, 0x54, 0x5d,
	0x54, 0x82, 0x9d, 0xcf, 0x9c, 0xef, 0xdc, 0x3e, 0x7f, 0x3e, 0x63, 0x30, 0xd6, 0x61, 0x90, 0x44,
	0xee, 0x3a, 0x19, 0xef, 0xa2, 0x30, 0x09, 0x89, 0x9a, 0x1c, 0x76, 0x2c, 0x7e, 0xf7, 0xd1, 0xbd,
	0x7b, 0xe7, 0x7b, 0x6e, 0x12, 0x46, 0xe7, 0xf9, 0x93, 0x40, 0xd8, 0xbf, 0xc9, 0x60, 0xcc, 0xd3,
	0xa0, 0xe9, 0x3a, 0xf1, 0xc3, 0x80, 0x9c, 0x83, 0xb6, 0x8e, 0x98, 0x9b, 0x30, 0x4b, 0x1a, 0x48,
	0xc3, 0xde, 0xe4, 0xfd, 0x31, 0x66, 0x19, 0x67, 0xb0, 0x39, 0x3a, 0xaf, 0x5a, 0x34, 0x85, 0x61,
	0x80, 0x1b, 0xac, 0xd9, 0x9d, 0x25, 0x37, 0x07, 0xa0, 0x13, 0x03, 0xf0, 0x89, 0x07, 0x6c, 0x43,
	0xcf, 0xdf, 0x1c, 0xac, 0x76, 0x63, 0xc0, 0x35, 0x3a, 0x79, 0x80, 0x80, 0x91, 0x4f, 0x40, 0x89,
	0xfd, 0xdb, 0xc0, 0x52, 0x10, 0xfe, 0x5e, 0x0d, 0xee, 0xf8, 0xb7, 0xc1, 0x55, 0x8b, 0x22, 0x84,
	0xe7, 0x8e, 0xd8, 0xf7, 0x6c, 0x9d, 0x58, 0x6a, 0x63, 0x6e, 0x8a, 0x4e, 0x9e, 0x5b, 0xc0, 0x88,
	0x01, 0x72, 0x72, 0xb0, 0xbc, 0x81, 0x34, 0x54, 0xa9, 0x9c, 0x1c, 0x66, 0x3a, 0xa8, 0xf7, 0xee,
	0xdd, 0x9e, 0xd9, 0xbf, 0xb4, 0x0b, 0x6a, 0xc4, 0xcc, 0xe4, 0x63, 0x80, 0x70, 0xc7, 0x22, 0xce,
	0xdf, 0xc2, 0x43, 0x7a, 0xba, 0x33, 0xed, 0xe9, 0xf1, 0x4c, 0xbe, 0x91, 0x68, 0xc9, 0xc3, 0x71,
	0xd9, 0x9b, 0x58, 0x78, 0xc8, 0x4a, 0x09, 0x57, 0x78, 0xc8, 0x97, 0xd0, 0xcf, 0xac, 0x2b, 0x37,
	0xfe, 0x0e, 0xe9, 0xe8, 0xce, 0xde, 0x3e, 0x3d, 0x9e, 0x9d, 0x8c, 0xf4, 0xcb, 0x28, 0xe2, 0x87,
	0x0f, 0xd2, 0x83, 0x44, 0x2b, 0x30, 0x32, 0x2a, 0xc2, 0xbe, 0x72, 0xb7, 0x0c, 0x69, 0x29, 0x0a,
	0x54, 0x7c, 0xe4, 0x14, 0x34, 0x77, 0x1b, 0xee, 0x03, 0xc1, 0x87, 0x22, 0x50, 0x66, 0x8b, 0xa6,
	0xa7, 0xe4, 0x53, 0xe8, 0x73, 0xde, 0x78, 0xe3, 0x87, 0x85, 0x17, 0x5b, 0xda, 0xa0, 0x3d, 0xec,
	0xce, 0x3a, 0x4f, 0x8f, 0x67, 0xca, 0x8d, 0xf4, 0x8d, 0x44, 0x2b, 0x5e, 0x62, 0x81, 0xee, 0xc7,
	0x17, 0x91, 0xbb, 0x49, 0x2c, 0x7d, 0x20, 0x0d, 0x3b, 0x34, 0x33, 0xc9, 0x18, 0x08, 0x47, 0x32,
	0x6f, 0x5e, 0x1e, 0xa8, 0xc3, 0x3b, 0xa3, 0x0d, 0x1e, 0x32, 0x84, 0x9e, 0x20, 0x8c, 0x2d, 0xfd,
	0x2d, 0xb3, 0xba, 0x95, 0xe6, 0xca, 0x2e, 0xfb, 0x57, 0xa9, 0xf4, 0x1e, 0x84, 0x80, 0x5e, 0xfb,
	0x3d, 0xd4, 0x9a, 0x69, 0x1f, 0x6f, 0xe6, 0xcf, 0xd2, 0xf7, 0x22, 0x64, 0xfa, 0xea, 0xcd, 0xd8,
	0x4d, 0xa2, 0xa8, 0x29, 0xa0, 0x99, 0x6d, 0xe5, 0x28, 0xdb, 0x76, 0x4d, 0x31, 0x6a, 0x35, 0x27,
	0x2a, 0xe5, 0x83, 0x5c, 0x29, 0x1a, 0x9f, 0x3f, 0x57, 0xc8, 0xa8, 0xa6, 0x10, 0x1d, 0x15, 0x92,
	0xab, 0xad, 0xa2, 0x8f, 0x1a, 0x91, 0x9d, 0xe3, 0x44, 0xfe, 0x25, 0x41, 0xbf, 0xfc, 0x01, 0xbf,
	0x3a, 0x8d, 0xd3, 0x46, 0x8a, 0x8e, 0x7e, 0x61, 0x2f, 0xd0, 0xa8, 0xf2, 0x32, 0x8d, 0x8a, 0x0d,
	0xf3, 0x1f, 0x6a, 0xf4, 0x6f, 0x19, 0x3a, 0x59, 0x33, 0xe4, 0xb4, 0x92, 0x1e, 0xdb, 0x78, 0x56,
	0x6d, 0x72, 0x83, 0xda, 0xea, 0xea, 0x69, 0x3f, 0xab, 0x1e, 0xa5, 0xa2, 0x9e, 0x21, 0xe8, 0x78,
	0x4d, 0x84, 0x51, 0xba, 0x90, 0x8d, 0x6c, 0x21, 0x8b, 0x53, 0x9a, 0xb9, 0xc9, 0x04, 0x7a, 0x99,
	0x96, 0x7c, 0x26, 0x16, 0x51, 0x6f, 0x62, 0xa6, 0x68, 0x27, 0x53, 0x19, 0x2d, 0x83, 0x70, 0x3a,
	0x5c, 0xcd, 0xc8, 0x89, 0x8e, 0x95, 0x4b, 0x27, 0xdc, 0xbf, 0xdf, 0x79, 0x15, 0x39, 0xd2, 0xd2,
	0x09, 0xf9, 0x0c, 0xb4, 0x38, 0x71, 0x93, 0x7d, 0x8c, 0x0b, 0xc8, 0xf8, 0xd7, 0x6d, 0xe1, 0xa0,
	0x93, 0xa6, 0x20, 0xfb, 0x77, 0x09, 0xf4, 0xb4, 0x6f, 0x7e, 0x6f, 0xf8, 0x19, 0xa1, 0xb2, 0xff,
	0x32, 0x22, 0x3f, 0x07, 0xe0, 0xdd, 0x8b, 0xac, 0x48, 0xa3, 0x31, 0x79, 0x5b, 0x9a, 0x30, 0x2d,
	0x57, 0x02, 0x91, 0x77, 0xd0, 0xe1, 0x56, 0x21, 0x40, 0x9a, 0xdb, 0x38, 0x3d, 0x2e, 0x44, 0xf4,
	0xaa, 0xe9, 0xf4, 0xf9, 0x89, 0xfd, 0x87, 0x04, 0xdd, 0x9c, 0xb8, 0xff, 0x49, 0xc3, 0xe2, 0xd6,
	0x2d, 0x37, 0x5c, 0x9c, 0xd8, 0x1f, 0x82, 0x4a, 0xd9, 0x8f, 0x0b, 0xaf, 0xde, 0xeb, 0x68, 0x5f,
	0x7c, 0x5e, 0x69, 0x19, 0x03, 0x60, 0xee, 0xac, 0xbe, 0x0e, 0x7e, 0x08, 0xc2, 0x9f, 0x02, 0xb3,
	0x45, 0x08, 0x18, 0x73, 0x67, 0xb5, 0x08, 0xd8, 0x66, 0xc3, 0xd6, 0x89, 0x7f, 0xcf, 0x4c, 0x89,
	0x98, 0xd0, 0x9f, 0x3b, 0xab, 0xcb, 0xfc, 0x44, 0x4e, 0xa3, 0x2e, 0xfc, 0x78, 0x1f, 0x33, 0xcf,
	0x6c, 0x93, 0x3e, 0x74, 0xb8, 0xcd, 0x6f, 0x30, 0x53, 0x21, 0x6f, 0xa0, 0x37, 0x77, 0x56, 0xe2,
	0x8e, 0x61, 0x9e, 0xa9, 0x8e, 0xae, 0x01, 0x8a, 0x29, 0x79, 0xb0, 0x53, 0x2e, 0xf9, 0x06, 0x7a,
	0x68, 0x8b, 0xcd, 0x61, 0x4a, 0xe4, 0x04, 0xba, 0x8e, 0xb3, 0x72, 0x84, 0x29, 0xa7, 0x7e, 0xb1,
	0x0e, 0x78, 0xb5, 0xd1, 0xcf, 0x40, 0xaa, 0xff, 0x5a, 0xcb, 0xc3, 0x8e, 0xf1, 0xb4, 0xd3, 0x65,
	0x29, 0xed, 0x09, 0x74, 0xa7, 0xcb, 0x95, 0xf8, 0xe3, 0x10, 0x49, 0xb9, 0x89, 0x4d, 0x99, 0x72,
	0x6a, 0x8a, 0xab, 0xc7, 0x6c, 0x93, 0x1e, 0xe8, 0xd3, 0x25, 0x96, 0x34, 0x95, 0xd4, 0x27, 0x0a,
	0x9a, 0x2a, 0xaf, 0x8f, 0xe6, 0xad, 0x1f, 0x27, 0x2c, 0x32, 0xb5, 0x6f, 0x35, 0xfc, 0xe7, 0xfb,
	0xe2, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb9, 0x24, 0x6f, 0x04, 0x27, 0x0a, 0x00, 0x00,
}
