package types

import "errors"

var (
//逻辑处理错误
    ErrorWrongOperation = errors.New("无效操作")
 	ErrorMarketExist = errors.New("公司已存在")
    ErrorMarketNotExist    =    errors.New("公司不存在")
    ErrorWrongCoinType    =    errors.New("币种不存在")
    ErrorWrongRecNum    =    errors.New("数额错误")
    ErrorWrongMarket    =    errors.New("公司id错误")
    ErrorEmptyPubkey    =    errors.New("公钥为空")
    ErrorPubkey    =    errors.New("公钥错误")
    ErrorRecAmount    =    errors.New("充值数量错误")
    ErrorTokenName    =    errors.New("错误的代币名")
    ErrorKvBTY    =    errors.New("BTY记录不存在")
    ErrorAdmin    =    errors.New("管理员不存在")
    ErrorAdminExist    =    errors.New("管理员已存在")
    ErrorWrongMessage    =    errors.New("错误消息")
    ErrorUser    =    errors.New("用户不存在")
    ErrorOrder    =    errors.New("订单信息错误")
    ErrorUserExist    =    errors.New("用户已存在")
    ErrorMatchMessage    =    errors.New("公钥和用户不匹配")
    ErrorWrongPd    =    errors.New("商品不存在")
    ErrorWrongUid    =    errors.New("该用户与此订单不符")
    ErrorUserOwn    =    errors.New("用户bty余额不足")
    ErrorMarketInfo    =    errors.New("商家信息不匹配")
    ErrorPd    =    errors.New("添加商品状态错误")
    ErrorMarketOwn    =    errors.New("商家token余额不足")
    ErrorUserOpera    =    errors.New("用户已对该订单进行过操作")
    ErrorOrderExist    =    errors.New("订单已存在")
    ErrorOrderNotExist    =    errors.New("订单不存在")
    ErrorOrderMessage    =    errors.New("订单信息不匹配")
    ErrorUserFrozen    =    errors.New("用户冻结资产不足")
    ErrorWithDrawAmountLess    =    errors.New("用户资产不足")
    ErrorWithDrawAmount    =    errors.New("充值数量太少")
    ErrorToken    =    errors.New("不支持币种")
    ErrorAddress    =    errors.New("错误地址")
    ErrorCoinAddress    =    errors.New("错误代币地址")
    ErrorPdInfo    =    errors.New("已上线")
    ErrorPdInfoOff    =    errors.New("已下线请勿重复添加")
    ErrorPdDelete    =    errors.New("该订单已删除")
    ErrorTouser    =    errors.New("转让方不存在")
    ErrorUUid    =    errors.New("唯一标识符错误")
    ErrorOrderStatus    =    errors.New("订单状态不可更改")
    ErrorStatus    =    errors.New("状态不可为空")
    ErrorTokenAmount    =    errors.New("token数量不足")
    ErrorPdStatus    =    errors.New("商品已过期")
    ErrorPdExist    =    errors.New("商品已存在")
    ErrorPdNotExist    =    errors.New("商品不存在")
    ErrorCurrencyId    =    errors.New("无法识别的币种id")
    ErrorTokenTrans    =    errors.New("商家转让token数量错误")
    ErrorAddressExist    =    errors.New("用户地址id已经被占用")
    ErrorPdMatch    =    errors.New("商品id不符合")
    ErrorAddressId    =    errors.New("地址id不存在")
    ErrorOprea    =    errors.New("该用户无权对该订单进行操作")
    ErrorMarketOprea    =    errors.New("该商家无权对该订单进行操作")
    ErrorBookTime    =    errors.New("预售时间已结束")
    ErrorLastPayTime    =    errors.New("提货时间已结束")
    ErrorAmount    =    errors.New("可用资产不足")
    ErrorRecInfo    =    errors.New("充值操作未通过")
)


