// Code generated by protoc-gen-go. DO NOT EDIT.
// source: preSale.proto

/*
Package types is a generated protocol buffer package.

It is generated from these files:
	preSale.proto

It has these top-level messages:
	PreSaleMarketInfo
	PreSaleToken
	PreSaleAdminInfo
	PreSaleCurrency
	PreSaleUserInfo
	PreSaleAddress
	PreSaleOpreation
	PresalePdInfo
	PreSaleOrderInfo
	PreSaleAmount
	WithDrawPreSale
	PreSale
	PreSaleMarketReg
	CoinInfo
	PreSaleAdminReg
	PreSaleUserReg
	PreSaleMarketRec
	PreSaleUserRec
	PreSaleAddPdInfo
	PreSaleOnOffPd
	PreSaleUserPay
	PreSaleAddAddress
	PreSaleOrderTrans
	PreSaleMarketShip
	PreSaleLogistics
	PreSaleUserRecipt
	PreSaleOverDue
	PreSaleWithDraw
	PreSaleChangePd
	PreSaleUserTokenWithDraw
	PreSaleUserShip
	MarketInfoPreSale
	AdminInfoPreSale
	UserInfoSale
	PdInfoPresale
	OrderInfoPreSale
	OverDuePreSale
	WithDrawPS
*/
package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PreSalePayType int32

const (
	PreSalePayType_PreSaleErr     PreSalePayType = 0
	PreSalePayType_PreSalePayBook PreSalePayType = 1
	PreSalePayType_PreSalePayLast PreSalePayType = 2
)

var PreSalePayType_name = map[int32]string{
	0: "PreSaleErr",
	1: "PreSalePayBook",
	2: "PreSalePayLast",
}
var PreSalePayType_value = map[string]int32{
	"PreSaleErr":     0,
	"PreSalePayBook": 1,
	"PreSalePayLast": 2,
}

func (x PreSalePayType) String() string {
	return proto.EnumName(PreSalePayType_name, int32(x))
}
func (PreSalePayType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// key marketid
type PreSaleMarketInfo struct {
	MarketName string             `protobuf:"bytes,1,opt,name=marketName" json:"marketName,omitempty"`
	MarketId   int64              `protobuf:"varint,2,opt,name=marketId" json:"marketId,omitempty"`
	Contact    string             `protobuf:"bytes,3,opt,name=contact" json:"contact,omitempty"`
	PhoneNum   string             `protobuf:"bytes,4,opt,name=phoneNum" json:"phoneNum,omitempty"`
	Currency   []*PreSaleCurrency `protobuf:"bytes,5,rep,name=currency" json:"currency,omitempty"`
	Operate    *PreSaleOpreation  `protobuf:"bytes,6,opt,name=operate" json:"operate,omitempty"`
	Token      *PreSaleToken      `protobuf:"bytes,7,opt,name=token" json:"token,omitempty"`
	IsTokenSup bool               `protobuf:"varint,8,opt,name=isTokenSup" json:"isTokenSup,omitempty"`
}

func (m *PreSaleMarketInfo) Reset()                    { *m = PreSaleMarketInfo{} }
func (m *PreSaleMarketInfo) String() string            { return proto.CompactTextString(m) }
func (*PreSaleMarketInfo) ProtoMessage()               {}
func (*PreSaleMarketInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PreSaleMarketInfo) GetMarketName() string {
	if m != nil {
		return m.MarketName
	}
	return ""
}

func (m *PreSaleMarketInfo) GetMarketId() int64 {
	if m != nil {
		return m.MarketId
	}
	return 0
}

func (m *PreSaleMarketInfo) GetContact() string {
	if m != nil {
		return m.Contact
	}
	return ""
}

func (m *PreSaleMarketInfo) GetPhoneNum() string {
	if m != nil {
		return m.PhoneNum
	}
	return ""
}

func (m *PreSaleMarketInfo) GetCurrency() []*PreSaleCurrency {
	if m != nil {
		return m.Currency
	}
	return nil
}

func (m *PreSaleMarketInfo) GetOperate() *PreSaleOpreation {
	if m != nil {
		return m.Operate
	}
	return nil
}

func (m *PreSaleMarketInfo) GetToken() *PreSaleToken {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *PreSaleMarketInfo) GetIsTokenSup() bool {
	if m != nil {
		return m.IsTokenSup
	}
	return false
}

type PreSaleToken struct {
	MarketId    int64 `protobuf:"varint,1,opt,name=marketId" json:"marketId,omitempty"`
	UseAble     int64 `protobuf:"varint,2,opt,name=useAble" json:"useAble,omitempty"`
	TokenFrozen int64 `protobuf:"varint,3,opt,name=tokenFrozen" json:"tokenFrozen,omitempty"`
}

func (m *PreSaleToken) Reset()                    { *m = PreSaleToken{} }
func (m *PreSaleToken) String() string            { return proto.CompactTextString(m) }
func (*PreSaleToken) ProtoMessage()               {}
func (*PreSaleToken) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PreSaleToken) GetMarketId() int64 {
	if m != nil {
		return m.MarketId
	}
	return 0
}

func (m *PreSaleToken) GetUseAble() int64 {
	if m != nil {
		return m.UseAble
	}
	return 0
}

func (m *PreSaleToken) GetTokenFrozen() int64 {
	if m != nil {
		return m.TokenFrozen
	}
	return 0
}

// adminid
type PreSaleAdminInfo struct {
	AdminName string `protobuf:"bytes,1,opt,name=adminName" json:"adminName,omitempty"`
	AdminId   int64  `protobuf:"varint,2,opt,name=adminId" json:"adminId,omitempty"`
	Status    string `protobuf:"bytes,3,opt,name=status" json:"status,omitempty"`
}

func (m *PreSaleAdminInfo) Reset()                    { *m = PreSaleAdminInfo{} }
func (m *PreSaleAdminInfo) String() string            { return proto.CompactTextString(m) }
func (*PreSaleAdminInfo) ProtoMessage()               {}
func (*PreSaleAdminInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PreSaleAdminInfo) GetAdminName() string {
	if m != nil {
		return m.AdminName
	}
	return ""
}

func (m *PreSaleAdminInfo) GetAdminId() int64 {
	if m != nil {
		return m.AdminId
	}
	return 0
}

func (m *PreSaleAdminInfo) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type PreSaleCurrency struct {
	CurrencyName string `protobuf:"bytes,1,opt,name=currencyName" json:"currencyName,omitempty"`
	Address      string `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
	UseAble      int64  `protobuf:"varint,3,opt,name=useAble" json:"useAble,omitempty"`
	Frozen       int64  `protobuf:"varint,4,opt,name=frozen" json:"frozen,omitempty"`
}

func (m *PreSaleCurrency) Reset()                    { *m = PreSaleCurrency{} }
func (m *PreSaleCurrency) String() string            { return proto.CompactTextString(m) }
func (*PreSaleCurrency) ProtoMessage()               {}
func (*PreSaleCurrency) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PreSaleCurrency) GetCurrencyName() string {
	if m != nil {
		return m.CurrencyName
	}
	return ""
}

func (m *PreSaleCurrency) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *PreSaleCurrency) GetUseAble() int64 {
	if m != nil {
		return m.UseAble
	}
	return 0
}

func (m *PreSaleCurrency) GetFrozen() int64 {
	if m != nil {
		return m.Frozen
	}
	return 0
}

// uid
type PreSaleUserInfo struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Email    string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	PhoneNum string `protobuf:"bytes,3,opt,name=phoneNum" json:"phoneNum,omitempty"`
	Uid      int64  `protobuf:"varint,4,opt,name=uid" json:"uid,omitempty"`
	// PreSaleCurrency  eth   =5;
	// PreSaleCurrency  bty   =6;
	Currency []*PreSaleCurrency `protobuf:"bytes,6,rep,name=currency" json:"currency,omitempty"`
	Operate  *PreSaleOpreation  `protobuf:"bytes,7,opt,name=operate" json:"operate,omitempty"`
	Token    []*PreSaleToken    `protobuf:"bytes,8,rep,name=token" json:"token,omitempty"`
	Uuid     string             `protobuf:"bytes,9,opt,name=uuid" json:"uuid,omitempty"`
	Address  []*PreSaleAddress  `protobuf:"bytes,10,rep,name=address" json:"address,omitempty"`
}

func (m *PreSaleUserInfo) Reset()                    { *m = PreSaleUserInfo{} }
func (m *PreSaleUserInfo) String() string            { return proto.CompactTextString(m) }
func (*PreSaleUserInfo) ProtoMessage()               {}
func (*PreSaleUserInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PreSaleUserInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PreSaleUserInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *PreSaleUserInfo) GetPhoneNum() string {
	if m != nil {
		return m.PhoneNum
	}
	return ""
}

func (m *PreSaleUserInfo) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *PreSaleUserInfo) GetCurrency() []*PreSaleCurrency {
	if m != nil {
		return m.Currency
	}
	return nil
}

func (m *PreSaleUserInfo) GetOperate() *PreSaleOpreation {
	if m != nil {
		return m.Operate
	}
	return nil
}

func (m *PreSaleUserInfo) GetToken() []*PreSaleToken {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *PreSaleUserInfo) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *PreSaleUserInfo) GetAddress() []*PreSaleAddress {
	if m != nil {
		return m.Address
	}
	return nil
}

type PreSaleAddress struct {
	UserName  string `protobuf:"bytes,1,opt,name=userName" json:"userName,omitempty"`
	PhoneNum  string `protobuf:"bytes,2,opt,name=phoneNum" json:"phoneNum,omitempty"`
	Address   string `protobuf:"bytes,3,opt,name=address" json:"address,omitempty"`
	AddressId int64  `protobuf:"varint,4,opt,name=addressId" json:"addressId,omitempty"`
}

func (m *PreSaleAddress) Reset()                    { *m = PreSaleAddress{} }
func (m *PreSaleAddress) String() string            { return proto.CompactTextString(m) }
func (*PreSaleAddress) ProtoMessage()               {}
func (*PreSaleAddress) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PreSaleAddress) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *PreSaleAddress) GetPhoneNum() string {
	if m != nil {
		return m.PhoneNum
	}
	return ""
}

func (m *PreSaleAddress) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *PreSaleAddress) GetAddressId() int64 {
	if m != nil {
		return m.AddressId
	}
	return 0
}

type PreSaleOpreation struct {
	Time        int64  `protobuf:"varint,1,opt,name=time" json:"time,omitempty"`
	FromAddress string `protobuf:"bytes,2,opt,name=fromAddress" json:"fromAddress,omitempty"`
	ToAddress   string `protobuf:"bytes,3,opt,name=toAddress" json:"toAddress,omitempty"`
	Status      string `protobuf:"bytes,4,opt,name=status" json:"status,omitempty"`
	MinerFee    string `protobuf:"bytes,5,opt,name=minerFee" json:"minerFee,omitempty"`
}

func (m *PreSaleOpreation) Reset()                    { *m = PreSaleOpreation{} }
func (m *PreSaleOpreation) String() string            { return proto.CompactTextString(m) }
func (*PreSaleOpreation) ProtoMessage()               {}
func (*PreSaleOpreation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *PreSaleOpreation) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *PreSaleOpreation) GetFromAddress() string {
	if m != nil {
		return m.FromAddress
	}
	return ""
}

func (m *PreSaleOpreation) GetToAddress() string {
	if m != nil {
		return m.ToAddress
	}
	return ""
}

func (m *PreSaleOpreation) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *PreSaleOpreation) GetMinerFee() string {
	if m != nil {
		return m.MinerFee
	}
	return ""
}

// pdId
type PresalePdInfo struct {
	PdName     string `protobuf:"bytes,1,opt,name=pdName" json:"pdName,omitempty"`
	PdId       int64  `protobuf:"varint,2,opt,name=pdId" json:"pdId,omitempty"`
	Price      int64  `protobuf:"varint,3,opt,name=price" json:"price,omitempty"`
	Deposit    int64  `protobuf:"varint,4,opt,name=deposit" json:"deposit,omitempty"`
	PsStart    int64  `protobuf:"varint,5,opt,name=psStart" json:"psStart,omitempty"`
	PsEnd      int64  `protobuf:"varint,6,opt,name=psEnd" json:"psEnd,omitempty"`
	PuStart    int64  `protobuf:"varint,7,opt,name=puStart" json:"puStart,omitempty"`
	PuEnd      int64  `protobuf:"varint,8,opt,name=puEnd" json:"puEnd,omitempty"`
	MarketId   int64  `protobuf:"varint,9,opt,name=marketId" json:"marketId,omitempty"`
	MarketName string `protobuf:"bytes,10,opt,name=marketName" json:"marketName,omitempty"`
	AdminId    int64  `protobuf:"varint,11,opt,name=adminId" json:"adminId,omitempty"`
	Status     string `protobuf:"bytes,12,opt,name=status" json:"status,omitempty"`
}

func (m *PresalePdInfo) Reset()                    { *m = PresalePdInfo{} }
func (m *PresalePdInfo) String() string            { return proto.CompactTextString(m) }
func (*PresalePdInfo) ProtoMessage()               {}
func (*PresalePdInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *PresalePdInfo) GetPdName() string {
	if m != nil {
		return m.PdName
	}
	return ""
}

func (m *PresalePdInfo) GetPdId() int64 {
	if m != nil {
		return m.PdId
	}
	return 0
}

func (m *PresalePdInfo) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *PresalePdInfo) GetDeposit() int64 {
	if m != nil {
		return m.Deposit
	}
	return 0
}

func (m *PresalePdInfo) GetPsStart() int64 {
	if m != nil {
		return m.PsStart
	}
	return 0
}

func (m *PresalePdInfo) GetPsEnd() int64 {
	if m != nil {
		return m.PsEnd
	}
	return 0
}

func (m *PresalePdInfo) GetPuStart() int64 {
	if m != nil {
		return m.PuStart
	}
	return 0
}

func (m *PresalePdInfo) GetPuEnd() int64 {
	if m != nil {
		return m.PuEnd
	}
	return 0
}

func (m *PresalePdInfo) GetMarketId() int64 {
	if m != nil {
		return m.MarketId
	}
	return 0
}

func (m *PresalePdInfo) GetMarketName() string {
	if m != nil {
		return m.MarketName
	}
	return ""
}

func (m *PresalePdInfo) GetAdminId() int64 {
	if m != nil {
		return m.AdminId
	}
	return 0
}

func (m *PresalePdInfo) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

// todo 价格的形式还没定好
// orderId
type PreSaleOrderInfo struct {
	OrderId     int64 `protobuf:"varint,1,opt,name=orderId" json:"orderId,omitempty"`
	PdId        int64 `protobuf:"varint,2,opt,name=pdId" json:"pdId,omitempty"`
	Uid         int64 `protobuf:"varint,3,opt,name=uid" json:"uid,omitempty"`
	MarketId    int64 `protobuf:"varint,4,opt,name=marketId" json:"marketId,omitempty"`
	TokenAmount int64 `protobuf:"varint,5,opt,name=tokenAmount" json:"tokenAmount,omitempty"`
	// int64  btyAmount   		=6; //bty 买家给商家 一共转的数量
	// int64  ethAmount   		=7; //eth 买家给商家 一共转的数量
	Book         *PreSaleAmount `protobuf:"bytes,6,opt,name=book" json:"book,omitempty"`
	LastPay      *PreSaleAmount `protobuf:"bytes,7,opt,name=lastPay" json:"lastPay,omitempty"`
	UserName     string         `protobuf:"bytes,8,opt,name=userName" json:"userName,omitempty"`
	PhoneNum     string         `protobuf:"bytes,9,opt,name=phoneNum" json:"phoneNum,omitempty"`
	Address      string         `protobuf:"bytes,10,opt,name=address" json:"address,omitempty"`
	MarketStatus string         `protobuf:"bytes,11,opt,name=marketStatus" json:"marketStatus,omitempty"`
	UserStatus   string         `protobuf:"bytes,12,opt,name=userStatus" json:"userStatus,omitempty"`
	Express      string         `protobuf:"bytes,14,opt,name=express" json:"express,omitempty"`
	OrdNum       string         `protobuf:"bytes,15,opt,name=ordNum" json:"ordNum,omitempty"`
	ExpressTime  int64          `protobuf:"varint,16,opt,name=expressTime" json:"expressTime,omitempty"`
	AdminId      string         `protobuf:"bytes,17,opt,name=adminId" json:"adminId,omitempty"`
	OperateTime  int64          `protobuf:"varint,18,opt,name=operateTime" json:"operateTime,omitempty"`
	Status       string         `protobuf:"bytes,19,opt,name=status" json:"status,omitempty"`
	PdAmount     int64          `protobuf:"varint,20,opt,name=pdAmount" json:"pdAmount,omitempty"`
	PsStart      int64          `protobuf:"varint,21,opt,name=psStart" json:"psStart,omitempty"`
	PsEnd        int64          `protobuf:"varint,22,opt,name=psEnd" json:"psEnd,omitempty"`
	PuStart      int64          `protobuf:"varint,23,opt,name=puStart" json:"puStart,omitempty"`
	PuEnd        int64          `protobuf:"varint,24,opt,name=puEnd" json:"puEnd,omitempty"`
}

func (m *PreSaleOrderInfo) Reset()                    { *m = PreSaleOrderInfo{} }
func (m *PreSaleOrderInfo) String() string            { return proto.CompactTextString(m) }
func (*PreSaleOrderInfo) ProtoMessage()               {}
func (*PreSaleOrderInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *PreSaleOrderInfo) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *PreSaleOrderInfo) GetPdId() int64 {
	if m != nil {
		return m.PdId
	}
	return 0
}

func (m *PreSaleOrderInfo) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *PreSaleOrderInfo) GetMarketId() int64 {
	if m != nil {
		return m.MarketId
	}
	return 0
}

func (m *PreSaleOrderInfo) GetTokenAmount() int64 {
	if m != nil {
		return m.TokenAmount
	}
	return 0
}

func (m *PreSaleOrderInfo) GetBook() *PreSaleAmount {
	if m != nil {
		return m.Book
	}
	return nil
}

func (m *PreSaleOrderInfo) GetLastPay() *PreSaleAmount {
	if m != nil {
		return m.LastPay
	}
	return nil
}

func (m *PreSaleOrderInfo) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *PreSaleOrderInfo) GetPhoneNum() string {
	if m != nil {
		return m.PhoneNum
	}
	return ""
}

func (m *PreSaleOrderInfo) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *PreSaleOrderInfo) GetMarketStatus() string {
	if m != nil {
		return m.MarketStatus
	}
	return ""
}

func (m *PreSaleOrderInfo) GetUserStatus() string {
	if m != nil {
		return m.UserStatus
	}
	return ""
}

func (m *PreSaleOrderInfo) GetExpress() string {
	if m != nil {
		return m.Express
	}
	return ""
}

func (m *PreSaleOrderInfo) GetOrdNum() string {
	if m != nil {
		return m.OrdNum
	}
	return ""
}

func (m *PreSaleOrderInfo) GetExpressTime() int64 {
	if m != nil {
		return m.ExpressTime
	}
	return 0
}

func (m *PreSaleOrderInfo) GetAdminId() string {
	if m != nil {
		return m.AdminId
	}
	return ""
}

func (m *PreSaleOrderInfo) GetOperateTime() int64 {
	if m != nil {
		return m.OperateTime
	}
	return 0
}

func (m *PreSaleOrderInfo) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *PreSaleOrderInfo) GetPdAmount() int64 {
	if m != nil {
		return m.PdAmount
	}
	return 0
}

func (m *PreSaleOrderInfo) GetPsStart() int64 {
	if m != nil {
		return m.PsStart
	}
	return 0
}

func (m *PreSaleOrderInfo) GetPsEnd() int64 {
	if m != nil {
		return m.PsEnd
	}
	return 0
}

func (m *PreSaleOrderInfo) GetPuStart() int64 {
	if m != nil {
		return m.PuStart
	}
	return 0
}

func (m *PreSaleOrderInfo) GetPuEnd() int64 {
	if m != nil {
		return m.PuEnd
	}
	return 0
}

type PreSaleAmount struct {
	CurrencyName string `protobuf:"bytes,1,opt,name=currencyName" json:"currencyName,omitempty"`
	Amount       int64  `protobuf:"varint,2,opt,name=amount" json:"amount,omitempty"`
}

func (m *PreSaleAmount) Reset()                    { *m = PreSaleAmount{} }
func (m *PreSaleAmount) String() string            { return proto.CompactTextString(m) }
func (*PreSaleAmount) ProtoMessage()               {}
func (*PreSaleAmount) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *PreSaleAmount) GetCurrencyName() string {
	if m != nil {
		return m.CurrencyName
	}
	return ""
}

func (m *PreSaleAmount) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type WithDrawPreSale struct {
	Id        int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Amount    int64  `protobuf:"varint,2,opt,name=amount" json:"amount,omitempty"`
	ToAddress string `protobuf:"bytes,4,opt,name=toAddress" json:"toAddress,omitempty"`
	IsMarket  bool   `protobuf:"varint,5,opt,name=isMarket" json:"isMarket,omitempty"`
	Currency  string `protobuf:"bytes,6,opt,name=currency" json:"currency,omitempty"`
	IsToken   bool   `protobuf:"varint,7,opt,name=isToken" json:"isToken,omitempty"`
	Time      int64  `protobuf:"varint,8,opt,name=time" json:"time,omitempty"`
}

func (m *WithDrawPreSale) Reset()                    { *m = WithDrawPreSale{} }
func (m *WithDrawPreSale) String() string            { return proto.CompactTextString(m) }
func (*WithDrawPreSale) ProtoMessage()               {}
func (*WithDrawPreSale) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *WithDrawPreSale) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *WithDrawPreSale) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *WithDrawPreSale) GetToAddress() string {
	if m != nil {
		return m.ToAddress
	}
	return ""
}

func (m *WithDrawPreSale) GetIsMarket() bool {
	if m != nil {
		return m.IsMarket
	}
	return false
}

func (m *WithDrawPreSale) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *WithDrawPreSale) GetIsToken() bool {
	if m != nil {
		return m.IsToken
	}
	return false
}

func (m *WithDrawPreSale) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

// 资产信息要不要上链 我觉得不用上链
// 商家id和用户id可以一致
// payload
type PreSale struct {
	// Types that are valid to be assigned to Value:
	//	*PreSale_MarketReg
	//	*PreSale_AdminReg
	//	*PreSale_UserReg
	//	*PreSale_MarketRec
	//	*PreSale_UserRec
	//	*PreSale_AddPdInfo
	//	*PreSale_OnOffPd
	//	*PreSale_UserPay
	//	*PreSale_Address
	//	*PreSale_OrderTrans
	//	*PreSale_MarketShip
	//	*PreSale_Logistics
	//	*PreSale_UserRecipt
	//	*PreSale_OverDue
	//	*PreSale_WithDraw
	//	*PreSale_ChangePd
	//	*PreSale_UserTokenWithDraw
	//	*PreSale_UserShip
	Value isPreSale_Value `protobuf_oneof:"value"`
	Ty    int32           `protobuf:"varint,99,opt,name=ty" json:"ty,omitempty"`
}

func (m *PreSale) Reset()                    { *m = PreSale{} }
func (m *PreSale) String() string            { return proto.CompactTextString(m) }
func (*PreSale) ProtoMessage()               {}
func (*PreSale) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type isPreSale_Value interface {
	isPreSale_Value()
}

type PreSale_MarketReg struct {
	MarketReg *PreSaleMarketReg `protobuf:"bytes,1,opt,name=marketReg,oneof"`
}
type PreSale_AdminReg struct {
	AdminReg *PreSaleAdminReg `protobuf:"bytes,2,opt,name=adminReg,oneof"`
}
type PreSale_UserReg struct {
	UserReg *PreSaleUserReg `protobuf:"bytes,3,opt,name=userReg,oneof"`
}
type PreSale_MarketRec struct {
	MarketRec *PreSaleMarketRec `protobuf:"bytes,4,opt,name=marketRec,oneof"`
}
type PreSale_UserRec struct {
	UserRec *PreSaleUserRec `protobuf:"bytes,5,opt,name=userRec,oneof"`
}
type PreSale_AddPdInfo struct {
	AddPdInfo *PreSaleAddPdInfo `protobuf:"bytes,6,opt,name=addPdInfo,oneof"`
}
type PreSale_OnOffPd struct {
	OnOffPd *PreSaleOnOffPd `protobuf:"bytes,7,opt,name=onOffPd,oneof"`
}
type PreSale_UserPay struct {
	UserPay *PreSaleUserPay `protobuf:"bytes,8,opt,name=userPay,oneof"`
}
type PreSale_Address struct {
	Address *PreSaleAddAddress `protobuf:"bytes,9,opt,name=address,oneof"`
}
type PreSale_OrderTrans struct {
	OrderTrans *PreSaleOrderTrans `protobuf:"bytes,10,opt,name=orderTrans,oneof"`
}
type PreSale_MarketShip struct {
	MarketShip *PreSaleMarketShip `protobuf:"bytes,11,opt,name=marketShip,oneof"`
}
type PreSale_Logistics struct {
	Logistics *PreSaleLogistics `protobuf:"bytes,12,opt,name=logistics,oneof"`
}
type PreSale_UserRecipt struct {
	UserRecipt *PreSaleUserRecipt `protobuf:"bytes,13,opt,name=userRecipt,oneof"`
}
type PreSale_OverDue struct {
	OverDue *PreSaleOverDue `protobuf:"bytes,14,opt,name=overDue,oneof"`
}
type PreSale_WithDraw struct {
	WithDraw *PreSaleWithDraw `protobuf:"bytes,15,opt,name=withDraw,oneof"`
}
type PreSale_ChangePd struct {
	ChangePd *PreSaleChangePd `protobuf:"bytes,16,opt,name=changePd,oneof"`
}
type PreSale_UserTokenWithDraw struct {
	UserTokenWithDraw *PreSaleUserTokenWithDraw `protobuf:"bytes,17,opt,name=userTokenWithDraw,oneof"`
}
type PreSale_UserShip struct {
	UserShip *PreSaleUserShip `protobuf:"bytes,18,opt,name=userShip,oneof"`
}

func (*PreSale_MarketReg) isPreSale_Value()         {}
func (*PreSale_AdminReg) isPreSale_Value()          {}
func (*PreSale_UserReg) isPreSale_Value()           {}
func (*PreSale_MarketRec) isPreSale_Value()         {}
func (*PreSale_UserRec) isPreSale_Value()           {}
func (*PreSale_AddPdInfo) isPreSale_Value()         {}
func (*PreSale_OnOffPd) isPreSale_Value()           {}
func (*PreSale_UserPay) isPreSale_Value()           {}
func (*PreSale_Address) isPreSale_Value()           {}
func (*PreSale_OrderTrans) isPreSale_Value()        {}
func (*PreSale_MarketShip) isPreSale_Value()        {}
func (*PreSale_Logistics) isPreSale_Value()         {}
func (*PreSale_UserRecipt) isPreSale_Value()        {}
func (*PreSale_OverDue) isPreSale_Value()           {}
func (*PreSale_WithDraw) isPreSale_Value()          {}
func (*PreSale_ChangePd) isPreSale_Value()          {}
func (*PreSale_UserTokenWithDraw) isPreSale_Value() {}
func (*PreSale_UserShip) isPreSale_Value()          {}

func (m *PreSale) GetValue() isPreSale_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *PreSale) GetMarketReg() *PreSaleMarketReg {
	if x, ok := m.GetValue().(*PreSale_MarketReg); ok {
		return x.MarketReg
	}
	return nil
}

func (m *PreSale) GetAdminReg() *PreSaleAdminReg {
	if x, ok := m.GetValue().(*PreSale_AdminReg); ok {
		return x.AdminReg
	}
	return nil
}

func (m *PreSale) GetUserReg() *PreSaleUserReg {
	if x, ok := m.GetValue().(*PreSale_UserReg); ok {
		return x.UserReg
	}
	return nil
}

func (m *PreSale) GetMarketRec() *PreSaleMarketRec {
	if x, ok := m.GetValue().(*PreSale_MarketRec); ok {
		return x.MarketRec
	}
	return nil
}

func (m *PreSale) GetUserRec() *PreSaleUserRec {
	if x, ok := m.GetValue().(*PreSale_UserRec); ok {
		return x.UserRec
	}
	return nil
}

func (m *PreSale) GetAddPdInfo() *PreSaleAddPdInfo {
	if x, ok := m.GetValue().(*PreSale_AddPdInfo); ok {
		return x.AddPdInfo
	}
	return nil
}

func (m *PreSale) GetOnOffPd() *PreSaleOnOffPd {
	if x, ok := m.GetValue().(*PreSale_OnOffPd); ok {
		return x.OnOffPd
	}
	return nil
}

func (m *PreSale) GetUserPay() *PreSaleUserPay {
	if x, ok := m.GetValue().(*PreSale_UserPay); ok {
		return x.UserPay
	}
	return nil
}

func (m *PreSale) GetAddress() *PreSaleAddAddress {
	if x, ok := m.GetValue().(*PreSale_Address); ok {
		return x.Address
	}
	return nil
}

func (m *PreSale) GetOrderTrans() *PreSaleOrderTrans {
	if x, ok := m.GetValue().(*PreSale_OrderTrans); ok {
		return x.OrderTrans
	}
	return nil
}

func (m *PreSale) GetMarketShip() *PreSaleMarketShip {
	if x, ok := m.GetValue().(*PreSale_MarketShip); ok {
		return x.MarketShip
	}
	return nil
}

func (m *PreSale) GetLogistics() *PreSaleLogistics {
	if x, ok := m.GetValue().(*PreSale_Logistics); ok {
		return x.Logistics
	}
	return nil
}

func (m *PreSale) GetUserRecipt() *PreSaleUserRecipt {
	if x, ok := m.GetValue().(*PreSale_UserRecipt); ok {
		return x.UserRecipt
	}
	return nil
}

func (m *PreSale) GetOverDue() *PreSaleOverDue {
	if x, ok := m.GetValue().(*PreSale_OverDue); ok {
		return x.OverDue
	}
	return nil
}

func (m *PreSale) GetWithDraw() *PreSaleWithDraw {
	if x, ok := m.GetValue().(*PreSale_WithDraw); ok {
		return x.WithDraw
	}
	return nil
}

func (m *PreSale) GetChangePd() *PreSaleChangePd {
	if x, ok := m.GetValue().(*PreSale_ChangePd); ok {
		return x.ChangePd
	}
	return nil
}

func (m *PreSale) GetUserTokenWithDraw() *PreSaleUserTokenWithDraw {
	if x, ok := m.GetValue().(*PreSale_UserTokenWithDraw); ok {
		return x.UserTokenWithDraw
	}
	return nil
}

func (m *PreSale) GetUserShip() *PreSaleUserShip {
	if x, ok := m.GetValue().(*PreSale_UserShip); ok {
		return x.UserShip
	}
	return nil
}

func (m *PreSale) GetTy() int32 {
	if m != nil {
		return m.Ty
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*PreSale) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _PreSale_OneofMarshaler, _PreSale_OneofUnmarshaler, _PreSale_OneofSizer, []interface{}{
		(*PreSale_MarketReg)(nil),
		(*PreSale_AdminReg)(nil),
		(*PreSale_UserReg)(nil),
		(*PreSale_MarketRec)(nil),
		(*PreSale_UserRec)(nil),
		(*PreSale_AddPdInfo)(nil),
		(*PreSale_OnOffPd)(nil),
		(*PreSale_UserPay)(nil),
		(*PreSale_Address)(nil),
		(*PreSale_OrderTrans)(nil),
		(*PreSale_MarketShip)(nil),
		(*PreSale_Logistics)(nil),
		(*PreSale_UserRecipt)(nil),
		(*PreSale_OverDue)(nil),
		(*PreSale_WithDraw)(nil),
		(*PreSale_ChangePd)(nil),
		(*PreSale_UserTokenWithDraw)(nil),
		(*PreSale_UserShip)(nil),
	}
}

func _PreSale_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*PreSale)
	// value
	switch x := m.Value.(type) {
	case *PreSale_MarketReg:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MarketReg); err != nil {
			return err
		}
	case *PreSale_AdminReg:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.AdminReg); err != nil {
			return err
		}
	case *PreSale_UserReg:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.UserReg); err != nil {
			return err
		}
	case *PreSale_MarketRec:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MarketRec); err != nil {
			return err
		}
	case *PreSale_UserRec:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.UserRec); err != nil {
			return err
		}
	case *PreSale_AddPdInfo:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.AddPdInfo); err != nil {
			return err
		}
	case *PreSale_OnOffPd:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.OnOffPd); err != nil {
			return err
		}
	case *PreSale_UserPay:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.UserPay); err != nil {
			return err
		}
	case *PreSale_Address:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Address); err != nil {
			return err
		}
	case *PreSale_OrderTrans:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.OrderTrans); err != nil {
			return err
		}
	case *PreSale_MarketShip:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MarketShip); err != nil {
			return err
		}
	case *PreSale_Logistics:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Logistics); err != nil {
			return err
		}
	case *PreSale_UserRecipt:
		b.EncodeVarint(13<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.UserRecipt); err != nil {
			return err
		}
	case *PreSale_OverDue:
		b.EncodeVarint(14<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.OverDue); err != nil {
			return err
		}
	case *PreSale_WithDraw:
		b.EncodeVarint(15<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.WithDraw); err != nil {
			return err
		}
	case *PreSale_ChangePd:
		b.EncodeVarint(16<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ChangePd); err != nil {
			return err
		}
	case *PreSale_UserTokenWithDraw:
		b.EncodeVarint(17<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.UserTokenWithDraw); err != nil {
			return err
		}
	case *PreSale_UserShip:
		b.EncodeVarint(18<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.UserShip); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("PreSale.Value has unexpected type %T", x)
	}
	return nil
}

func _PreSale_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*PreSale)
	switch tag {
	case 1: // value.marketReg
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PreSaleMarketReg)
		err := b.DecodeMessage(msg)
		m.Value = &PreSale_MarketReg{msg}
		return true, err
	case 2: // value.adminReg
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PreSaleAdminReg)
		err := b.DecodeMessage(msg)
		m.Value = &PreSale_AdminReg{msg}
		return true, err
	case 3: // value.userReg
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PreSaleUserReg)
		err := b.DecodeMessage(msg)
		m.Value = &PreSale_UserReg{msg}
		return true, err
	case 4: // value.marketRec
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PreSaleMarketRec)
		err := b.DecodeMessage(msg)
		m.Value = &PreSale_MarketRec{msg}
		return true, err
	case 5: // value.userRec
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PreSaleUserRec)
		err := b.DecodeMessage(msg)
		m.Value = &PreSale_UserRec{msg}
		return true, err
	case 6: // value.addPdInfo
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PreSaleAddPdInfo)
		err := b.DecodeMessage(msg)
		m.Value = &PreSale_AddPdInfo{msg}
		return true, err
	case 7: // value.onOffPd
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PreSaleOnOffPd)
		err := b.DecodeMessage(msg)
		m.Value = &PreSale_OnOffPd{msg}
		return true, err
	case 8: // value.userPay
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PreSaleUserPay)
		err := b.DecodeMessage(msg)
		m.Value = &PreSale_UserPay{msg}
		return true, err
	case 9: // value.address
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PreSaleAddAddress)
		err := b.DecodeMessage(msg)
		m.Value = &PreSale_Address{msg}
		return true, err
	case 10: // value.orderTrans
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PreSaleOrderTrans)
		err := b.DecodeMessage(msg)
		m.Value = &PreSale_OrderTrans{msg}
		return true, err
	case 11: // value.marketShip
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PreSaleMarketShip)
		err := b.DecodeMessage(msg)
		m.Value = &PreSale_MarketShip{msg}
		return true, err
	case 12: // value.logistics
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PreSaleLogistics)
		err := b.DecodeMessage(msg)
		m.Value = &PreSale_Logistics{msg}
		return true, err
	case 13: // value.userRecipt
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PreSaleUserRecipt)
		err := b.DecodeMessage(msg)
		m.Value = &PreSale_UserRecipt{msg}
		return true, err
	case 14: // value.overDue
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PreSaleOverDue)
		err := b.DecodeMessage(msg)
		m.Value = &PreSale_OverDue{msg}
		return true, err
	case 15: // value.withDraw
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PreSaleWithDraw)
		err := b.DecodeMessage(msg)
		m.Value = &PreSale_WithDraw{msg}
		return true, err
	case 16: // value.changePd
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PreSaleChangePd)
		err := b.DecodeMessage(msg)
		m.Value = &PreSale_ChangePd{msg}
		return true, err
	case 17: // value.userTokenWithDraw
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PreSaleUserTokenWithDraw)
		err := b.DecodeMessage(msg)
		m.Value = &PreSale_UserTokenWithDraw{msg}
		return true, err
	case 18: // value.userShip
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PreSaleUserShip)
		err := b.DecodeMessage(msg)
		m.Value = &PreSale_UserShip{msg}
		return true, err
	default:
		return false, nil
	}
}

func _PreSale_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*PreSale)
	// value
	switch x := m.Value.(type) {
	case *PreSale_MarketReg:
		s := proto.Size(x.MarketReg)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PreSale_AdminReg:
		s := proto.Size(x.AdminReg)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PreSale_UserReg:
		s := proto.Size(x.UserReg)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PreSale_MarketRec:
		s := proto.Size(x.MarketRec)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PreSale_UserRec:
		s := proto.Size(x.UserRec)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PreSale_AddPdInfo:
		s := proto.Size(x.AddPdInfo)
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PreSale_OnOffPd:
		s := proto.Size(x.OnOffPd)
		n += proto.SizeVarint(7<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PreSale_UserPay:
		s := proto.Size(x.UserPay)
		n += proto.SizeVarint(8<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PreSale_Address:
		s := proto.Size(x.Address)
		n += proto.SizeVarint(9<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PreSale_OrderTrans:
		s := proto.Size(x.OrderTrans)
		n += proto.SizeVarint(10<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PreSale_MarketShip:
		s := proto.Size(x.MarketShip)
		n += proto.SizeVarint(11<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PreSale_Logistics:
		s := proto.Size(x.Logistics)
		n += proto.SizeVarint(12<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PreSale_UserRecipt:
		s := proto.Size(x.UserRecipt)
		n += proto.SizeVarint(13<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PreSale_OverDue:
		s := proto.Size(x.OverDue)
		n += proto.SizeVarint(14<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PreSale_WithDraw:
		s := proto.Size(x.WithDraw)
		n += proto.SizeVarint(15<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PreSale_ChangePd:
		s := proto.Size(x.ChangePd)
		n += proto.SizeVarint(16<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PreSale_UserTokenWithDraw:
		s := proto.Size(x.UserTokenWithDraw)
		n += proto.SizeVarint(17<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PreSale_UserShip:
		s := proto.Size(x.UserShip)
		n += proto.SizeVarint(18<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// id存本地数据库    商家信息上链
type PreSaleMarketReg struct {
	MarketName string `protobuf:"bytes,1,opt,name=marketName" json:"marketName,omitempty"`
	MarketId   int64  `protobuf:"varint,2,opt,name=marketId" json:"marketId,omitempty"`
	Contact    string `protobuf:"bytes,3,opt,name=contact" json:"contact,omitempty"`
	PhoneNum   string `protobuf:"bytes,4,opt,name=phoneNum" json:"phoneNum,omitempty"`
	// string btyAddress   =5;//bty地址
	// string ethAddress   =6;//eth地址
	Currency   []*CoinInfo `protobuf:"bytes,5,rep,name=currency" json:"currency,omitempty"`
	IsTokenSup bool        `protobuf:"varint,6,opt,name=isTokenSup" json:"isTokenSup,omitempty"`
}

func (m *PreSaleMarketReg) Reset()                    { *m = PreSaleMarketReg{} }
func (m *PreSaleMarketReg) String() string            { return proto.CompactTextString(m) }
func (*PreSaleMarketReg) ProtoMessage()               {}
func (*PreSaleMarketReg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *PreSaleMarketReg) GetMarketName() string {
	if m != nil {
		return m.MarketName
	}
	return ""
}

func (m *PreSaleMarketReg) GetMarketId() int64 {
	if m != nil {
		return m.MarketId
	}
	return 0
}

func (m *PreSaleMarketReg) GetContact() string {
	if m != nil {
		return m.Contact
	}
	return ""
}

func (m *PreSaleMarketReg) GetPhoneNum() string {
	if m != nil {
		return m.PhoneNum
	}
	return ""
}

func (m *PreSaleMarketReg) GetCurrency() []*CoinInfo {
	if m != nil {
		return m.Currency
	}
	return nil
}

func (m *PreSaleMarketReg) GetIsTokenSup() bool {
	if m != nil {
		return m.IsTokenSup
	}
	return false
}

type CoinInfo struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// int64  coinId=2;
	Address string `protobuf:"bytes,3,opt,name=Address" json:"Address,omitempty"`
}

func (m *CoinInfo) Reset()                    { *m = CoinInfo{} }
func (m *CoinInfo) String() string            { return proto.CompactTextString(m) }
func (*CoinInfo) ProtoMessage()               {}
func (*CoinInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *CoinInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CoinInfo) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// id存本地数据库     管理员姓名上链
type PreSaleAdminReg struct {
	AdminName string `protobuf:"bytes,1,opt,name=adminName" json:"adminName,omitempty"`
	AdminId   int64  `protobuf:"varint,2,opt,name=adminId" json:"adminId,omitempty"`
}

func (m *PreSaleAdminReg) Reset()                    { *m = PreSaleAdminReg{} }
func (m *PreSaleAdminReg) String() string            { return proto.CompactTextString(m) }
func (*PreSaleAdminReg) ProtoMessage()               {}
func (*PreSaleAdminReg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *PreSaleAdminReg) GetAdminName() string {
	if m != nil {
		return m.AdminName
	}
	return ""
}

func (m *PreSaleAdminReg) GetAdminId() int64 {
	if m != nil {
		return m.AdminId
	}
	return 0
}

// id存本地数据库    用户信息上链
type PreSaleUserReg struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Email    string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	PhoneNum string `protobuf:"bytes,3,opt,name=phoneNum" json:"phoneNum,omitempty"`
	Uid      int64  `protobuf:"varint,4,opt,name=uid" json:"uid,omitempty"`
	// string btyAddress   =5;//bty地址
	// string ethAddress   =6;//eth地址
	Currency []*CoinInfo `protobuf:"bytes,5,rep,name=currency" json:"currency,omitempty"`
	Uuid     string      `protobuf:"bytes,7,opt,name=uuid" json:"uuid,omitempty"`
}

func (m *PreSaleUserReg) Reset()                    { *m = PreSaleUserReg{} }
func (m *PreSaleUserReg) String() string            { return proto.CompactTextString(m) }
func (*PreSaleUserReg) ProtoMessage()               {}
func (*PreSaleUserReg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *PreSaleUserReg) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PreSaleUserReg) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *PreSaleUserReg) GetPhoneNum() string {
	if m != nil {
		return m.PhoneNum
	}
	return ""
}

func (m *PreSaleUserReg) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *PreSaleUserReg) GetCurrency() []*CoinInfo {
	if m != nil {
		return m.Currency
	}
	return nil
}

func (m *PreSaleUserReg) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

// 放入本地数据库 充值操作上链 数量不上链  确认pubkey是否与market一致
type PreSaleMarketRec struct {
	MarketId  int64  `protobuf:"varint,1,opt,name=marketId" json:"marketId,omitempty"`
	Amount    int64  `protobuf:"varint,2,opt,name=amount" json:"amount,omitempty"`
	Currency  string `protobuf:"bytes,3,opt,name=currency" json:"currency,omitempty"`
	IsToken   bool   `protobuf:"varint,4,opt,name=isToken" json:"isToken,omitempty"`
	Time      int64  `protobuf:"varint,5,opt,name=time" json:"time,omitempty"`
	ToAddress string `protobuf:"bytes,6,opt,name=toAddress" json:"toAddress,omitempty"`
}

func (m *PreSaleMarketRec) Reset()                    { *m = PreSaleMarketRec{} }
func (m *PreSaleMarketRec) String() string            { return proto.CompactTextString(m) }
func (*PreSaleMarketRec) ProtoMessage()               {}
func (*PreSaleMarketRec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *PreSaleMarketRec) GetMarketId() int64 {
	if m != nil {
		return m.MarketId
	}
	return 0
}

func (m *PreSaleMarketRec) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *PreSaleMarketRec) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *PreSaleMarketRec) GetIsToken() bool {
	if m != nil {
		return m.IsToken
	}
	return false
}

func (m *PreSaleMarketRec) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *PreSaleMarketRec) GetToAddress() string {
	if m != nil {
		return m.ToAddress
	}
	return ""
}

type PreSaleUserRec struct {
	Uid int64 `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	// int64  marketId     =2;//需要充值的商家代币 直接冲eth bty 可为空
	Amount   int64  `protobuf:"varint,2,opt,name=amount" json:"amount,omitempty"`
	Time     int64  `protobuf:"varint,3,opt,name=time" json:"time,omitempty"`
	Currency string `protobuf:"bytes,4,opt,name=currency" json:"currency,omitempty"`
	// bool   isToken      =6;   //是否为币种所对应的代币
	ToAddress string `protobuf:"bytes,5,opt,name=toAddress" json:"toAddress,omitempty"`
}

func (m *PreSaleUserRec) Reset()                    { *m = PreSaleUserRec{} }
func (m *PreSaleUserRec) String() string            { return proto.CompactTextString(m) }
func (*PreSaleUserRec) ProtoMessage()               {}
func (*PreSaleUserRec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *PreSaleUserRec) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *PreSaleUserRec) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *PreSaleUserRec) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *PreSaleUserRec) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *PreSaleUserRec) GetToAddress() string {
	if m != nil {
		return m.ToAddress
	}
	return ""
}

// 上链：在这里需要添加货单状态为未上线 货单信息上链
type PreSaleAddPdInfo struct {
	PdName     string `protobuf:"bytes,1,opt,name=pdName" json:"pdName,omitempty"`
	PdId       int64  `protobuf:"varint,2,opt,name=pdId" json:"pdId,omitempty"`
	Price      int64  `protobuf:"varint,3,opt,name=price" json:"price,omitempty"`
	Deposit    int64  `protobuf:"varint,4,opt,name=deposit" json:"deposit,omitempty"`
	PsStart    int64  `protobuf:"varint,5,opt,name=psStart" json:"psStart,omitempty"`
	PsEnd      int64  `protobuf:"varint,6,opt,name=psEnd" json:"psEnd,omitempty"`
	PuStart    int64  `protobuf:"varint,7,opt,name=puStart" json:"puStart,omitempty"`
	PuEnd      int64  `protobuf:"varint,8,opt,name=puEnd" json:"puEnd,omitempty"`
	MarketId   int64  `protobuf:"varint,9,opt,name=marketId" json:"marketId,omitempty"`
	MarketName string `protobuf:"bytes,10,opt,name=marketName" json:"marketName,omitempty"`
	AdminId    int64  `protobuf:"varint,11,opt,name=adminId" json:"adminId,omitempty"`
	Status     string `protobuf:"bytes,12,opt,name=status" json:"status,omitempty"`
}

func (m *PreSaleAddPdInfo) Reset()                    { *m = PreSaleAddPdInfo{} }
func (m *PreSaleAddPdInfo) String() string            { return proto.CompactTextString(m) }
func (*PreSaleAddPdInfo) ProtoMessage()               {}
func (*PreSaleAddPdInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *PreSaleAddPdInfo) GetPdName() string {
	if m != nil {
		return m.PdName
	}
	return ""
}

func (m *PreSaleAddPdInfo) GetPdId() int64 {
	if m != nil {
		return m.PdId
	}
	return 0
}

func (m *PreSaleAddPdInfo) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *PreSaleAddPdInfo) GetDeposit() int64 {
	if m != nil {
		return m.Deposit
	}
	return 0
}

func (m *PreSaleAddPdInfo) GetPsStart() int64 {
	if m != nil {
		return m.PsStart
	}
	return 0
}

func (m *PreSaleAddPdInfo) GetPsEnd() int64 {
	if m != nil {
		return m.PsEnd
	}
	return 0
}

func (m *PreSaleAddPdInfo) GetPuStart() int64 {
	if m != nil {
		return m.PuStart
	}
	return 0
}

func (m *PreSaleAddPdInfo) GetPuEnd() int64 {
	if m != nil {
		return m.PuEnd
	}
	return 0
}

func (m *PreSaleAddPdInfo) GetMarketId() int64 {
	if m != nil {
		return m.MarketId
	}
	return 0
}

func (m *PreSaleAddPdInfo) GetMarketName() string {
	if m != nil {
		return m.MarketName
	}
	return ""
}

func (m *PreSaleAddPdInfo) GetAdminId() int64 {
	if m != nil {
		return m.AdminId
	}
	return 0
}

func (m *PreSaleAddPdInfo) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

// 上链 存本地数据库  如果下线了就不能买了
type PreSaleOnOffPd struct {
	PdId    int64 `protobuf:"varint,1,opt,name=pdId" json:"pdId,omitempty"`
	Status  bool  `protobuf:"varint,3,opt,name=status" json:"status,omitempty"`
	AdminId int64 `protobuf:"varint,4,opt,name=adminId" json:"adminId,omitempty"`
	Time    int64 `protobuf:"varint,5,opt,name=time" json:"time,omitempty"`
}

func (m *PreSaleOnOffPd) Reset()                    { *m = PreSaleOnOffPd{} }
func (m *PreSaleOnOffPd) String() string            { return proto.CompactTextString(m) }
func (*PreSaleOnOffPd) ProtoMessage()               {}
func (*PreSaleOnOffPd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *PreSaleOnOffPd) GetPdId() int64 {
	if m != nil {
		return m.PdId
	}
	return 0
}

func (m *PreSaleOnOffPd) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *PreSaleOnOffPd) GetAdminId() int64 {
	if m != nil {
		return m.AdminId
	}
	return 0
}

func (m *PreSaleOnOffPd) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

// 判断产品是否下架  这里要做很多资产判断
type PreSaleUserPay struct {
	OrderId int64 `protobuf:"varint,1,opt,name=orderId" json:"orderId,omitempty"`
	PdId    int64 `protobuf:"varint,2,opt,name=pdId" json:"pdId,omitempty"`
	Uid     int64 `protobuf:"varint,3,opt,name=uid" json:"uid,omitempty"`
	// int64  currencyId       =4; //代币id  1："bty"  2:"eth"
	CurrencyName   string         `protobuf:"bytes,4,opt,name=currencyName" json:"currencyName,omitempty"`
	TokenAmount    int64          `protobuf:"varint,5,opt,name=tokenAmount" json:"tokenAmount,omitempty"`
	CurrencyAmount int64          `protobuf:"varint,6,opt,name=currencyAmount" json:"currencyAmount,omitempty"`
	PayId          PreSalePayType `protobuf:"varint,7,opt,name=payId,enum=types.PreSalePayType" json:"payId,omitempty"`
	Time           int64          `protobuf:"varint,11,opt,name=Time" json:"Time,omitempty"`
	MarketId       int64          `protobuf:"varint,12,opt,name=marketId" json:"marketId,omitempty"`
	AddressId      int64          `protobuf:"varint,13,opt,name=addressId" json:"addressId,omitempty"`
	Amount         int64          `protobuf:"varint,14,opt,name=amount" json:"amount,omitempty"`
}

func (m *PreSaleUserPay) Reset()                    { *m = PreSaleUserPay{} }
func (m *PreSaleUserPay) String() string            { return proto.CompactTextString(m) }
func (*PreSaleUserPay) ProtoMessage()               {}
func (*PreSaleUserPay) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *PreSaleUserPay) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *PreSaleUserPay) GetPdId() int64 {
	if m != nil {
		return m.PdId
	}
	return 0
}

func (m *PreSaleUserPay) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *PreSaleUserPay) GetCurrencyName() string {
	if m != nil {
		return m.CurrencyName
	}
	return ""
}

func (m *PreSaleUserPay) GetTokenAmount() int64 {
	if m != nil {
		return m.TokenAmount
	}
	return 0
}

func (m *PreSaleUserPay) GetCurrencyAmount() int64 {
	if m != nil {
		return m.CurrencyAmount
	}
	return 0
}

func (m *PreSaleUserPay) GetPayId() PreSalePayType {
	if m != nil {
		return m.PayId
	}
	return PreSalePayType_PreSaleErr
}

func (m *PreSaleUserPay) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *PreSaleUserPay) GetMarketId() int64 {
	if m != nil {
		return m.MarketId
	}
	return 0
}

func (m *PreSaleUserPay) GetAddressId() int64 {
	if m != nil {
		return m.AddressId
	}
	return 0
}

func (m *PreSaleUserPay) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type PreSaleAddAddress struct {
	UserName  string `protobuf:"bytes,1,opt,name=userName" json:"userName,omitempty"`
	PhoneNum  string `protobuf:"bytes,2,opt,name=phoneNum" json:"phoneNum,omitempty"`
	Address   string `protobuf:"bytes,3,opt,name=address" json:"address,omitempty"`
	Uid       int64  `protobuf:"varint,4,opt,name=uid" json:"uid,omitempty"`
	AddressId int64  `protobuf:"varint,5,opt,name=addressId" json:"addressId,omitempty"`
}

func (m *PreSaleAddAddress) Reset()                    { *m = PreSaleAddAddress{} }
func (m *PreSaleAddAddress) String() string            { return proto.CompactTextString(m) }
func (*PreSaleAddAddress) ProtoMessage()               {}
func (*PreSaleAddAddress) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *PreSaleAddAddress) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *PreSaleAddAddress) GetPhoneNum() string {
	if m != nil {
		return m.PhoneNum
	}
	return ""
}

func (m *PreSaleAddAddress) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *PreSaleAddAddress) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *PreSaleAddAddress) GetAddressId() int64 {
	if m != nil {
		return m.AddressId
	}
	return 0
}

type PreSaleOrderTrans struct {
	OrderId int64  `protobuf:"varint,1,opt,name=orderId" json:"orderId,omitempty"`
	ToUUid  string `protobuf:"bytes,2,opt,name=toUUid" json:"toUUid,omitempty"`
	// string fromUUid =3;//用户的UUid
	Uid        int64 `protobuf:"varint,4,opt,name=uid" json:"uid,omitempty"`
	ToUid      int64 `protobuf:"varint,5,opt,name=toUid" json:"toUid,omitempty"`
	Time       int64 `protobuf:"varint,6,opt,name=time" json:"time,omitempty"`
	NewOrderId int64 `protobuf:"varint,7,opt,name=newOrderId" json:"newOrderId,omitempty"`
}

func (m *PreSaleOrderTrans) Reset()                    { *m = PreSaleOrderTrans{} }
func (m *PreSaleOrderTrans) String() string            { return proto.CompactTextString(m) }
func (*PreSaleOrderTrans) ProtoMessage()               {}
func (*PreSaleOrderTrans) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *PreSaleOrderTrans) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *PreSaleOrderTrans) GetToUUid() string {
	if m != nil {
		return m.ToUUid
	}
	return ""
}

func (m *PreSaleOrderTrans) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *PreSaleOrderTrans) GetToUid() int64 {
	if m != nil {
		return m.ToUid
	}
	return 0
}

func (m *PreSaleOrderTrans) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *PreSaleOrderTrans) GetNewOrderId() int64 {
	if m != nil {
		return m.NewOrderId
	}
	return 0
}

type PreSaleMarketShip struct {
	OrderId int64  `protobuf:"varint,1,opt,name=orderId" json:"orderId,omitempty"`
	AdminId int64  `protobuf:"varint,2,opt,name=adminId" json:"adminId,omitempty"`
	Time    int64  `protobuf:"varint,3,opt,name=time" json:"time,omitempty"`
	Express string `protobuf:"bytes,4,opt,name=express" json:"express,omitempty"`
	OrdNum  string `protobuf:"bytes,5,opt,name=ordNum" json:"ordNum,omitempty"`
}

func (m *PreSaleMarketShip) Reset()                    { *m = PreSaleMarketShip{} }
func (m *PreSaleMarketShip) String() string            { return proto.CompactTextString(m) }
func (*PreSaleMarketShip) ProtoMessage()               {}
func (*PreSaleMarketShip) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *PreSaleMarketShip) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *PreSaleMarketShip) GetAdminId() int64 {
	if m != nil {
		return m.AdminId
	}
	return 0
}

func (m *PreSaleMarketShip) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *PreSaleMarketShip) GetExpress() string {
	if m != nil {
		return m.Express
	}
	return ""
}

func (m *PreSaleMarketShip) GetOrdNum() string {
	if m != nil {
		return m.OrdNum
	}
	return ""
}

type PreSaleLogistics struct {
	OrderId  int64  `protobuf:"varint,1,opt,name=orderId" json:"orderId,omitempty"`
	Express  string `protobuf:"bytes,2,opt,name=express" json:"express,omitempty"`
	OrdNum   string `protobuf:"bytes,3,opt,name=ordNum" json:"ordNum,omitempty"`
	Time     int64  `protobuf:"varint,4,opt,name=time" json:"time,omitempty"`
	Marketid int64  `protobuf:"varint,5,opt,name=marketid" json:"marketid,omitempty"`
}

func (m *PreSaleLogistics) Reset()                    { *m = PreSaleLogistics{} }
func (m *PreSaleLogistics) String() string            { return proto.CompactTextString(m) }
func (*PreSaleLogistics) ProtoMessage()               {}
func (*PreSaleLogistics) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *PreSaleLogistics) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *PreSaleLogistics) GetExpress() string {
	if m != nil {
		return m.Express
	}
	return ""
}

func (m *PreSaleLogistics) GetOrdNum() string {
	if m != nil {
		return m.OrdNum
	}
	return ""
}

func (m *PreSaleLogistics) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *PreSaleLogistics) GetMarketid() int64 {
	if m != nil {
		return m.Marketid
	}
	return 0
}

type PreSaleUserRecipt struct {
	OrderId int64 `protobuf:"varint,1,opt,name=orderId" json:"orderId,omitempty"`
	Time    int64 `protobuf:"varint,2,opt,name=time" json:"time,omitempty"`
	Uid     int64 `protobuf:"varint,3,opt,name=uid" json:"uid,omitempty"`
}

func (m *PreSaleUserRecipt) Reset()                    { *m = PreSaleUserRecipt{} }
func (m *PreSaleUserRecipt) String() string            { return proto.CompactTextString(m) }
func (*PreSaleUserRecipt) ProtoMessage()               {}
func (*PreSaleUserRecipt) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *PreSaleUserRecipt) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *PreSaleUserRecipt) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *PreSaleUserRecipt) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type PreSaleOverDue struct {
	OrderId []int64 `protobuf:"varint,1,rep,packed,name=orderId" json:"orderId,omitempty"`
	Time    int64   `protobuf:"varint,3,opt,name=time" json:"time,omitempty"`
}

func (m *PreSaleOverDue) Reset()                    { *m = PreSaleOverDue{} }
func (m *PreSaleOverDue) String() string            { return proto.CompactTextString(m) }
func (*PreSaleOverDue) ProtoMessage()               {}
func (*PreSaleOverDue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *PreSaleOverDue) GetOrderId() []int64 {
	if m != nil {
		return m.OrderId
	}
	return nil
}

func (m *PreSaleOverDue) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type PreSaleWithDraw struct {
	Id        int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Amount    int64  `protobuf:"varint,2,opt,name=amount" json:"amount,omitempty"`
	ToAddress string `protobuf:"bytes,4,opt,name=toAddress" json:"toAddress,omitempty"`
	IsMarket  bool   `protobuf:"varint,5,opt,name=isMarket" json:"isMarket,omitempty"`
	Currency  string `protobuf:"bytes,6,opt,name=currency" json:"currency,omitempty"`
	IsToken   bool   `protobuf:"varint,7,opt,name=isToken" json:"isToken,omitempty"`
	Time      int64  `protobuf:"varint,8,opt,name=time" json:"time,omitempty"`
	MinerFee  string `protobuf:"bytes,9,opt,name=minerFee" json:"minerFee,omitempty"`
}

func (m *PreSaleWithDraw) Reset()                    { *m = PreSaleWithDraw{} }
func (m *PreSaleWithDraw) String() string            { return proto.CompactTextString(m) }
func (*PreSaleWithDraw) ProtoMessage()               {}
func (*PreSaleWithDraw) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *PreSaleWithDraw) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PreSaleWithDraw) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *PreSaleWithDraw) GetToAddress() string {
	if m != nil {
		return m.ToAddress
	}
	return ""
}

func (m *PreSaleWithDraw) GetIsMarket() bool {
	if m != nil {
		return m.IsMarket
	}
	return false
}

func (m *PreSaleWithDraw) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *PreSaleWithDraw) GetIsToken() bool {
	if m != nil {
		return m.IsToken
	}
	return false
}

func (m *PreSaleWithDraw) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *PreSaleWithDraw) GetMinerFee() string {
	if m != nil {
		return m.MinerFee
	}
	return ""
}

type PreSaleChangePd struct {
	PdName     string `protobuf:"bytes,1,opt,name=pdName" json:"pdName,omitempty"`
	PdId       int64  `protobuf:"varint,2,opt,name=pdId" json:"pdId,omitempty"`
	Price      int64  `protobuf:"varint,3,opt,name=price" json:"price,omitempty"`
	Deposit    int64  `protobuf:"varint,4,opt,name=deposit" json:"deposit,omitempty"`
	PsStart    int64  `protobuf:"varint,5,opt,name=psStart" json:"psStart,omitempty"`
	PsEnd      int64  `protobuf:"varint,6,opt,name=psEnd" json:"psEnd,omitempty"`
	PuStart    int64  `protobuf:"varint,7,opt,name=puStart" json:"puStart,omitempty"`
	PuEnd      int64  `protobuf:"varint,8,opt,name=puEnd" json:"puEnd,omitempty"`
	MarketId   int64  `protobuf:"varint,9,opt,name=marketId" json:"marketId,omitempty"`
	MarketName string `protobuf:"bytes,10,opt,name=marketName" json:"marketName,omitempty"`
	AdminId    int64  `protobuf:"varint,11,opt,name=adminId" json:"adminId,omitempty"`
	Status     string `protobuf:"bytes,12,opt,name=status" json:"status,omitempty"`
	IsDelete   bool   `protobuf:"varint,13,opt,name=isDelete" json:"isDelete,omitempty"`
}

func (m *PreSaleChangePd) Reset()                    { *m = PreSaleChangePd{} }
func (m *PreSaleChangePd) String() string            { return proto.CompactTextString(m) }
func (*PreSaleChangePd) ProtoMessage()               {}
func (*PreSaleChangePd) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *PreSaleChangePd) GetPdName() string {
	if m != nil {
		return m.PdName
	}
	return ""
}

func (m *PreSaleChangePd) GetPdId() int64 {
	if m != nil {
		return m.PdId
	}
	return 0
}

func (m *PreSaleChangePd) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *PreSaleChangePd) GetDeposit() int64 {
	if m != nil {
		return m.Deposit
	}
	return 0
}

func (m *PreSaleChangePd) GetPsStart() int64 {
	if m != nil {
		return m.PsStart
	}
	return 0
}

func (m *PreSaleChangePd) GetPsEnd() int64 {
	if m != nil {
		return m.PsEnd
	}
	return 0
}

func (m *PreSaleChangePd) GetPuStart() int64 {
	if m != nil {
		return m.PuStart
	}
	return 0
}

func (m *PreSaleChangePd) GetPuEnd() int64 {
	if m != nil {
		return m.PuEnd
	}
	return 0
}

func (m *PreSaleChangePd) GetMarketId() int64 {
	if m != nil {
		return m.MarketId
	}
	return 0
}

func (m *PreSaleChangePd) GetMarketName() string {
	if m != nil {
		return m.MarketName
	}
	return ""
}

func (m *PreSaleChangePd) GetAdminId() int64 {
	if m != nil {
		return m.AdminId
	}
	return 0
}

func (m *PreSaleChangePd) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *PreSaleChangePd) GetIsDelete() bool {
	if m != nil {
		return m.IsDelete
	}
	return false
}

type PreSaleUserTokenWithDraw struct {
	Uid      int64  `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	MarketId int64  `protobuf:"varint,2,opt,name=marketId" json:"marketId,omitempty"`
	Amount   int64  `protobuf:"varint,3,opt,name=amount" json:"amount,omitempty"`
	Address  string `protobuf:"bytes,4,opt,name=address" json:"address,omitempty"`
}

func (m *PreSaleUserTokenWithDraw) Reset()                    { *m = PreSaleUserTokenWithDraw{} }
func (m *PreSaleUserTokenWithDraw) String() string            { return proto.CompactTextString(m) }
func (*PreSaleUserTokenWithDraw) ProtoMessage()               {}
func (*PreSaleUserTokenWithDraw) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *PreSaleUserTokenWithDraw) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *PreSaleUserTokenWithDraw) GetMarketId() int64 {
	if m != nil {
		return m.MarketId
	}
	return 0
}

func (m *PreSaleUserTokenWithDraw) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *PreSaleUserTokenWithDraw) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type PreSaleUserShip struct {
	Uid       int64 `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	Oid       int64 `protobuf:"varint,2,opt,name=oid" json:"oid,omitempty"`
	AddressId int64 `protobuf:"varint,3,opt,name=addressId" json:"addressId,omitempty"`
}

func (m *PreSaleUserShip) Reset()                    { *m = PreSaleUserShip{} }
func (m *PreSaleUserShip) String() string            { return proto.CompactTextString(m) }
func (*PreSaleUserShip) ProtoMessage()               {}
func (*PreSaleUserShip) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *PreSaleUserShip) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *PreSaleUserShip) GetOid() int64 {
	if m != nil {
		return m.Oid
	}
	return 0
}

func (m *PreSaleUserShip) GetAddressId() int64 {
	if m != nil {
		return m.AddressId
	}
	return 0
}

// log
type MarketInfoPreSale struct {
	MarketInfo *PreSaleMarketInfo `protobuf:"bytes,1,opt,name=marketInfo" json:"marketInfo,omitempty"`
}

func (m *MarketInfoPreSale) Reset()                    { *m = MarketInfoPreSale{} }
func (m *MarketInfoPreSale) String() string            { return proto.CompactTextString(m) }
func (*MarketInfoPreSale) ProtoMessage()               {}
func (*MarketInfoPreSale) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *MarketInfoPreSale) GetMarketInfo() *PreSaleMarketInfo {
	if m != nil {
		return m.MarketInfo
	}
	return nil
}

type AdminInfoPreSale struct {
	AdminInfo *PreSaleAdminInfo `protobuf:"bytes,1,opt,name=adminInfo" json:"adminInfo,omitempty"`
}

func (m *AdminInfoPreSale) Reset()                    { *m = AdminInfoPreSale{} }
func (m *AdminInfoPreSale) String() string            { return proto.CompactTextString(m) }
func (*AdminInfoPreSale) ProtoMessage()               {}
func (*AdminInfoPreSale) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

func (m *AdminInfoPreSale) GetAdminInfo() *PreSaleAdminInfo {
	if m != nil {
		return m.AdminInfo
	}
	return nil
}

type UserInfoSale struct {
	UserInfo *PreSaleUserInfo `protobuf:"bytes,1,opt,name=userInfo" json:"userInfo,omitempty"`
}

func (m *UserInfoSale) Reset()                    { *m = UserInfoSale{} }
func (m *UserInfoSale) String() string            { return proto.CompactTextString(m) }
func (*UserInfoSale) ProtoMessage()               {}
func (*UserInfoSale) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

func (m *UserInfoSale) GetUserInfo() *PreSaleUserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

type PdInfoPresale struct {
	PdInfo *PresalePdInfo `protobuf:"bytes,1,opt,name=pdInfo" json:"pdInfo,omitempty"`
}

func (m *PdInfoPresale) Reset()                    { *m = PdInfoPresale{} }
func (m *PdInfoPresale) String() string            { return proto.CompactTextString(m) }
func (*PdInfoPresale) ProtoMessage()               {}
func (*PdInfoPresale) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

func (m *PdInfoPresale) GetPdInfo() *PresalePdInfo {
	if m != nil {
		return m.PdInfo
	}
	return nil
}

type OrderInfoPreSale struct {
	OrderInfo *PreSaleOrderInfo `protobuf:"bytes,1,opt,name=orderInfo" json:"orderInfo,omitempty"`
}

func (m *OrderInfoPreSale) Reset()                    { *m = OrderInfoPreSale{} }
func (m *OrderInfoPreSale) String() string            { return proto.CompactTextString(m) }
func (*OrderInfoPreSale) ProtoMessage()               {}
func (*OrderInfoPreSale) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

func (m *OrderInfoPreSale) GetOrderInfo() *PreSaleOrderInfo {
	if m != nil {
		return m.OrderInfo
	}
	return nil
}

type OverDuePreSale struct {
	Order []int64 `protobuf:"varint,1,rep,packed,name=order" json:"order,omitempty"`
}

func (m *OverDuePreSale) Reset()                    { *m = OverDuePreSale{} }
func (m *OverDuePreSale) String() string            { return proto.CompactTextString(m) }
func (*OverDuePreSale) ProtoMessage()               {}
func (*OverDuePreSale) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{36} }

func (m *OverDuePreSale) GetOrder() []int64 {
	if m != nil {
		return m.Order
	}
	return nil
}

type WithDrawPS struct {
	WithDrawInfo *PreSaleWithDraw `protobuf:"bytes,1,opt,name=withDrawInfo" json:"withDrawInfo,omitempty"`
}

func (m *WithDrawPS) Reset()                    { *m = WithDrawPS{} }
func (m *WithDrawPS) String() string            { return proto.CompactTextString(m) }
func (*WithDrawPS) ProtoMessage()               {}
func (*WithDrawPS) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{37} }

func (m *WithDrawPS) GetWithDrawInfo() *PreSaleWithDraw {
	if m != nil {
		return m.WithDrawInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*PreSaleMarketInfo)(nil), "types.PreSaleMarketInfo")
	proto.RegisterType((*PreSaleToken)(nil), "types.PreSaleToken")
	proto.RegisterType((*PreSaleAdminInfo)(nil), "types.PreSaleAdminInfo")
	proto.RegisterType((*PreSaleCurrency)(nil), "types.PreSaleCurrency")
	proto.RegisterType((*PreSaleUserInfo)(nil), "types.PreSaleUserInfo")
	proto.RegisterType((*PreSaleAddress)(nil), "types.PreSaleAddress")
	proto.RegisterType((*PreSaleOpreation)(nil), "types.PreSaleOpreation")
	proto.RegisterType((*PresalePdInfo)(nil), "types.PresalePdInfo")
	proto.RegisterType((*PreSaleOrderInfo)(nil), "types.PreSaleOrderInfo")
	proto.RegisterType((*PreSaleAmount)(nil), "types.PreSaleAmount")
	proto.RegisterType((*WithDrawPreSale)(nil), "types.WithDrawPreSale")
	proto.RegisterType((*PreSale)(nil), "types.PreSale")
	proto.RegisterType((*PreSaleMarketReg)(nil), "types.PreSaleMarketReg")
	proto.RegisterType((*CoinInfo)(nil), "types.CoinInfo")
	proto.RegisterType((*PreSaleAdminReg)(nil), "types.PreSaleAdminReg")
	proto.RegisterType((*PreSaleUserReg)(nil), "types.PreSaleUserReg")
	proto.RegisterType((*PreSaleMarketRec)(nil), "types.PreSaleMarketRec")
	proto.RegisterType((*PreSaleUserRec)(nil), "types.PreSaleUserRec")
	proto.RegisterType((*PreSaleAddPdInfo)(nil), "types.PreSaleAddPdInfo")
	proto.RegisterType((*PreSaleOnOffPd)(nil), "types.PreSaleOnOffPd")
	proto.RegisterType((*PreSaleUserPay)(nil), "types.PreSaleUserPay")
	proto.RegisterType((*PreSaleAddAddress)(nil), "types.PreSaleAddAddress")
	proto.RegisterType((*PreSaleOrderTrans)(nil), "types.PreSaleOrderTrans")
	proto.RegisterType((*PreSaleMarketShip)(nil), "types.PreSaleMarketShip")
	proto.RegisterType((*PreSaleLogistics)(nil), "types.PreSaleLogistics")
	proto.RegisterType((*PreSaleUserRecipt)(nil), "types.PreSaleUserRecipt")
	proto.RegisterType((*PreSaleOverDue)(nil), "types.PreSaleOverDue")
	proto.RegisterType((*PreSaleWithDraw)(nil), "types.PreSaleWithDraw")
	proto.RegisterType((*PreSaleChangePd)(nil), "types.PreSaleChangePd")
	proto.RegisterType((*PreSaleUserTokenWithDraw)(nil), "types.PreSaleUserTokenWithDraw")
	proto.RegisterType((*PreSaleUserShip)(nil), "types.PreSaleUserShip")
	proto.RegisterType((*MarketInfoPreSale)(nil), "types.MarketInfoPreSale")
	proto.RegisterType((*AdminInfoPreSale)(nil), "types.AdminInfoPreSale")
	proto.RegisterType((*UserInfoSale)(nil), "types.UserInfoSale")
	proto.RegisterType((*PdInfoPresale)(nil), "types.PdInfoPresale")
	proto.RegisterType((*OrderInfoPreSale)(nil), "types.OrderInfoPreSale")
	proto.RegisterType((*OverDuePreSale)(nil), "types.OverDuePreSale")
	proto.RegisterType((*WithDrawPS)(nil), "types.WithDrawPS")
	proto.RegisterEnum("types.PreSalePayType", PreSalePayType_name, PreSalePayType_value)
}

func init() { proto.RegisterFile("preSale.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1898 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x59, 0xcd, 0x6f, 0xe4, 0x48,
	0x15, 0x8f, 0xdb, 0xfd, 0xe1, 0x7e, 0x49, 0x3a, 0x1d, 0x6f, 0xb6, 0xc7, 0x5a, 0xa1, 0xa5, 0xe5,
	0xc3, 0x2a, 0xb0, 0x28, 0x88, 0xb0, 0x88, 0xd5, 0x4a, 0x20, 0x65, 0x76, 0x76, 0x95, 0x88, 0xcd,
	0xa6, 0xe5, 0x4e, 0xc4, 0xd9, 0xb1, 0x2b, 0x13, 0x93, 0x8e, 0x6d, 0xd9, 0xee, 0x1d, 0x7a, 0x4e,
	0x70, 0xe3, 0x02, 0x37, 0x24, 0xc4, 0x0d, 0x89, 0x0b, 0x17, 0xae, 0x08, 0x09, 0x24, 0xfe, 0x85,
	0x39, 0x21, 0xfe, 0x1b, 0x54, 0xaf, 0xbe, 0xfd, 0x11, 0x26, 0xa0, 0x11, 0x5a, 0x69, 0x6e, 0x7e,
	0x55, 0xaf, 0xea, 0xbd, 0x7a, 0x1f, 0xbf, 0x7a, 0xaf, 0x0c, 0xbb, 0x79, 0x41, 0x96, 0xe1, 0x8a,
	0x1c, 0xe5, 0x45, 0x56, 0x65, 0xee, 0xa0, 0xda, 0xe4, 0xa4, 0xf4, 0xff, 0xd2, 0x83, 0xfd, 0x05,
	0x9b, 0x38, 0x0f, 0x8b, 0x3b, 0x52, 0x9d, 0xa5, 0x37, 0x99, 0xfb, 0x3e, 0xc0, 0x3d, 0x52, 0x5f,
	0x86, 0xf7, 0xc4, 0xb3, 0xe6, 0xd6, 0xe1, 0x38, 0xd0, 0x46, 0xdc, 0xf7, 0xc0, 0x61, 0xd4, 0x59,
	0xec, 0xf5, 0xe6, 0xd6, 0xa1, 0x1d, 0x48, 0xda, 0xf5, 0x60, 0x14, 0x65, 0x69, 0x15, 0x46, 0x95,
	0x67, 0xe3, 0x42, 0x41, 0xd2, 0x55, 0xf9, 0x6d, 0x96, 0x92, 0x2f, 0xd7, 0xf7, 0x5e, 0x1f, 0xa7,
	0x24, 0xed, 0x1e, 0x83, 0x13, 0xad, 0x8b, 0x82, 0xa4, 0xd1, 0xc6, 0x1b, 0xcc, 0xed, 0xc3, 0xed,
	0xe3, 0xd9, 0x11, 0x6a, 0x78, 0xc4, 0xb5, 0xfb, 0x94, 0xcf, 0x06, 0x92, 0xcf, 0xfd, 0x1e, 0x8c,
	0xb2, 0x9c, 0x14, 0x61, 0x45, 0xbc, 0xe1, 0xdc, 0x3a, 0xdc, 0x3e, 0x7e, 0x62, 0x2e, 0xb9, 0xc8,
	0x0b, 0x12, 0x56, 0x49, 0x96, 0x06, 0x82, 0xcf, 0xfd, 0x16, 0x0c, 0xaa, 0xec, 0x8e, 0xa4, 0xde,
	0x08, 0x17, 0xbc, 0x63, 0x2e, 0xb8, 0xa4, 0x53, 0x01, 0xe3, 0xa0, 0x36, 0x48, 0x4a, 0x1c, 0x59,
	0xae, 0x73, 0xcf, 0x99, 0x5b, 0x87, 0x4e, 0xa0, 0x8d, 0xf8, 0x37, 0xb0, 0xa3, 0x2f, 0x33, 0x6c,
	0x62, 0x35, 0x6d, 0xb2, 0x2e, 0xc9, 0xc9, 0xf5, 0x8a, 0x70, 0x73, 0x09, 0xd2, 0x9d, 0xc3, 0x36,
	0x8a, 0xfb, 0xbc, 0xc8, 0x5e, 0x92, 0x14, 0x2d, 0x66, 0x07, 0xfa, 0x90, 0x7f, 0x0d, 0x53, 0x2e,
	0xe7, 0x24, 0xbe, 0x4f, 0x52, 0xf4, 0xcf, 0x37, 0x60, 0x1c, 0x52, 0x42, 0x73, 0x8f, 0x1a, 0xa0,
	0xd2, 0x90, 0x90, 0xce, 0x11, 0xa4, 0x3b, 0x83, 0x61, 0x59, 0x85, 0xd5, 0xba, 0xe4, 0xae, 0xe1,
	0x94, 0xff, 0x4b, 0x0b, 0xf6, 0x6a, 0x76, 0x76, 0x7d, 0xd8, 0x11, 0x96, 0xd6, 0xc4, 0x18, 0x63,
	0x4c, 0x52, 0x5c, 0x90, 0xb2, 0x44, 0x49, 0xe3, 0x40, 0x90, 0xfa, 0x89, 0x6d, 0xf3, 0xc4, 0x33,
	0x18, 0xde, 0xb0, 0xc3, 0xf6, 0x71, 0x82, 0x53, 0xfe, 0x3f, 0x7a, 0x52, 0x87, 0xab, 0x92, 0x14,
	0x78, 0x4e, 0x17, 0xfa, 0xa9, 0x92, 0x8d, 0xdf, 0xee, 0x01, 0x0c, 0xc8, 0x7d, 0x98, 0xac, 0xb8,
	0x44, 0x46, 0x18, 0xb1, 0x65, 0xd7, 0x62, 0x6b, 0x0a, 0xf6, 0x3a, 0x89, 0xb9, 0x38, 0xfa, 0x69,
	0x44, 0xdb, 0xf0, 0xf1, 0xd1, 0x36, 0x7a, 0x6c, 0xb4, 0x39, 0x28, 0xe3, 0xa1, 0x68, 0x73, 0xa1,
	0xbf, 0xa6, 0x4a, 0x8e, 0xd9, 0x49, 0xe9, 0xb7, 0xfb, 0x5d, 0x65, 0x5d, 0xc0, 0x0d, 0xde, 0x35,
	0x37, 0x38, 0x61, 0x93, 0xd2, 0xe8, 0xfe, 0x2f, 0x2c, 0x98, 0x98, 0x73, 0xd4, 0x2e, 0xeb, 0x92,
	0x14, 0x9a, 0x07, 0x25, 0x6d, 0xd8, 0xac, 0x57, 0xb3, 0x99, 0xe6, 0x59, 0xdb, 0xf4, 0x2c, 0xc6,
	0x1e, 0x7e, 0x9e, 0x09, 0x9b, 0xaa, 0x01, 0xff, 0xf7, 0x96, 0x0c, 0x57, 0x69, 0x10, 0x7a, 0xb8,
	0x2a, 0xe1, 0x0a, 0xd8, 0x01, 0x7e, 0xd3, 0xc0, 0xbf, 0x29, 0xb2, 0xfb, 0x13, 0x23, 0x7c, 0xf4,
	0x21, 0x2a, 0xa8, 0xca, 0x4e, 0x0c, 0x25, 0xd4, 0x80, 0x16, 0xca, 0x7d, 0x3d, 0x94, 0x31, 0x0d,
	0x93, 0x94, 0x14, 0x9f, 0x13, 0xe2, 0x0d, 0xd8, 0xa1, 0x04, 0xed, 0xff, 0xb5, 0x07, 0xbb, 0x8b,
	0x82, 0x94, 0xe1, 0x8a, 0x2c, 0x62, 0x0c, 0xb0, 0x19, 0x0c, 0xf3, 0x58, 0x33, 0x0e, 0xa7, 0xa8,
	0xc6, 0x79, 0x2c, 0xf3, 0x07, 0xbf, 0x69, 0xe0, 0xe5, 0x45, 0x12, 0x89, 0x80, 0x66, 0x04, 0x35,
	0x54, 0x4c, 0xf2, 0xac, 0x4c, 0x2a, 0x6e, 0x0c, 0x41, 0xd2, 0x99, 0xbc, 0x5c, 0x56, 0x61, 0x51,
	0xa1, 0x22, 0x76, 0x20, 0x48, 0xdc, 0xa9, 0xfc, 0x2c, 0x8d, 0x11, 0xb6, 0xe8, 0x4e, 0x94, 0x40,
	0xfe, 0x35, 0xe3, 0x1f, 0x71, 0xfe, 0xb5, 0xe2, 0x5f, 0x53, 0x7e, 0x87, 0xf3, 0x53, 0xc2, 0x00,
	0x9c, 0x71, 0x0d, 0x70, 0x4c, 0x00, 0x87, 0x06, 0x80, 0x6b, 0x10, 0xb1, 0xdd, 0x05, 0x11, 0x3b,
	0x06, 0x44, 0xfc, 0x71, 0xa0, 0x1c, 0x5b, 0xc4, 0x3c, 0x3f, 0x3d, 0x18, 0x65, 0x48, 0x08, 0xc8,
	0x13, 0x64, 0xab, 0x01, 0x79, 0x1e, 0xda, 0x2a, 0x0f, 0xf5, 0x23, 0xf4, 0x6b, 0x47, 0x10, 0xc8,
	0x78, 0x72, 0x9f, 0xad, 0x53, 0x61, 0x42, 0x7d, 0xc8, 0x3d, 0x84, 0xfe, 0x75, 0x96, 0xdd, 0x71,
	0xf0, 0x3f, 0xa8, 0x25, 0x07, 0xf2, 0x04, 0xc8, 0xe1, 0x1e, 0xc1, 0x68, 0x15, 0x96, 0xd5, 0x22,
	0xdc, 0xf0, 0xdc, 0x6d, 0x67, 0x16, 0x4c, 0x46, 0xd6, 0x38, 0x0f, 0x64, 0xcd, 0xb8, 0x3b, 0x6b,
	0xc0, 0xcc, 0x1a, 0x1f, 0x76, 0xd8, 0xc9, 0x96, 0xcc, 0xb8, 0xdb, 0x0c, 0x4d, 0xf5, 0x31, 0xea,
	0x34, 0x2a, 0x65, 0xa9, 0x9b, 0x5f, 0x1b, 0xa1, 0xbb, 0x93, 0x9f, 0xe7, 0xb8, 0xfb, 0x84, 0xed,
	0xce, 0x49, 0xea, 0xb4, 0xac, 0x88, 0xa9, 0x46, 0x7b, 0xcc, 0x69, 0x8c, 0xa2, 0x36, 0xe4, 0x2c,
	0x97, 0x34, 0xff, 0xa6, 0xcc, 0x86, 0xda, 0x90, 0x1e, 0x08, 0xfb, 0x42, 0x63, 0x16, 0x08, 0x73,
	0xd8, 0xe6, 0x38, 0x86, 0x6b, 0x5d, 0xb6, 0x56, 0x1b, 0xd2, 0x42, 0xe5, 0x9d, 0x7a, 0x0a, 0xe6,
	0x31, 0x77, 0xdb, 0x01, 0xf3, 0xaa, 0xa0, 0xf5, 0xa4, 0x78, 0xb7, 0x23, 0x29, 0x66, 0x1d, 0x49,
	0xf1, 0xa4, 0x23, 0x29, 0x3c, 0x2d, 0x29, 0xfc, 0x9f, 0x60, 0x86, 0x2b, 0x9f, 0xbe, 0xd6, 0x35,
	0x36, 0x83, 0x61, 0xc8, 0xd4, 0x65, 0xe1, 0xca, 0x29, 0xff, 0xef, 0x16, 0xec, 0xfd, 0x34, 0xa9,
	0x6e, 0x9f, 0x15, 0xe1, 0x0b, 0xbe, 0xab, 0x3b, 0x81, 0x5e, 0x22, 0xa2, 0xbd, 0x97, 0xc4, 0x5d,
	0x6b, 0x4d, 0xf4, 0xea, 0xd7, 0xd1, 0xeb, 0x3d, 0x70, 0x92, 0x92, 0x15, 0x5c, 0x18, 0xd9, 0x4e,
	0x20, 0x69, 0x3a, 0xa7, 0x5d, 0x4e, 0x18, 0x60, 0xf2, 0x12, 0xf2, 0x60, 0xc4, 0x4b, 0x10, 0x0c,
	0x64, 0x27, 0x10, 0xa4, 0xc4, 0x58, 0x47, 0x61, 0xac, 0xff, 0x3b, 0x07, 0x46, 0x42, 0xef, 0x1f,
	0xc2, 0x98, 0x05, 0x5b, 0x40, 0x9e, 0xa3, 0xfa, 0x8d, 0x0b, 0xec, 0x5c, 0x4c, 0x9f, 0x6e, 0x05,
	0x8a, 0xd7, 0xfd, 0x08, 0x1c, 0x0c, 0x09, 0xba, 0xae, 0x87, 0xeb, 0x66, 0xf5, 0x6b, 0x88, 0xcd,
	0x9e, 0x6e, 0x05, 0x92, 0x93, 0xde, 0x96, 0x34, 0x72, 0xe9, 0x22, 0x1b, 0x17, 0xd5, 0xee, 0xae,
	0x2b, 0x36, 0x79, 0xba, 0x15, 0x08, 0x3e, 0x5d, 0xc3, 0x08, 0x2d, 0xd6, 0xa9, 0x61, 0xa4, 0x6b,
	0x18, 0x29, 0x59, 0x11, 0xda, 0xb2, 0x43, 0x56, 0xa4, 0x64, 0x45, 0x54, 0x56, 0x18, 0xc7, 0xec,
	0x12, 0x68, 0x2f, 0x1e, 0x4f, 0xc4, 0x34, 0x95, 0x25, 0x79, 0xb1, 0x0a, 0x48, 0x2f, 0x6e, 0x6e,
	0x16, 0x31, 0x47, 0x92, 0x9a, 0xac, 0x0b, 0x36, 0x49, 0x65, 0x71, 0x3e, 0xa1, 0x1e, 0x05, 0x1f,
	0xa7, 0x4b, 0xbd, 0x45, 0xb8, 0x11, 0xea, 0x51, 0xfc, 0xf9, 0x48, 0xe1, 0xc8, 0x18, 0x97, 0x78,
	0x0d, 0xe5, 0x78, 0x24, 0xd1, 0x55, 0x02, 0x63, 0x3e, 0x01, 0x40, 0xf8, 0xbd, 0x2c, 0xc2, 0x94,
	0x01, 0x50, 0x63, 0xe1, 0x85, 0x9c, 0x3f, 0xdd, 0x0a, 0x34, 0x6e, 0xba, 0x96, 0x63, 0xd1, 0x6d,
	0x92, 0x23, 0x3a, 0x35, 0xd6, 0x9e, 0xcb, 0x79, 0xba, 0x56, 0x71, 0x53, 0x63, 0xae, 0xb2, 0xe7,
	0x49, 0x59, 0x25, 0x11, 0x83, 0xad, 0x86, 0x31, 0xbf, 0x10, 0xd3, 0xd4, 0x98, 0x92, 0x97, 0x0a,
	0xe5, 0x0e, 0x49, 0xf2, 0xca, 0xdb, 0x6d, 0x13, 0x7a, 0x25, 0xe7, 0xa9, 0x50, 0xc5, 0x8d, 0x8e,
	0xf8, 0x8a, 0x14, 0xcf, 0xd6, 0x04, 0xc1, 0xb0, 0xe9, 0x08, 0x36, 0x89, 0x8e, 0x60, 0x9f, 0x34,
	0x92, 0x5f, 0xf0, 0x6c, 0x46, 0x9c, 0x6c, 0x44, 0xb2, 0xc8, 0x75, 0x1a, 0xc9, 0x82, 0x93, 0xae,
	0x8a, 0x6e, 0xc3, 0xf4, 0x39, 0x59, 0xc4, 0x08, 0xa0, 0xcd, 0x5a, 0x91, 0xcf, 0xd2, 0x55, 0x82,
	0xd3, 0xbd, 0x80, 0x7d, 0xaa, 0x2c, 0xe6, 0xa6, 0xd8, 0x16, 0x11, 0x76, 0xfb, 0xf8, 0x9b, 0xcd,
	0x13, 0x1a, 0x6c, 0xa7, 0x5b, 0x41, 0x73, 0x2d, 0x55, 0x03, 0xaf, 0x02, 0xea, 0x1e, 0xb7, 0x4d,
	0x8d, 0x2b, 0x3e, 0x4b, 0xd5, 0x10, 0x9c, 0x14, 0xad, 0xaa, 0x8d, 0x17, 0xcd, 0xad, 0xc3, 0x41,
	0xd0, 0xab, 0x36, 0x4f, 0x47, 0x30, 0xf8, 0x2a, 0x5c, 0xad, 0x89, 0xff, 0x4a, 0xd5, 0x69, 0x32,
	0xef, 0xff, 0x0f, 0x6d, 0xdf, 0x87, 0x8d, 0xb6, 0x6f, 0x8f, 0x9f, 0xea, 0xd3, 0x8c, 0xf5, 0x3a,
	0x1a, 0xf8, 0x99, 0x1d, 0xd9, 0xb0, 0xd1, 0x91, 0x7d, 0x0c, 0x8e, 0x58, 0xd5, 0xda, 0x39, 0x78,
	0x30, 0x32, 0xcb, 0x49, 0x41, 0xfa, 0x67, 0xb2, 0xf5, 0x10, 0x60, 0xf6, 0xdf, 0xb6, 0x58, 0xfe,
	0x9f, 0x54, 0x0d, 0xce, 0x31, 0xee, 0x8d, 0x75, 0x31, 0x8f, 0x32, 0x9e, 0x68, 0x30, 0x46, 0xaa,
	0xc1, 0xf0, 0xff, 0xdc, 0x0c, 0x82, 0xe8, 0xc1, 0x3e, 0xb6, 0xeb, 0xb2, 0xd3, 0xaf, 0x2c, 0xbb,
	0xfb, 0xca, 0xea, 0xb7, 0x5f, 0x59, 0x03, 0xad, 0x2d, 0x30, 0xae, 0xcd, 0x61, 0xed, 0xda, 0xf4,
	0x7f, 0x55, 0x37, 0x6e, 0x24, 0xcc, 0x62, 0x29, 0xb3, 0x74, 0x29, 0x29, 0xc4, 0xd9, 0x9a, 0x38,
	0x5d, 0xf1, 0x7e, 0x4d, 0x71, 0x43, 0x95, 0x41, 0x5d, 0x95, 0xbf, 0xf5, 0xb4, 0xbe, 0x3c, 0x7e,
	0xdb, 0x4e, 0x3c, 0xb2, 0x9d, 0xf8, 0x99, 0x74, 0x24, 0xbf, 0x31, 0xa5, 0x8d, 0x2c, 0xcd, 0x46,
	0xe6, 0x7b, 0x85, 0x23, 0x2b, 0x4c, 0x4d, 0x5e, 0xdf, 0x94, 0xd7, 0x12, 0x53, 0xfe, 0xab, 0x9e,
	0x11, 0x35, 0xf4, 0x82, 0xfd, 0x5f, 0x1b, 0x97, 0x7a, 0x55, 0xd9, 0x6f, 0xa9, 0x2a, 0xff, 0x73,
	0x03, 0xf3, 0x01, 0x4c, 0xc4, 0x0a, 0xce, 0xc4, 0x3c, 0x58, 0x1b, 0x75, 0x3f, 0x84, 0x41, 0x1e,
	0x6e, 0xce, 0x58, 0xf2, 0x4e, 0xea, 0x37, 0xdd, 0x22, 0xdc, 0x5c, 0x6e, 0x72, 0x12, 0x30, 0x1e,
	0x7a, 0x00, 0x2c, 0xd8, 0x99, 0x23, 0xf0, 0xdb, 0xf0, 0xed, 0x4e, 0xcd, 0xb7, 0x46, 0x3f, 0xbf,
	0x5b, 0xeb, 0xe7, 0xb5, 0x64, 0x9a, 0x18, 0xa5, 0xf1, 0x6f, 0x2d, 0xf9, 0x6e, 0xa8, 0x8a, 0x91,
	0x37, 0xf0, 0xda, 0xd0, 0x44, 0x3d, 0x43, 0xdf, 0x41, 0xfd, 0xfd, 0xe1, 0x0f, 0x4a, 0x2f, 0x55,
	0xeb, 0x3c, 0xe0, 0xee, 0x19, 0x0c, 0xab, 0xec, 0xea, 0x2a, 0x89, 0xb9, 0x4e, 0x9c, 0x6a, 0x91,
	0x7b, 0x00, 0x83, 0x2a, 0xa3, 0x8c, 0x4c, 0x26, 0x23, 0x64, 0xbc, 0x0d, 0x35, 0x50, 0x79, 0x1f,
	0x20, 0x25, 0x2f, 0x2e, 0xb8, 0x40, 0x96, 0x7c, 0xda, 0x88, 0xff, 0x6b, 0xab, 0xf6, 0xe6, 0x8a,
	0x57, 0x75, 0xb7, 0x8e, 0xdd, 0xef, 0x79, 0x6d, 0x90, 0xa6, 0x75, 0x89, 0xfd, 0xae, 0x2e, 0x71,
	0xa0, 0x77, 0x89, 0xfe, 0x6f, 0xd4, 0x35, 0x20, 0x0b, 0xb5, 0x87, 0xd5, 0x11, 0x02, 0x7a, 0x5d,
	0x02, 0x6c, 0xa3, 0x0d, 0x15, 0x6a, 0xf6, 0x4d, 0xe4, 0x65, 0x21, 0x28, 0x2d, 0x2a, 0x69, 0x7f,
	0x29, 0xed, 0xa3, 0xca, 0xbf, 0x87, 0x53, 0x16, 0xb7, 0xef, 0x69, 0xdb, 0x37, 0x52, 0xd6, 0xff,
	0xb1, 0x42, 0x1c, 0x5e, 0x0f, 0x1a, 0x3b, 0xda, 0x6d, 0x3b, 0x6a, 0x76, 0xf5, 0xff, 0xa5, 0xde,
	0x48, 0x65, 0x51, 0xf6, 0x35, 0x6a, 0x06, 0x8d, 0x87, 0xb1, 0x71, 0xed, 0x61, 0xec, 0x9f, 0xea,
	0xed, 0x55, 0x54, 0xb3, 0x6f, 0xef, 0xb2, 0xd7, 0xbd, 0xcb, 0x98, 0xff, 0x9e, 0x91, 0x15, 0xa9,
	0x08, 0x02, 0x28, 0xfa, 0x8f, 0xd1, 0xfe, 0x4b, 0xf0, 0xba, 0xea, 0xfc, 0x96, 0xd2, 0xe5, 0xa1,
	0x02, 0x5b, 0xc5, 0x96, 0x6d, 0xc4, 0x96, 0x86, 0x9d, 0x7d, 0x03, 0x3b, 0xfd, 0xa5, 0xf1, 0xa0,
	0x8e, 0x20, 0xd3, 0x14, 0x39, 0x05, 0x3b, 0x4b, 0x84, 0x34, 0xfa, 0x69, 0x02, 0xac, 0x5d, 0x07,
	0xd8, 0x73, 0xd8, 0x57, 0x3f, 0x8a, 0xc4, 0xe3, 0xc2, 0xc7, 0xc2, 0xa6, 0xd8, 0x4f, 0x5b, 0xdd,
	0xdd, 0x23, 0x16, 0xa5, 0x1a, 0xaf, 0x7f, 0x06, 0x53, 0xf9, 0x5b, 0x43, 0xec, 0xf6, 0x03, 0x5e,
	0x7a, 0x6b, 0x9b, 0x3d, 0x69, 0x79, 0x72, 0xc0, 0xbd, 0x14, 0xa7, 0xff, 0x14, 0x76, 0xc4, 0x8f,
	0x03, 0xdc, 0xe6, 0x98, 0x5d, 0x46, 0xda, 0x2e, 0x2d, 0x1d, 0x13, 0xab, 0x92, 0x05, 0x9f, 0xff,
	0x23, 0xd8, 0x65, 0xa5, 0x1c, 0x7f, 0x26, 0x76, 0xbf, 0x43, 0xb3, 0x40, 0xdb, 0x42, 0x7b, 0x38,
	0x54, 0xcf, 0xc8, 0x01, 0xe7, 0xa1, 0xa7, 0x91, 0x8f, 0xa3, 0xda, 0x69, 0x32, 0x31, 0xd6, 0x7e,
	0x1a, 0xb9, 0x24, 0x50, 0x9c, 0xfe, 0x07, 0x30, 0xe1, 0x38, 0x25, 0x36, 0x3a, 0x80, 0x01, 0x4e,
	0x73, 0xb0, 0x62, 0x84, 0x7f, 0x0a, 0x20, 0x9f, 0xa8, 0x96, 0xee, 0x27, 0xb0, 0x23, 0x1a, 0xd7,
	0xee, 0x73, 0x0b, 0xfe, 0xc0, 0xe0, 0xfd, 0xf6, 0xa9, 0x04, 0x48, 0x5e, 0x51, 0xb8, 0x13, 0x00,
	0x3e, 0xf2, 0x59, 0x51, 0x4c, 0xb7, 0x5c, 0x57, 0xe7, 0x78, 0x9a, 0x65, 0x77, 0x53, 0xcb, 0x1c,
	0xfb, 0x22, 0x2c, 0xab, 0x69, 0xef, 0x7a, 0x88, 0xbf, 0x18, 0xbf, 0xff, 0xef, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xfa, 0x73, 0xfa, 0xa6, 0x73, 0x1c, 0x00, 0x00,
}
