// Code generated by protoc-gen-go. DO NOT EDIT.
// source: goldbill.proto

/*
Package goldbill is a generated protocol buffer package.

It is generated from these files:
	goldbill.proto

It has these top-level messages:
	GoldbillAction
	GoldbillInitPlatform
	GoldbillRegisterUser
	GoldbillSetFee
	GoldbillSetStamps
	GoldbillSetBail
	GoldbillWithdraw
	GoldbillDeposit
	GoldbillPayKCoin
	GoldbillInvoice
	GoldbillAddBill
	GoldbillWithdrawKcoin
	GoldbillDepositKcoin
	GoldbillBatchSell
	GoldbillBatchCancelSell
	GoldbillBatchBuy
	GoldbillBatchPay
	GoldbillBatchTakeOut
	GoldbillSliceBill
	GoldbillBatchRegUser
	GoldbillResponseInitPlatform
	GoldbillResponseRegisterUser
	GoldbillResponseSetFee
	GoldbillResponseSetStamps
	GoldbillResponseSetBail
	GoldbillResponseWithdraw
	GoldbillResponseDeposit
	GoldbillResponsePayKCoin
	GoldbillResponseInvoice
	GoldbillResponseAddBill
	GoldbillResponseWithdrawKcoin
	GoldbillResponseDepositKcoin
	GoldbillResponseBatchSell
	GoldbillResponseBatchCancelSell
	GoldbillResponseBatchBuy
	GoldbillResponseBatchPay
	GoldbillResponseSliceBill
	GoldbillResponseBatchTakeOut
	GoldbillResponseBatchRegUser
	GoldbillPlatform
	GoldbillUser
	GoldbillAdmin
	GoldbillKeyUid
	GoldbillPickUp
	GoldbillTakeDelivery
	GoldbillDetail
	GoldbillCommonInvoice
	GoldbillVATInvoice
	GoldbillBatchSellList
	GoldbillPayTo
	GoldbillSmall
	GoldbillUserState
*/
package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GoldbillActionType int32

const (
	GoldbillActionType_MsgError           GoldbillActionType = 0
	GoldbillActionType_MsgInitPlatform    GoldbillActionType = 1
	GoldbillActionType_MsgRegisterUser    GoldbillActionType = 2
	GoldbillActionType_MsgSetFee          GoldbillActionType = 3
	GoldbillActionType_MsgSetStamps       GoldbillActionType = 4
	GoldbillActionType_MsgSetBail         GoldbillActionType = 5
	GoldbillActionType_MsgWithdraw        GoldbillActionType = 6
	GoldbillActionType_MsgDeposit         GoldbillActionType = 7
	GoldbillActionType_MsgDepositKcoin    GoldbillActionType = 8
	GoldbillActionType_MsgWithdrawKcoin   GoldbillActionType = 9
	GoldbillActionType_MsgPayKCoin        GoldbillActionType = 10
	GoldbillActionType_MsgInvoice         GoldbillActionType = 11
	GoldbillActionType_MsgAddBill         GoldbillActionType = 12
	GoldbillActionType_MsgBatchSell       GoldbillActionType = 13
	GoldbillActionType_MsgBatchCancelSell GoldbillActionType = 14
	GoldbillActionType_MsgBatchBuy        GoldbillActionType = 15
	GoldbillActionType_MsgBatchPay        GoldbillActionType = 16
	GoldbillActionType_MsgBatchTakeOut    GoldbillActionType = 17
	GoldbillActionType_MsgSliceBill       GoldbillActionType = 18
	GoldbillActionType_MsgBatchRegUser    GoldbillActionType = 19
	GoldbillActionType_MsgCount           GoldbillActionType = 99
)

var GoldbillActionType_name = map[int32]string{
	0:  "MsgError",
	1:  "MsgInitPlatform",
	2:  "MsgRegisterUser",
	3:  "MsgSetFee",
	4:  "MsgSetStamps",
	5:  "MsgSetBail",
	6:  "MsgWithdraw",
	7:  "MsgDeposit",
	8:  "MsgDepositKcoin",
	9:  "MsgWithdrawKcoin",
	10: "MsgPayKCoin",
	11: "MsgInvoice",
	12: "MsgAddBill",
	13: "MsgBatchSell",
	14: "MsgBatchCancelSell",
	15: "MsgBatchBuy",
	16: "MsgBatchPay",
	17: "MsgBatchTakeOut",
	18: "MsgSliceBill",
	19: "MsgBatchRegUser",
	99: "MsgCount",
}
var GoldbillActionType_value = map[string]int32{
	"MsgError":           0,
	"MsgInitPlatform":    1,
	"MsgRegisterUser":    2,
	"MsgSetFee":          3,
	"MsgSetStamps":       4,
	"MsgSetBail":         5,
	"MsgWithdraw":        6,
	"MsgDeposit":         7,
	"MsgDepositKcoin":    8,
	"MsgWithdrawKcoin":   9,
	"MsgPayKCoin":        10,
	"MsgInvoice":         11,
	"MsgAddBill":         12,
	"MsgBatchSell":       13,
	"MsgBatchCancelSell": 14,
	"MsgBatchBuy":        15,
	"MsgBatchPay":        16,
	"MsgBatchTakeOut":    17,
	"MsgSliceBill":       18,
	"MsgBatchRegUser":    19,
	"MsgCount":           99,
}

func (x GoldbillActionType) String() string {
	return proto.EnumName(GoldbillActionType_name, int32(x))
}
func (GoldbillActionType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type GoldbillUserType int32

const (
	GoldbillUserType_UT_UNKNOWN GoldbillUserType = 0
	GoldbillUserType_UT_USER    GoldbillUserType = 1
	GoldbillUserType_UT_ADMIN   GoldbillUserType = 2
)

var GoldbillUserType_name = map[int32]string{
	0: "UT_UNKNOWN",
	1: "UT_USER",
	2: "UT_ADMIN",
}
var GoldbillUserType_value = map[string]int32{
	"UT_UNKNOWN": 0,
	"UT_USER":    1,
	"UT_ADMIN":   2,
}

func (x GoldbillUserType) String() string {
	return proto.EnumName(GoldbillUserType_name, int32(x))
}
func (GoldbillUserType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type GoldbillTakeOutType int32

const (
	GoldbillTakeOutType_TOT_UNKNOWN      GoldbillTakeOutType = 0
	GoldbillTakeOutType_TOT_PICKUP       GoldbillTakeOutType = 1
	GoldbillTakeOutType_TOT_TAKEDELIVERY GoldbillTakeOutType = 2
)

var GoldbillTakeOutType_name = map[int32]string{
	0: "TOT_UNKNOWN",
	1: "TOT_PICKUP",
	2: "TOT_TAKEDELIVERY",
}
var GoldbillTakeOutType_value = map[string]int32{
	"TOT_UNKNOWN":      0,
	"TOT_PICKUP":       1,
	"TOT_TAKEDELIVERY": 2,
}

func (x GoldbillTakeOutType) String() string {
	return proto.EnumName(GoldbillTakeOutType_name, int32(x))
}
func (GoldbillTakeOutType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type GoldbillDeliveryFeeType int32

const (
	GoldbillDeliveryFeeType_DFT_UNKNOWN GoldbillDeliveryFeeType = 0
	GoldbillDeliveryFeeType_DFT_DF      GoldbillDeliveryFeeType = 1
	GoldbillDeliveryFeeType_DFT_YJ      GoldbillDeliveryFeeType = 2
)

var GoldbillDeliveryFeeType_name = map[int32]string{
	0: "DFT_UNKNOWN",
	1: "DFT_DF",
	2: "DFT_YJ",
}
var GoldbillDeliveryFeeType_value = map[string]int32{
	"DFT_UNKNOWN": 0,
	"DFT_DF":      1,
	"DFT_YJ":      2,
}

func (x GoldbillDeliveryFeeType) String() string {
	return proto.EnumName(GoldbillDeliveryFeeType_name, int32(x))
}
func (GoldbillDeliveryFeeType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type GoldbillState int32

const (
	GoldbillState_BS_UNKNOWN GoldbillState = 0
	GoldbillState_BS_FREE    GoldbillState = 1
	GoldbillState_BS_FROZEN  GoldbillState = 2
	GoldbillState_BS_SELL    GoldbillState = 3
	GoldbillState_BS_TAKEOUT GoldbillState = 4
)

var GoldbillState_name = map[int32]string{
	0: "BS_UNKNOWN",
	1: "BS_FREE",
	2: "BS_FROZEN",
	3: "BS_SELL",
	4: "BS_TAKEOUT",
}
var GoldbillState_value = map[string]int32{
	"BS_UNKNOWN": 0,
	"BS_FREE":    1,
	"BS_FROZEN":  2,
	"BS_SELL":    3,
	"BS_TAKEOUT": 4,
}

func (x GoldbillState) String() string {
	return proto.EnumName(GoldbillState_name, int32(x))
}
func (GoldbillState) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type GoldbillInvoiceType int32

const (
	GoldbillInvoiceType_IT_UNKNOWN GoldbillInvoiceType = 0
	GoldbillInvoiceType_IT_COM     GoldbillInvoiceType = 1
	GoldbillInvoiceType_IT_VAT     GoldbillInvoiceType = 2
)

var GoldbillInvoiceType_name = map[int32]string{
	0: "IT_UNKNOWN",
	1: "IT_COM",
	2: "IT_VAT",
}
var GoldbillInvoiceType_value = map[string]int32{
	"IT_UNKNOWN": 0,
	"IT_COM":     1,
	"IT_VAT":     2,
}

func (x GoldbillInvoiceType) String() string {
	return proto.EnumName(GoldbillInvoiceType_name, int32(x))
}
func (GoldbillInvoiceType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type GoldbillAction struct {
	// Types that are valid to be assigned to Value:
	//	*GoldbillAction_InitPlatform
	//	*GoldbillAction_RegisterUser
	//	*GoldbillAction_SetFee
	//	*GoldbillAction_SetStamps
	//	*GoldbillAction_SetBail
	//	*GoldbillAction_Withdraw
	//	*GoldbillAction_Deposit
	//	*GoldbillAction_WithdrawKcoin
	//	*GoldbillAction_DepositKcoin
	//	*GoldbillAction_PayKCoin
	//	*GoldbillAction_Invoice
	//	*GoldbillAction_AddBill
	//	*GoldbillAction_BatchSell
	//	*GoldbillAction_BatchCancelSell
	//	*GoldbillAction_BatchBuy
	//	*GoldbillAction_BatchPay
	//	*GoldbillAction_BatchTakeOut
	//	*GoldbillAction_SliceBill
	//	*GoldbillAction_BatchRegUser
	Value isGoldbillAction_Value `protobuf_oneof:"value"`
	Ty    GoldbillActionType     `protobuf:"varint,35,opt,name=ty,enum=goldbill.GoldbillActionType" json:"ty,omitempty"`
}

func (m *GoldbillAction) Reset()                    { *m = GoldbillAction{} }
func (m *GoldbillAction) String() string            { return proto.CompactTextString(m) }
func (*GoldbillAction) ProtoMessage()               {}
func (*GoldbillAction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isGoldbillAction_Value interface {
	isGoldbillAction_Value()
}

type GoldbillAction_InitPlatform struct {
	InitPlatform *GoldbillInitPlatform `protobuf:"bytes,1,opt,name=initPlatform,oneof"`
}
type GoldbillAction_RegisterUser struct {
	RegisterUser *GoldbillRegisterUser `protobuf:"bytes,2,opt,name=registerUser,oneof"`
}
type GoldbillAction_SetFee struct {
	SetFee *GoldbillSetFee `protobuf:"bytes,3,opt,name=setFee,oneof"`
}
type GoldbillAction_SetStamps struct {
	SetStamps *GoldbillSetStamps `protobuf:"bytes,4,opt,name=setStamps,oneof"`
}
type GoldbillAction_SetBail struct {
	SetBail *GoldbillSetBail `protobuf:"bytes,5,opt,name=setBail,oneof"`
}
type GoldbillAction_Withdraw struct {
	Withdraw *GoldbillWithdraw `protobuf:"bytes,6,opt,name=withdraw,oneof"`
}
type GoldbillAction_Deposit struct {
	Deposit *GoldbillDeposit `protobuf:"bytes,7,opt,name=deposit,oneof"`
}
type GoldbillAction_WithdrawKcoin struct {
	WithdrawKcoin *GoldbillWithdrawKcoin `protobuf:"bytes,8,opt,name=withdrawKcoin,oneof"`
}
type GoldbillAction_DepositKcoin struct {
	DepositKcoin *GoldbillDepositKcoin `protobuf:"bytes,9,opt,name=depositKcoin,oneof"`
}
type GoldbillAction_PayKCoin struct {
	PayKCoin *GoldbillPayKCoin `protobuf:"bytes,10,opt,name=payKCoin,oneof"`
}
type GoldbillAction_Invoice struct {
	Invoice *GoldbillInvoice `protobuf:"bytes,11,opt,name=invoice,oneof"`
}
type GoldbillAction_AddBill struct {
	AddBill *GoldbillAddBill `protobuf:"bytes,12,opt,name=addBill,oneof"`
}
type GoldbillAction_BatchSell struct {
	BatchSell *GoldbillBatchSell `protobuf:"bytes,13,opt,name=batchSell,oneof"`
}
type GoldbillAction_BatchCancelSell struct {
	BatchCancelSell *GoldbillBatchCancelSell `protobuf:"bytes,14,opt,name=batchCancelSell,oneof"`
}
type GoldbillAction_BatchBuy struct {
	BatchBuy *GoldbillBatchBuy `protobuf:"bytes,15,opt,name=batchBuy,oneof"`
}
type GoldbillAction_BatchPay struct {
	BatchPay *GoldbillBatchPay `protobuf:"bytes,16,opt,name=batchPay,oneof"`
}
type GoldbillAction_BatchTakeOut struct {
	BatchTakeOut *GoldbillBatchTakeOut `protobuf:"bytes,17,opt,name=batchTakeOut,oneof"`
}
type GoldbillAction_SliceBill struct {
	SliceBill *GoldbillSliceBill `protobuf:"bytes,18,opt,name=sliceBill,oneof"`
}
type GoldbillAction_BatchRegUser struct {
	BatchRegUser *GoldbillBatchRegUser `protobuf:"bytes,19,opt,name=batchRegUser,oneof"`
}

func (*GoldbillAction_InitPlatform) isGoldbillAction_Value()    {}
func (*GoldbillAction_RegisterUser) isGoldbillAction_Value()    {}
func (*GoldbillAction_SetFee) isGoldbillAction_Value()          {}
func (*GoldbillAction_SetStamps) isGoldbillAction_Value()       {}
func (*GoldbillAction_SetBail) isGoldbillAction_Value()         {}
func (*GoldbillAction_Withdraw) isGoldbillAction_Value()        {}
func (*GoldbillAction_Deposit) isGoldbillAction_Value()         {}
func (*GoldbillAction_WithdrawKcoin) isGoldbillAction_Value()   {}
func (*GoldbillAction_DepositKcoin) isGoldbillAction_Value()    {}
func (*GoldbillAction_PayKCoin) isGoldbillAction_Value()        {}
func (*GoldbillAction_Invoice) isGoldbillAction_Value()         {}
func (*GoldbillAction_AddBill) isGoldbillAction_Value()         {}
func (*GoldbillAction_BatchSell) isGoldbillAction_Value()       {}
func (*GoldbillAction_BatchCancelSell) isGoldbillAction_Value() {}
func (*GoldbillAction_BatchBuy) isGoldbillAction_Value()        {}
func (*GoldbillAction_BatchPay) isGoldbillAction_Value()        {}
func (*GoldbillAction_BatchTakeOut) isGoldbillAction_Value()    {}
func (*GoldbillAction_SliceBill) isGoldbillAction_Value()       {}
func (*GoldbillAction_BatchRegUser) isGoldbillAction_Value()    {}

func (m *GoldbillAction) GetValue() isGoldbillAction_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *GoldbillAction) GetInitPlatform() *GoldbillInitPlatform {
	if x, ok := m.GetValue().(*GoldbillAction_InitPlatform); ok {
		return x.InitPlatform
	}
	return nil
}

func (m *GoldbillAction) GetRegisterUser() *GoldbillRegisterUser {
	if x, ok := m.GetValue().(*GoldbillAction_RegisterUser); ok {
		return x.RegisterUser
	}
	return nil
}

func (m *GoldbillAction) GetSetFee() *GoldbillSetFee {
	if x, ok := m.GetValue().(*GoldbillAction_SetFee); ok {
		return x.SetFee
	}
	return nil
}

func (m *GoldbillAction) GetSetStamps() *GoldbillSetStamps {
	if x, ok := m.GetValue().(*GoldbillAction_SetStamps); ok {
		return x.SetStamps
	}
	return nil
}

func (m *GoldbillAction) GetSetBail() *GoldbillSetBail {
	if x, ok := m.GetValue().(*GoldbillAction_SetBail); ok {
		return x.SetBail
	}
	return nil
}

func (m *GoldbillAction) GetWithdraw() *GoldbillWithdraw {
	if x, ok := m.GetValue().(*GoldbillAction_Withdraw); ok {
		return x.Withdraw
	}
	return nil
}

func (m *GoldbillAction) GetDeposit() *GoldbillDeposit {
	if x, ok := m.GetValue().(*GoldbillAction_Deposit); ok {
		return x.Deposit
	}
	return nil
}

func (m *GoldbillAction) GetWithdrawKcoin() *GoldbillWithdrawKcoin {
	if x, ok := m.GetValue().(*GoldbillAction_WithdrawKcoin); ok {
		return x.WithdrawKcoin
	}
	return nil
}

func (m *GoldbillAction) GetDepositKcoin() *GoldbillDepositKcoin {
	if x, ok := m.GetValue().(*GoldbillAction_DepositKcoin); ok {
		return x.DepositKcoin
	}
	return nil
}

func (m *GoldbillAction) GetPayKCoin() *GoldbillPayKCoin {
	if x, ok := m.GetValue().(*GoldbillAction_PayKCoin); ok {
		return x.PayKCoin
	}
	return nil
}

func (m *GoldbillAction) GetInvoice() *GoldbillInvoice {
	if x, ok := m.GetValue().(*GoldbillAction_Invoice); ok {
		return x.Invoice
	}
	return nil
}

func (m *GoldbillAction) GetAddBill() *GoldbillAddBill {
	if x, ok := m.GetValue().(*GoldbillAction_AddBill); ok {
		return x.AddBill
	}
	return nil
}

func (m *GoldbillAction) GetBatchSell() *GoldbillBatchSell {
	if x, ok := m.GetValue().(*GoldbillAction_BatchSell); ok {
		return x.BatchSell
	}
	return nil
}

func (m *GoldbillAction) GetBatchCancelSell() *GoldbillBatchCancelSell {
	if x, ok := m.GetValue().(*GoldbillAction_BatchCancelSell); ok {
		return x.BatchCancelSell
	}
	return nil
}

func (m *GoldbillAction) GetBatchBuy() *GoldbillBatchBuy {
	if x, ok := m.GetValue().(*GoldbillAction_BatchBuy); ok {
		return x.BatchBuy
	}
	return nil
}

func (m *GoldbillAction) GetBatchPay() *GoldbillBatchPay {
	if x, ok := m.GetValue().(*GoldbillAction_BatchPay); ok {
		return x.BatchPay
	}
	return nil
}

func (m *GoldbillAction) GetBatchTakeOut() *GoldbillBatchTakeOut {
	if x, ok := m.GetValue().(*GoldbillAction_BatchTakeOut); ok {
		return x.BatchTakeOut
	}
	return nil
}

func (m *GoldbillAction) GetSliceBill() *GoldbillSliceBill {
	if x, ok := m.GetValue().(*GoldbillAction_SliceBill); ok {
		return x.SliceBill
	}
	return nil
}

func (m *GoldbillAction) GetBatchRegUser() *GoldbillBatchRegUser {
	if x, ok := m.GetValue().(*GoldbillAction_BatchRegUser); ok {
		return x.BatchRegUser
	}
	return nil
}

func (m *GoldbillAction) GetTy() GoldbillActionType {
	if m != nil {
		return m.Ty
	}
	return GoldbillActionType_MsgError
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*GoldbillAction) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _GoldbillAction_OneofMarshaler, _GoldbillAction_OneofUnmarshaler, _GoldbillAction_OneofSizer, []interface{}{
		(*GoldbillAction_InitPlatform)(nil),
		(*GoldbillAction_RegisterUser)(nil),
		(*GoldbillAction_SetFee)(nil),
		(*GoldbillAction_SetStamps)(nil),
		(*GoldbillAction_SetBail)(nil),
		(*GoldbillAction_Withdraw)(nil),
		(*GoldbillAction_Deposit)(nil),
		(*GoldbillAction_WithdrawKcoin)(nil),
		(*GoldbillAction_DepositKcoin)(nil),
		(*GoldbillAction_PayKCoin)(nil),
		(*GoldbillAction_Invoice)(nil),
		(*GoldbillAction_AddBill)(nil),
		(*GoldbillAction_BatchSell)(nil),
		(*GoldbillAction_BatchCancelSell)(nil),
		(*GoldbillAction_BatchBuy)(nil),
		(*GoldbillAction_BatchPay)(nil),
		(*GoldbillAction_BatchTakeOut)(nil),
		(*GoldbillAction_SliceBill)(nil),
		(*GoldbillAction_BatchRegUser)(nil),
	}
}

func _GoldbillAction_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*GoldbillAction)
	// value
	switch x := m.Value.(type) {
	case *GoldbillAction_InitPlatform:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.InitPlatform); err != nil {
			return err
		}
	case *GoldbillAction_RegisterUser:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RegisterUser); err != nil {
			return err
		}
	case *GoldbillAction_SetFee:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SetFee); err != nil {
			return err
		}
	case *GoldbillAction_SetStamps:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SetStamps); err != nil {
			return err
		}
	case *GoldbillAction_SetBail:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SetBail); err != nil {
			return err
		}
	case *GoldbillAction_Withdraw:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Withdraw); err != nil {
			return err
		}
	case *GoldbillAction_Deposit:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Deposit); err != nil {
			return err
		}
	case *GoldbillAction_WithdrawKcoin:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.WithdrawKcoin); err != nil {
			return err
		}
	case *GoldbillAction_DepositKcoin:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DepositKcoin); err != nil {
			return err
		}
	case *GoldbillAction_PayKCoin:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PayKCoin); err != nil {
			return err
		}
	case *GoldbillAction_Invoice:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Invoice); err != nil {
			return err
		}
	case *GoldbillAction_AddBill:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.AddBill); err != nil {
			return err
		}
	case *GoldbillAction_BatchSell:
		b.EncodeVarint(13<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BatchSell); err != nil {
			return err
		}
	case *GoldbillAction_BatchCancelSell:
		b.EncodeVarint(14<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BatchCancelSell); err != nil {
			return err
		}
	case *GoldbillAction_BatchBuy:
		b.EncodeVarint(15<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BatchBuy); err != nil {
			return err
		}
	case *GoldbillAction_BatchPay:
		b.EncodeVarint(16<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BatchPay); err != nil {
			return err
		}
	case *GoldbillAction_BatchTakeOut:
		b.EncodeVarint(17<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BatchTakeOut); err != nil {
			return err
		}
	case *GoldbillAction_SliceBill:
		b.EncodeVarint(18<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SliceBill); err != nil {
			return err
		}
	case *GoldbillAction_BatchRegUser:
		b.EncodeVarint(19<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BatchRegUser); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("GoldbillAction.Value has unexpected type %T", x)
	}
	return nil
}

func _GoldbillAction_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*GoldbillAction)
	switch tag {
	case 1: // value.initPlatform
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GoldbillInitPlatform)
		err := b.DecodeMessage(msg)
		m.Value = &GoldbillAction_InitPlatform{msg}
		return true, err
	case 2: // value.registerUser
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GoldbillRegisterUser)
		err := b.DecodeMessage(msg)
		m.Value = &GoldbillAction_RegisterUser{msg}
		return true, err
	case 3: // value.setFee
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GoldbillSetFee)
		err := b.DecodeMessage(msg)
		m.Value = &GoldbillAction_SetFee{msg}
		return true, err
	case 4: // value.setStamps
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GoldbillSetStamps)
		err := b.DecodeMessage(msg)
		m.Value = &GoldbillAction_SetStamps{msg}
		return true, err
	case 5: // value.setBail
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GoldbillSetBail)
		err := b.DecodeMessage(msg)
		m.Value = &GoldbillAction_SetBail{msg}
		return true, err
	case 6: // value.withdraw
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GoldbillWithdraw)
		err := b.DecodeMessage(msg)
		m.Value = &GoldbillAction_Withdraw{msg}
		return true, err
	case 7: // value.deposit
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GoldbillDeposit)
		err := b.DecodeMessage(msg)
		m.Value = &GoldbillAction_Deposit{msg}
		return true, err
	case 8: // value.withdrawKcoin
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GoldbillWithdrawKcoin)
		err := b.DecodeMessage(msg)
		m.Value = &GoldbillAction_WithdrawKcoin{msg}
		return true, err
	case 9: // value.depositKcoin
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GoldbillDepositKcoin)
		err := b.DecodeMessage(msg)
		m.Value = &GoldbillAction_DepositKcoin{msg}
		return true, err
	case 10: // value.payKCoin
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GoldbillPayKCoin)
		err := b.DecodeMessage(msg)
		m.Value = &GoldbillAction_PayKCoin{msg}
		return true, err
	case 11: // value.invoice
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GoldbillInvoice)
		err := b.DecodeMessage(msg)
		m.Value = &GoldbillAction_Invoice{msg}
		return true, err
	case 12: // value.addBill
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GoldbillAddBill)
		err := b.DecodeMessage(msg)
		m.Value = &GoldbillAction_AddBill{msg}
		return true, err
	case 13: // value.batchSell
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GoldbillBatchSell)
		err := b.DecodeMessage(msg)
		m.Value = &GoldbillAction_BatchSell{msg}
		return true, err
	case 14: // value.batchCancelSell
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GoldbillBatchCancelSell)
		err := b.DecodeMessage(msg)
		m.Value = &GoldbillAction_BatchCancelSell{msg}
		return true, err
	case 15: // value.batchBuy
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GoldbillBatchBuy)
		err := b.DecodeMessage(msg)
		m.Value = &GoldbillAction_BatchBuy{msg}
		return true, err
	case 16: // value.batchPay
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GoldbillBatchPay)
		err := b.DecodeMessage(msg)
		m.Value = &GoldbillAction_BatchPay{msg}
		return true, err
	case 17: // value.batchTakeOut
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GoldbillBatchTakeOut)
		err := b.DecodeMessage(msg)
		m.Value = &GoldbillAction_BatchTakeOut{msg}
		return true, err
	case 18: // value.sliceBill
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GoldbillSliceBill)
		err := b.DecodeMessage(msg)
		m.Value = &GoldbillAction_SliceBill{msg}
		return true, err
	case 19: // value.batchRegUser
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GoldbillBatchRegUser)
		err := b.DecodeMessage(msg)
		m.Value = &GoldbillAction_BatchRegUser{msg}
		return true, err
	default:
		return false, nil
	}
}

func _GoldbillAction_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*GoldbillAction)
	// value
	switch x := m.Value.(type) {
	case *GoldbillAction_InitPlatform:
		s := proto.Size(x.InitPlatform)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GoldbillAction_RegisterUser:
		s := proto.Size(x.RegisterUser)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GoldbillAction_SetFee:
		s := proto.Size(x.SetFee)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GoldbillAction_SetStamps:
		s := proto.Size(x.SetStamps)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GoldbillAction_SetBail:
		s := proto.Size(x.SetBail)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GoldbillAction_Withdraw:
		s := proto.Size(x.Withdraw)
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GoldbillAction_Deposit:
		s := proto.Size(x.Deposit)
		n += proto.SizeVarint(7<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GoldbillAction_WithdrawKcoin:
		s := proto.Size(x.WithdrawKcoin)
		n += proto.SizeVarint(8<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GoldbillAction_DepositKcoin:
		s := proto.Size(x.DepositKcoin)
		n += proto.SizeVarint(9<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GoldbillAction_PayKCoin:
		s := proto.Size(x.PayKCoin)
		n += proto.SizeVarint(10<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GoldbillAction_Invoice:
		s := proto.Size(x.Invoice)
		n += proto.SizeVarint(11<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GoldbillAction_AddBill:
		s := proto.Size(x.AddBill)
		n += proto.SizeVarint(12<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GoldbillAction_BatchSell:
		s := proto.Size(x.BatchSell)
		n += proto.SizeVarint(13<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GoldbillAction_BatchCancelSell:
		s := proto.Size(x.BatchCancelSell)
		n += proto.SizeVarint(14<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GoldbillAction_BatchBuy:
		s := proto.Size(x.BatchBuy)
		n += proto.SizeVarint(15<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GoldbillAction_BatchPay:
		s := proto.Size(x.BatchPay)
		n += proto.SizeVarint(16<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GoldbillAction_BatchTakeOut:
		s := proto.Size(x.BatchTakeOut)
		n += proto.SizeVarint(17<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GoldbillAction_SliceBill:
		s := proto.Size(x.SliceBill)
		n += proto.SizeVarint(18<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GoldbillAction_BatchRegUser:
		s := proto.Size(x.BatchRegUser)
		n += proto.SizeVarint(19<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type GoldbillInitPlatform struct {
	PlatformKey []byte `protobuf:"bytes,1,opt,name=platformKey,proto3" json:"platformKey,omitempty"`
	Info        string `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
}

func (m *GoldbillInitPlatform) Reset()                    { *m = GoldbillInitPlatform{} }
func (m *GoldbillInitPlatform) String() string            { return proto.CompactTextString(m) }
func (*GoldbillInitPlatform) ProtoMessage()               {}
func (*GoldbillInitPlatform) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GoldbillInitPlatform) GetPlatformKey() []byte {
	if m != nil {
		return m.PlatformKey
	}
	return nil
}

func (m *GoldbillInitPlatform) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

type GoldbillRegisterUser struct {
	UserPubkey []byte           `protobuf:"bytes,1,opt,name=userPubkey,proto3" json:"userPubkey,omitempty"`
	UserId     string           `protobuf:"bytes,2,opt,name=userId" json:"userId,omitempty"`
	UserType   GoldbillUserType `protobuf:"varint,3,opt,name=userType,enum=goldbill.GoldbillUserType" json:"userType,omitempty"`
}

func (m *GoldbillRegisterUser) Reset()                    { *m = GoldbillRegisterUser{} }
func (m *GoldbillRegisterUser) String() string            { return proto.CompactTextString(m) }
func (*GoldbillRegisterUser) ProtoMessage()               {}
func (*GoldbillRegisterUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GoldbillRegisterUser) GetUserPubkey() []byte {
	if m != nil {
		return m.UserPubkey
	}
	return nil
}

func (m *GoldbillRegisterUser) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GoldbillRegisterUser) GetUserType() GoldbillUserType {
	if m != nil {
		return m.UserType
	}
	return GoldbillUserType_UT_UNKNOWN
}

type GoldbillSetFee struct {
	Fee int64 `protobuf:"varint,1,opt,name=fee" json:"fee,omitempty"`
}

func (m *GoldbillSetFee) Reset()                    { *m = GoldbillSetFee{} }
func (m *GoldbillSetFee) String() string            { return proto.CompactTextString(m) }
func (*GoldbillSetFee) ProtoMessage()               {}
func (*GoldbillSetFee) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GoldbillSetFee) GetFee() int64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

type GoldbillSetStamps struct {
	Stamps int64 `protobuf:"varint,1,opt,name=stamps" json:"stamps,omitempty"`
}

func (m *GoldbillSetStamps) Reset()                    { *m = GoldbillSetStamps{} }
func (m *GoldbillSetStamps) String() string            { return proto.CompactTextString(m) }
func (*GoldbillSetStamps) ProtoMessage()               {}
func (*GoldbillSetStamps) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GoldbillSetStamps) GetStamps() int64 {
	if m != nil {
		return m.Stamps
	}
	return 0
}

type GoldbillSetBail struct {
	Bail int64 `protobuf:"varint,1,opt,name=bail" json:"bail,omitempty"`
}

func (m *GoldbillSetBail) Reset()                    { *m = GoldbillSetBail{} }
func (m *GoldbillSetBail) String() string            { return proto.CompactTextString(m) }
func (*GoldbillSetBail) ProtoMessage()               {}
func (*GoldbillSetBail) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GoldbillSetBail) GetBail() int64 {
	if m != nil {
		return m.Bail
	}
	return 0
}

type GoldbillWithdraw struct {
	Amount int64  `protobuf:"varint,1,opt,name=amount" json:"amount,omitempty"`
	Uid    string `protobuf:"bytes,2,opt,name=uid" json:"uid,omitempty"`
	Pubkey []byte `protobuf:"bytes,3,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
}

func (m *GoldbillWithdraw) Reset()                    { *m = GoldbillWithdraw{} }
func (m *GoldbillWithdraw) String() string            { return proto.CompactTextString(m) }
func (*GoldbillWithdraw) ProtoMessage()               {}
func (*GoldbillWithdraw) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GoldbillWithdraw) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *GoldbillWithdraw) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *GoldbillWithdraw) GetPubkey() []byte {
	if m != nil {
		return m.Pubkey
	}
	return nil
}

type GoldbillDeposit struct {
	Amount int64 `protobuf:"varint,1,opt,name=amount" json:"amount,omitempty"`
}

func (m *GoldbillDeposit) Reset()                    { *m = GoldbillDeposit{} }
func (m *GoldbillDeposit) String() string            { return proto.CompactTextString(m) }
func (*GoldbillDeposit) ProtoMessage()               {}
func (*GoldbillDeposit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GoldbillDeposit) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type GoldbillPayKCoin struct {
	Amount   int64  `protobuf:"varint,1,opt,name=amount" json:"amount,omitempty"`
	Phone    int64  `protobuf:"varint,2,opt,name=phone" json:"phone,omitempty"`
	Name     string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Topubkey []byte `protobuf:"bytes,4,opt,name=topubkey,proto3" json:"topubkey,omitempty"`
}

func (m *GoldbillPayKCoin) Reset()                    { *m = GoldbillPayKCoin{} }
func (m *GoldbillPayKCoin) String() string            { return proto.CompactTextString(m) }
func (*GoldbillPayKCoin) ProtoMessage()               {}
func (*GoldbillPayKCoin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *GoldbillPayKCoin) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *GoldbillPayKCoin) GetPhone() int64 {
	if m != nil {
		return m.Phone
	}
	return 0
}

func (m *GoldbillPayKCoin) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GoldbillPayKCoin) GetTopubkey() []byte {
	if m != nil {
		return m.Topubkey
	}
	return nil
}

type GoldbillInvoice struct {
	InvoiceType   GoldbillInvoiceType    `protobuf:"varint,1,opt,name=invoiceType,enum=goldbill.GoldbillInvoiceType" json:"invoiceType,omitempty"`
	CommonInvoice *GoldbillCommonInvoice `protobuf:"bytes,2,opt,name=commonInvoice" json:"commonInvoice,omitempty"`
	VatInvoice    *GoldbillVATInvoice    `protobuf:"bytes,3,opt,name=vatInvoice" json:"vatInvoice,omitempty"`
}

func (m *GoldbillInvoice) Reset()                    { *m = GoldbillInvoice{} }
func (m *GoldbillInvoice) String() string            { return proto.CompactTextString(m) }
func (*GoldbillInvoice) ProtoMessage()               {}
func (*GoldbillInvoice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *GoldbillInvoice) GetInvoiceType() GoldbillInvoiceType {
	if m != nil {
		return m.InvoiceType
	}
	return GoldbillInvoiceType_IT_UNKNOWN
}

func (m *GoldbillInvoice) GetCommonInvoice() *GoldbillCommonInvoice {
	if m != nil {
		return m.CommonInvoice
	}
	return nil
}

func (m *GoldbillInvoice) GetVatInvoice() *GoldbillVATInvoice {
	if m != nil {
		return m.VatInvoice
	}
	return nil
}

type GoldbillAddBill struct {
	BillList []*GoldbillDetail `protobuf:"bytes,1,rep,name=billList" json:"billList,omitempty"`
}

func (m *GoldbillAddBill) Reset()                    { *m = GoldbillAddBill{} }
func (m *GoldbillAddBill) String() string            { return proto.CompactTextString(m) }
func (*GoldbillAddBill) ProtoMessage()               {}
func (*GoldbillAddBill) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *GoldbillAddBill) GetBillList() []*GoldbillDetail {
	if m != nil {
		return m.BillList
	}
	return nil
}

type GoldbillWithdrawKcoin struct {
	Uid    string `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
	Amount int64  `protobuf:"varint,2,opt,name=amount" json:"amount,omitempty"`
}

func (m *GoldbillWithdrawKcoin) Reset()                    { *m = GoldbillWithdrawKcoin{} }
func (m *GoldbillWithdrawKcoin) String() string            { return proto.CompactTextString(m) }
func (*GoldbillWithdrawKcoin) ProtoMessage()               {}
func (*GoldbillWithdrawKcoin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *GoldbillWithdrawKcoin) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *GoldbillWithdrawKcoin) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type GoldbillDepositKcoin struct {
	Amount int64 `protobuf:"varint,1,opt,name=amount" json:"amount,omitempty"`
}

func (m *GoldbillDepositKcoin) Reset()                    { *m = GoldbillDepositKcoin{} }
func (m *GoldbillDepositKcoin) String() string            { return proto.CompactTextString(m) }
func (*GoldbillDepositKcoin) ProtoMessage()               {}
func (*GoldbillDepositKcoin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *GoldbillDepositKcoin) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type GoldbillBatchSell struct {
	BillList []*GoldbillDetail `protobuf:"bytes,1,rep,name=billList" json:"billList,omitempty"`
}

func (m *GoldbillBatchSell) Reset()                    { *m = GoldbillBatchSell{} }
func (m *GoldbillBatchSell) String() string            { return proto.CompactTextString(m) }
func (*GoldbillBatchSell) ProtoMessage()               {}
func (*GoldbillBatchSell) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *GoldbillBatchSell) GetBillList() []*GoldbillDetail {
	if m != nil {
		return m.BillList
	}
	return nil
}

type GoldbillBatchCancelSell struct {
	BillList []string `protobuf:"bytes,2,rep,name=billList" json:"billList,omitempty"`
}

func (m *GoldbillBatchCancelSell) Reset()                    { *m = GoldbillBatchCancelSell{} }
func (m *GoldbillBatchCancelSell) String() string            { return proto.CompactTextString(m) }
func (*GoldbillBatchCancelSell) ProtoMessage()               {}
func (*GoldbillBatchCancelSell) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *GoldbillBatchCancelSell) GetBillList() []string {
	if m != nil {
		return m.BillList
	}
	return nil
}

type GoldbillBatchBuy struct {
	BillList []string `protobuf:"bytes,3,rep,name=billList" json:"billList,omitempty"`
}

func (m *GoldbillBatchBuy) Reset()                    { *m = GoldbillBatchBuy{} }
func (m *GoldbillBatchBuy) String() string            { return proto.CompactTextString(m) }
func (*GoldbillBatchBuy) ProtoMessage()               {}
func (*GoldbillBatchBuy) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *GoldbillBatchBuy) GetBillList() []string {
	if m != nil {
		return m.BillList
	}
	return nil
}

type GoldbillBatchPay struct {
	PayTo []*GoldbillPayTo `protobuf:"bytes,2,rep,name=payTo" json:"payTo,omitempty"`
}

func (m *GoldbillBatchPay) Reset()                    { *m = GoldbillBatchPay{} }
func (m *GoldbillBatchPay) String() string            { return proto.CompactTextString(m) }
func (*GoldbillBatchPay) ProtoMessage()               {}
func (*GoldbillBatchPay) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *GoldbillBatchPay) GetPayTo() []*GoldbillPayTo {
	if m != nil {
		return m.PayTo
	}
	return nil
}

type GoldbillBatchTakeOut struct {
	BillId       []string              `protobuf:"bytes,1,rep,name=billId" json:"billId,omitempty"`
	TakeOutType  GoldbillTakeOutType   `protobuf:"varint,2,opt,name=takeOutType,enum=goldbill.GoldbillTakeOutType" json:"takeOutType,omitempty"`
	PickUp       *GoldbillPickUp       `protobuf:"bytes,3,opt,name=pickUp" json:"pickUp,omitempty"`
	TakeDelivery *GoldbillTakeDelivery `protobuf:"bytes,4,opt,name=takeDelivery" json:"takeDelivery,omitempty"`
}

func (m *GoldbillBatchTakeOut) Reset()                    { *m = GoldbillBatchTakeOut{} }
func (m *GoldbillBatchTakeOut) String() string            { return proto.CompactTextString(m) }
func (*GoldbillBatchTakeOut) ProtoMessage()               {}
func (*GoldbillBatchTakeOut) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *GoldbillBatchTakeOut) GetBillId() []string {
	if m != nil {
		return m.BillId
	}
	return nil
}

func (m *GoldbillBatchTakeOut) GetTakeOutType() GoldbillTakeOutType {
	if m != nil {
		return m.TakeOutType
	}
	return GoldbillTakeOutType_TOT_UNKNOWN
}

func (m *GoldbillBatchTakeOut) GetPickUp() *GoldbillPickUp {
	if m != nil {
		return m.PickUp
	}
	return nil
}

func (m *GoldbillBatchTakeOut) GetTakeDelivery() *GoldbillTakeDelivery {
	if m != nil {
		return m.TakeDelivery
	}
	return nil
}

type GoldbillSliceBill struct {
	BigId     string           `protobuf:"bytes,1,opt,name=bigId" json:"bigId,omitempty"`
	SmallBill []*GoldbillSmall `protobuf:"bytes,2,rep,name=smallBill" json:"smallBill,omitempty"`
}

func (m *GoldbillSliceBill) Reset()                    { *m = GoldbillSliceBill{} }
func (m *GoldbillSliceBill) String() string            { return proto.CompactTextString(m) }
func (*GoldbillSliceBill) ProtoMessage()               {}
func (*GoldbillSliceBill) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *GoldbillSliceBill) GetBigId() string {
	if m != nil {
		return m.BigId
	}
	return ""
}

func (m *GoldbillSliceBill) GetSmallBill() []*GoldbillSmall {
	if m != nil {
		return m.SmallBill
	}
	return nil
}

type GoldbillBatchRegUser struct {
	UserList []*GoldbillKeyUid `protobuf:"bytes,1,rep,name=userList" json:"userList,omitempty"`
}

func (m *GoldbillBatchRegUser) Reset()                    { *m = GoldbillBatchRegUser{} }
func (m *GoldbillBatchRegUser) String() string            { return proto.CompactTextString(m) }
func (*GoldbillBatchRegUser) ProtoMessage()               {}
func (*GoldbillBatchRegUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *GoldbillBatchRegUser) GetUserList() []*GoldbillKeyUid {
	if m != nil {
		return m.UserList
	}
	return nil
}

type GoldbillResponseInitPlatform struct {
	GoldbillPlatform *GoldbillPlatform `protobuf:"bytes,1,opt,name=goldbillPlatform" json:"goldbillPlatform,omitempty"`
}

func (m *GoldbillResponseInitPlatform) Reset()                    { *m = GoldbillResponseInitPlatform{} }
func (m *GoldbillResponseInitPlatform) String() string            { return proto.CompactTextString(m) }
func (*GoldbillResponseInitPlatform) ProtoMessage()               {}
func (*GoldbillResponseInitPlatform) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *GoldbillResponseInitPlatform) GetGoldbillPlatform() *GoldbillPlatform {
	if m != nil {
		return m.GoldbillPlatform
	}
	return nil
}

type GoldbillResponseRegisterUser struct {
	GoldbillUser *GoldbillUser `protobuf:"bytes,1,opt,name=goldbillUser" json:"goldbillUser,omitempty"`
}

func (m *GoldbillResponseRegisterUser) Reset()                    { *m = GoldbillResponseRegisterUser{} }
func (m *GoldbillResponseRegisterUser) String() string            { return proto.CompactTextString(m) }
func (*GoldbillResponseRegisterUser) ProtoMessage()               {}
func (*GoldbillResponseRegisterUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *GoldbillResponseRegisterUser) GetGoldbillUser() *GoldbillUser {
	if m != nil {
		return m.GoldbillUser
	}
	return nil
}

type GoldbillResponseSetFee struct {
	GoldbillPlatform *GoldbillPlatform `protobuf:"bytes,1,opt,name=goldbillPlatform" json:"goldbillPlatform,omitempty"`
}

func (m *GoldbillResponseSetFee) Reset()                    { *m = GoldbillResponseSetFee{} }
func (m *GoldbillResponseSetFee) String() string            { return proto.CompactTextString(m) }
func (*GoldbillResponseSetFee) ProtoMessage()               {}
func (*GoldbillResponseSetFee) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *GoldbillResponseSetFee) GetGoldbillPlatform() *GoldbillPlatform {
	if m != nil {
		return m.GoldbillPlatform
	}
	return nil
}

type GoldbillResponseSetStamps struct {
	GoldbillPlatform *GoldbillPlatform `protobuf:"bytes,1,opt,name=goldbillPlatform" json:"goldbillPlatform,omitempty"`
}

func (m *GoldbillResponseSetStamps) Reset()                    { *m = GoldbillResponseSetStamps{} }
func (m *GoldbillResponseSetStamps) String() string            { return proto.CompactTextString(m) }
func (*GoldbillResponseSetStamps) ProtoMessage()               {}
func (*GoldbillResponseSetStamps) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *GoldbillResponseSetStamps) GetGoldbillPlatform() *GoldbillPlatform {
	if m != nil {
		return m.GoldbillPlatform
	}
	return nil
}

type GoldbillResponseSetBail struct {
	GoldbillPlatform *GoldbillPlatform `protobuf:"bytes,1,opt,name=goldbillPlatform" json:"goldbillPlatform,omitempty"`
}

func (m *GoldbillResponseSetBail) Reset()                    { *m = GoldbillResponseSetBail{} }
func (m *GoldbillResponseSetBail) String() string            { return proto.CompactTextString(m) }
func (*GoldbillResponseSetBail) ProtoMessage()               {}
func (*GoldbillResponseSetBail) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *GoldbillResponseSetBail) GetGoldbillPlatform() *GoldbillPlatform {
	if m != nil {
		return m.GoldbillPlatform
	}
	return nil
}

type GoldbillResponseWithdraw struct {
	GoldbillPlatform *GoldbillPlatform `protobuf:"bytes,1,opt,name=goldbillPlatform" json:"goldbillPlatform,omitempty"`
	GoldbillUser     *GoldbillUser     `protobuf:"bytes,2,opt,name=goldbillUser" json:"goldbillUser,omitempty"`
}

func (m *GoldbillResponseWithdraw) Reset()                    { *m = GoldbillResponseWithdraw{} }
func (m *GoldbillResponseWithdraw) String() string            { return proto.CompactTextString(m) }
func (*GoldbillResponseWithdraw) ProtoMessage()               {}
func (*GoldbillResponseWithdraw) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *GoldbillResponseWithdraw) GetGoldbillPlatform() *GoldbillPlatform {
	if m != nil {
		return m.GoldbillPlatform
	}
	return nil
}

func (m *GoldbillResponseWithdraw) GetGoldbillUser() *GoldbillUser {
	if m != nil {
		return m.GoldbillUser
	}
	return nil
}

type GoldbillResponseDeposit struct {
	GoldbillPlatform *GoldbillPlatform `protobuf:"bytes,1,opt,name=goldbillPlatform" json:"goldbillPlatform,omitempty"`
	GoldbillUser     *GoldbillUser     `protobuf:"bytes,2,opt,name=goldbillUser" json:"goldbillUser,omitempty"`
}

func (m *GoldbillResponseDeposit) Reset()                    { *m = GoldbillResponseDeposit{} }
func (m *GoldbillResponseDeposit) String() string            { return proto.CompactTextString(m) }
func (*GoldbillResponseDeposit) ProtoMessage()               {}
func (*GoldbillResponseDeposit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *GoldbillResponseDeposit) GetGoldbillPlatform() *GoldbillPlatform {
	if m != nil {
		return m.GoldbillPlatform
	}
	return nil
}

func (m *GoldbillResponseDeposit) GetGoldbillUser() *GoldbillUser {
	if m != nil {
		return m.GoldbillUser
	}
	return nil
}

type GoldbillResponsePayKCoin struct {
	From *GoldbillUser `protobuf:"bytes,1,opt,name=from" json:"from,omitempty"`
	To   *GoldbillUser `protobuf:"bytes,2,opt,name=to" json:"to,omitempty"`
}

func (m *GoldbillResponsePayKCoin) Reset()                    { *m = GoldbillResponsePayKCoin{} }
func (m *GoldbillResponsePayKCoin) String() string            { return proto.CompactTextString(m) }
func (*GoldbillResponsePayKCoin) ProtoMessage()               {}
func (*GoldbillResponsePayKCoin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *GoldbillResponsePayKCoin) GetFrom() *GoldbillUser {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *GoldbillResponsePayKCoin) GetTo() *GoldbillUser {
	if m != nil {
		return m.To
	}
	return nil
}

type GoldbillResponseInvoice struct {
	InvoiceId string `protobuf:"bytes,1,opt,name=invoiceId" json:"invoiceId,omitempty"`
}

func (m *GoldbillResponseInvoice) Reset()                    { *m = GoldbillResponseInvoice{} }
func (m *GoldbillResponseInvoice) String() string            { return proto.CompactTextString(m) }
func (*GoldbillResponseInvoice) ProtoMessage()               {}
func (*GoldbillResponseInvoice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *GoldbillResponseInvoice) GetInvoiceId() string {
	if m != nil {
		return m.InvoiceId
	}
	return ""
}

type GoldbillResponseAddBill struct {
	BillList []string `protobuf:"bytes,1,rep,name=billList" json:"billList,omitempty"`
}

func (m *GoldbillResponseAddBill) Reset()                    { *m = GoldbillResponseAddBill{} }
func (m *GoldbillResponseAddBill) String() string            { return proto.CompactTextString(m) }
func (*GoldbillResponseAddBill) ProtoMessage()               {}
func (*GoldbillResponseAddBill) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *GoldbillResponseAddBill) GetBillList() []string {
	if m != nil {
		return m.BillList
	}
	return nil
}

type GoldbillResponseWithdrawKcoin struct {
	GoldbillPlatform *GoldbillPlatform `protobuf:"bytes,1,opt,name=goldbillPlatform" json:"goldbillPlatform,omitempty"`
	GoldbillUser     *GoldbillUser     `protobuf:"bytes,2,opt,name=goldbillUser" json:"goldbillUser,omitempty"`
}

func (m *GoldbillResponseWithdrawKcoin) Reset()                    { *m = GoldbillResponseWithdrawKcoin{} }
func (m *GoldbillResponseWithdrawKcoin) String() string            { return proto.CompactTextString(m) }
func (*GoldbillResponseWithdrawKcoin) ProtoMessage()               {}
func (*GoldbillResponseWithdrawKcoin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *GoldbillResponseWithdrawKcoin) GetGoldbillPlatform() *GoldbillPlatform {
	if m != nil {
		return m.GoldbillPlatform
	}
	return nil
}

func (m *GoldbillResponseWithdrawKcoin) GetGoldbillUser() *GoldbillUser {
	if m != nil {
		return m.GoldbillUser
	}
	return nil
}

type GoldbillResponseDepositKcoin struct {
	GoldbillPlatform *GoldbillPlatform `protobuf:"bytes,1,opt,name=goldbillPlatform" json:"goldbillPlatform,omitempty"`
	GoldbillUser     *GoldbillUser     `protobuf:"bytes,2,opt,name=goldbillUser" json:"goldbillUser,omitempty"`
}

func (m *GoldbillResponseDepositKcoin) Reset()                    { *m = GoldbillResponseDepositKcoin{} }
func (m *GoldbillResponseDepositKcoin) String() string            { return proto.CompactTextString(m) }
func (*GoldbillResponseDepositKcoin) ProtoMessage()               {}
func (*GoldbillResponseDepositKcoin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *GoldbillResponseDepositKcoin) GetGoldbillPlatform() *GoldbillPlatform {
	if m != nil {
		return m.GoldbillPlatform
	}
	return nil
}

func (m *GoldbillResponseDepositKcoin) GetGoldbillUser() *GoldbillUser {
	if m != nil {
		return m.GoldbillUser
	}
	return nil
}

type GoldbillResponseBatchSell struct {
	SellList []string `protobuf:"bytes,1,rep,name=sellList" json:"sellList,omitempty"`
}

func (m *GoldbillResponseBatchSell) Reset()                    { *m = GoldbillResponseBatchSell{} }
func (m *GoldbillResponseBatchSell) String() string            { return proto.CompactTextString(m) }
func (*GoldbillResponseBatchSell) ProtoMessage()               {}
func (*GoldbillResponseBatchSell) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

func (m *GoldbillResponseBatchSell) GetSellList() []string {
	if m != nil {
		return m.SellList
	}
	return nil
}

type GoldbillResponseBatchCancelSell struct {
	CancelList []string `protobuf:"bytes,1,rep,name=cancelList" json:"cancelList,omitempty"`
}

func (m *GoldbillResponseBatchCancelSell) Reset()         { *m = GoldbillResponseBatchCancelSell{} }
func (m *GoldbillResponseBatchCancelSell) String() string { return proto.CompactTextString(m) }
func (*GoldbillResponseBatchCancelSell) ProtoMessage()    {}
func (*GoldbillResponseBatchCancelSell) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{33}
}

func (m *GoldbillResponseBatchCancelSell) GetCancelList() []string {
	if m != nil {
		return m.CancelList
	}
	return nil
}

type GoldbillResponseBatchBuy struct {
	BuyList []string `protobuf:"bytes,1,rep,name=buyList" json:"buyList,omitempty"`
}

func (m *GoldbillResponseBatchBuy) Reset()                    { *m = GoldbillResponseBatchBuy{} }
func (m *GoldbillResponseBatchBuy) String() string            { return proto.CompactTextString(m) }
func (*GoldbillResponseBatchBuy) ProtoMessage()               {}
func (*GoldbillResponseBatchBuy) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

func (m *GoldbillResponseBatchBuy) GetBuyList() []string {
	if m != nil {
		return m.BuyList
	}
	return nil
}

type GoldbillResponseBatchPay struct {
	From     *GoldbillUser `protobuf:"bytes,1,opt,name=from" json:"from,omitempty"`
	BillList []string      `protobuf:"bytes,2,rep,name=billList" json:"billList,omitempty"`
}

func (m *GoldbillResponseBatchPay) Reset()                    { *m = GoldbillResponseBatchPay{} }
func (m *GoldbillResponseBatchPay) String() string            { return proto.CompactTextString(m) }
func (*GoldbillResponseBatchPay) ProtoMessage()               {}
func (*GoldbillResponseBatchPay) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

func (m *GoldbillResponseBatchPay) GetFrom() *GoldbillUser {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *GoldbillResponseBatchPay) GetBillList() []string {
	if m != nil {
		return m.BillList
	}
	return nil
}

type GoldbillResponseSliceBill struct {
	OldBill *GoldbillDetail   `protobuf:"bytes,1,opt,name=oldBill" json:"oldBill,omitempty"`
	NewBill []*GoldbillDetail `protobuf:"bytes,2,rep,name=newBill" json:"newBill,omitempty"`
}

func (m *GoldbillResponseSliceBill) Reset()                    { *m = GoldbillResponseSliceBill{} }
func (m *GoldbillResponseSliceBill) String() string            { return proto.CompactTextString(m) }
func (*GoldbillResponseSliceBill) ProtoMessage()               {}
func (*GoldbillResponseSliceBill) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{36} }

func (m *GoldbillResponseSliceBill) GetOldBill() *GoldbillDetail {
	if m != nil {
		return m.OldBill
	}
	return nil
}

func (m *GoldbillResponseSliceBill) GetNewBill() []*GoldbillDetail {
	if m != nil {
		return m.NewBill
	}
	return nil
}

type GoldbillResponseBatchTakeOut struct {
	BillId []string `protobuf:"bytes,1,rep,name=billId" json:"billId,omitempty"`
}

func (m *GoldbillResponseBatchTakeOut) Reset()                    { *m = GoldbillResponseBatchTakeOut{} }
func (m *GoldbillResponseBatchTakeOut) String() string            { return proto.CompactTextString(m) }
func (*GoldbillResponseBatchTakeOut) ProtoMessage()               {}
func (*GoldbillResponseBatchTakeOut) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{37} }

func (m *GoldbillResponseBatchTakeOut) GetBillId() []string {
	if m != nil {
		return m.BillId
	}
	return nil
}

type GoldbillResponseBatchRegUser struct {
	Succ []string `protobuf:"bytes,1,rep,name=succ" json:"succ,omitempty"`
	Fail []string `protobuf:"bytes,2,rep,name=fail" json:"fail,omitempty"`
}

func (m *GoldbillResponseBatchRegUser) Reset()                    { *m = GoldbillResponseBatchRegUser{} }
func (m *GoldbillResponseBatchRegUser) String() string            { return proto.CompactTextString(m) }
func (*GoldbillResponseBatchRegUser) ProtoMessage()               {}
func (*GoldbillResponseBatchRegUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{38} }

func (m *GoldbillResponseBatchRegUser) GetSucc() []string {
	if m != nil {
		return m.Succ
	}
	return nil
}

func (m *GoldbillResponseBatchRegUser) GetFail() []string {
	if m != nil {
		return m.Fail
	}
	return nil
}

type GoldbillPlatform struct {
	Pubkey       []byte   `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Info         string   `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
	FeeAmount    int64    `protobuf:"varint,3,opt,name=feeAmount" json:"feeAmount,omitempty"`
	Fee          int64    `protobuf:"varint,4,opt,name=fee" json:"fee,omitempty"`
	StampsAmount int64    `protobuf:"varint,5,opt,name=stampsAmount" json:"stampsAmount,omitempty"`
	Stamps       int64    `protobuf:"varint,6,opt,name=stamps" json:"stamps,omitempty"`
	BailAmount   int64    `protobuf:"varint,7,opt,name=bailAmount" json:"bailAmount,omitempty"`
	Bail         int64    `protobuf:"varint,8,opt,name=bail" json:"bail,omitempty"`
	SellList     []string `protobuf:"bytes,9,rep,name=sellList" json:"sellList,omitempty"`
	PledgeAmount int64    `protobuf:"varint,10,opt,name=pledgeAmount" json:"pledgeAmount,omitempty"`
	Rmb          int64    `protobuf:"varint,11,opt,name=rmb" json:"rmb,omitempty"`
	Kcoin        int64    `protobuf:"varint,12,opt,name=kcoin" json:"kcoin,omitempty"`
	Rate         int64    `protobuf:"varint,13,opt,name=rate" json:"rate,omitempty"`
}

func (m *GoldbillPlatform) Reset()                    { *m = GoldbillPlatform{} }
func (m *GoldbillPlatform) String() string            { return proto.CompactTextString(m) }
func (*GoldbillPlatform) ProtoMessage()               {}
func (*GoldbillPlatform) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{39} }

func (m *GoldbillPlatform) GetPubkey() []byte {
	if m != nil {
		return m.Pubkey
	}
	return nil
}

func (m *GoldbillPlatform) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func (m *GoldbillPlatform) GetFeeAmount() int64 {
	if m != nil {
		return m.FeeAmount
	}
	return 0
}

func (m *GoldbillPlatform) GetFee() int64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *GoldbillPlatform) GetStampsAmount() int64 {
	if m != nil {
		return m.StampsAmount
	}
	return 0
}

func (m *GoldbillPlatform) GetStamps() int64 {
	if m != nil {
		return m.Stamps
	}
	return 0
}

func (m *GoldbillPlatform) GetBailAmount() int64 {
	if m != nil {
		return m.BailAmount
	}
	return 0
}

func (m *GoldbillPlatform) GetBail() int64 {
	if m != nil {
		return m.Bail
	}
	return 0
}

func (m *GoldbillPlatform) GetSellList() []string {
	if m != nil {
		return m.SellList
	}
	return nil
}

func (m *GoldbillPlatform) GetPledgeAmount() int64 {
	if m != nil {
		return m.PledgeAmount
	}
	return 0
}

func (m *GoldbillPlatform) GetRmb() int64 {
	if m != nil {
		return m.Rmb
	}
	return 0
}

func (m *GoldbillPlatform) GetKcoin() int64 {
	if m != nil {
		return m.Kcoin
	}
	return 0
}

func (m *GoldbillPlatform) GetRate() int64 {
	if m != nil {
		return m.Rate
	}
	return 0
}

type GoldbillUser struct {
	Uid    string           `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
	Rmb    int64            `protobuf:"varint,2,opt,name=rmb" json:"rmb,omitempty"`
	Frozen int64            `protobuf:"varint,3,opt,name=frozen" json:"frozen,omitempty"`
	Kcoin  int64            `protobuf:"varint,4,opt,name=kcoin" json:"kcoin,omitempty"`
	Name   string           `protobuf:"bytes,5,opt,name=name" json:"name,omitempty"`
	Phone  int64            `protobuf:"varint,6,opt,name=phone" json:"phone,omitempty"`
	Mail   string           `protobuf:"bytes,7,opt,name=mail" json:"mail,omitempty"`
	WrList []string         `protobuf:"bytes,8,rep,name=wrList" json:"wrList,omitempty"`
	Pubkey []byte           `protobuf:"bytes,9,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Type   GoldbillUserType `protobuf:"varint,10,opt,name=type,enum=goldbill.GoldbillUserType" json:"type,omitempty"`
}

func (m *GoldbillUser) Reset()                    { *m = GoldbillUser{} }
func (m *GoldbillUser) String() string            { return proto.CompactTextString(m) }
func (*GoldbillUser) ProtoMessage()               {}
func (*GoldbillUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{40} }

func (m *GoldbillUser) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *GoldbillUser) GetRmb() int64 {
	if m != nil {
		return m.Rmb
	}
	return 0
}

func (m *GoldbillUser) GetFrozen() int64 {
	if m != nil {
		return m.Frozen
	}
	return 0
}

func (m *GoldbillUser) GetKcoin() int64 {
	if m != nil {
		return m.Kcoin
	}
	return 0
}

func (m *GoldbillUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GoldbillUser) GetPhone() int64 {
	if m != nil {
		return m.Phone
	}
	return 0
}

func (m *GoldbillUser) GetMail() string {
	if m != nil {
		return m.Mail
	}
	return ""
}

func (m *GoldbillUser) GetWrList() []string {
	if m != nil {
		return m.WrList
	}
	return nil
}

func (m *GoldbillUser) GetPubkey() []byte {
	if m != nil {
		return m.Pubkey
	}
	return nil
}

func (m *GoldbillUser) GetType() GoldbillUserType {
	if m != nil {
		return m.Type
	}
	return GoldbillUserType_UT_UNKNOWN
}

type GoldbillAdmin struct {
	Uid    string `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
	Pubkey []byte `protobuf:"bytes,2,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
}

func (m *GoldbillAdmin) Reset()                    { *m = GoldbillAdmin{} }
func (m *GoldbillAdmin) String() string            { return proto.CompactTextString(m) }
func (*GoldbillAdmin) ProtoMessage()               {}
func (*GoldbillAdmin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{41} }

func (m *GoldbillAdmin) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *GoldbillAdmin) GetPubkey() []byte {
	if m != nil {
		return m.Pubkey
	}
	return nil
}

type GoldbillKeyUid struct {
	Uid    string `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
	Pubkey []byte `protobuf:"bytes,2,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
}

func (m *GoldbillKeyUid) Reset()                    { *m = GoldbillKeyUid{} }
func (m *GoldbillKeyUid) String() string            { return proto.CompactTextString(m) }
func (*GoldbillKeyUid) ProtoMessage()               {}
func (*GoldbillKeyUid) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{42} }

func (m *GoldbillKeyUid) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *GoldbillKeyUid) GetPubkey() []byte {
	if m != nil {
		return m.Pubkey
	}
	return nil
}

type GoldbillPickUp struct {
	Phone int64 `protobuf:"varint,1,opt,name=phone" json:"phone,omitempty"`
}

func (m *GoldbillPickUp) Reset()                    { *m = GoldbillPickUp{} }
func (m *GoldbillPickUp) String() string            { return proto.CompactTextString(m) }
func (*GoldbillPickUp) ProtoMessage()               {}
func (*GoldbillPickUp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{43} }

func (m *GoldbillPickUp) GetPhone() int64 {
	if m != nil {
		return m.Phone
	}
	return 0
}

type GoldbillTakeDelivery struct {
	Receiver        string                  `protobuf:"bytes,1,opt,name=receiver" json:"receiver,omitempty"`
	ReceiveAddr     string                  `protobuf:"bytes,2,opt,name=receiveAddr" json:"receiveAddr,omitempty"`
	Contract        string                  `protobuf:"bytes,3,opt,name=contract" json:"contract,omitempty"`
	DeliveryFeeType GoldbillDeliveryFeeType `protobuf:"varint,4,opt,name=deliveryFeeType,enum=goldbill.GoldbillDeliveryFeeType" json:"deliveryFeeType,omitempty"`
}

func (m *GoldbillTakeDelivery) Reset()                    { *m = GoldbillTakeDelivery{} }
func (m *GoldbillTakeDelivery) String() string            { return proto.CompactTextString(m) }
func (*GoldbillTakeDelivery) ProtoMessage()               {}
func (*GoldbillTakeDelivery) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{44} }

func (m *GoldbillTakeDelivery) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *GoldbillTakeDelivery) GetReceiveAddr() string {
	if m != nil {
		return m.ReceiveAddr
	}
	return ""
}

func (m *GoldbillTakeDelivery) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *GoldbillTakeDelivery) GetDeliveryFeeType() GoldbillDeliveryFeeType {
	if m != nil {
		return m.DeliveryFeeType
	}
	return GoldbillDeliveryFeeType_DFT_UNKNOWN
}

type GoldbillDetail struct {
	BillId       string        `protobuf:"bytes,1,opt,name=billId" json:"billId,omitempty"`
	BillType     string        `protobuf:"bytes,2,opt,name=billType" json:"billType,omitempty"`
	BillName     string        `protobuf:"bytes,3,opt,name=billName" json:"billName,omitempty"`
	BillBand     string        `protobuf:"bytes,4,opt,name=billBand" json:"billBand,omitempty"`
	BillStand    string        `protobuf:"bytes,5,opt,name=billStand" json:"billStand,omitempty"`
	BillPack     string        `protobuf:"bytes,6,opt,name=billPack" json:"billPack,omitempty"`
	BillNum      int64         `protobuf:"varint,7,opt,name=billNum" json:"billNum,omitempty"`
	BillPrice    int64         `protobuf:"varint,8,opt,name=billPrice" json:"billPrice,omitempty"`
	BillState    GoldbillState `protobuf:"varint,9,opt,name=billState,enum=goldbill.GoldbillState" json:"billState,omitempty"`
	Amount       int64         `protobuf:"varint,10,opt,name=amount" json:"amount,omitempty"`
	PledgeAmount int64         `protobuf:"varint,11,opt,name=pledgeAmount" json:"pledgeAmount,omitempty"`
	Oid          string        `protobuf:"bytes,12,opt,name=oid" json:"oid,omitempty"`
	Pubkey       []byte        `protobuf:"bytes,13,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	IsPledge     bool          `protobuf:"varint,14,opt,name=isPledge" json:"isPledge,omitempty"`
	WarName      string        `protobuf:"bytes,15,opt,name=warName" json:"warName,omitempty"`
	CreateMan    string        `protobuf:"bytes,16,opt,name=createMan" json:"createMan,omitempty"`
	EditMan      string        `protobuf:"bytes,17,opt,name=editMan" json:"editMan,omitempty"`
	AuditMan     string        `protobuf:"bytes,18,opt,name=auditMan" json:"auditMan,omitempty"`
	WriteMan     string        `protobuf:"bytes,19,opt,name=writeMan" json:"writeMan,omitempty"`
}

func (m *GoldbillDetail) Reset()                    { *m = GoldbillDetail{} }
func (m *GoldbillDetail) String() string            { return proto.CompactTextString(m) }
func (*GoldbillDetail) ProtoMessage()               {}
func (*GoldbillDetail) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{45} }

func (m *GoldbillDetail) GetBillId() string {
	if m != nil {
		return m.BillId
	}
	return ""
}

func (m *GoldbillDetail) GetBillType() string {
	if m != nil {
		return m.BillType
	}
	return ""
}

func (m *GoldbillDetail) GetBillName() string {
	if m != nil {
		return m.BillName
	}
	return ""
}

func (m *GoldbillDetail) GetBillBand() string {
	if m != nil {
		return m.BillBand
	}
	return ""
}

func (m *GoldbillDetail) GetBillStand() string {
	if m != nil {
		return m.BillStand
	}
	return ""
}

func (m *GoldbillDetail) GetBillPack() string {
	if m != nil {
		return m.BillPack
	}
	return ""
}

func (m *GoldbillDetail) GetBillNum() int64 {
	if m != nil {
		return m.BillNum
	}
	return 0
}

func (m *GoldbillDetail) GetBillPrice() int64 {
	if m != nil {
		return m.BillPrice
	}
	return 0
}

func (m *GoldbillDetail) GetBillState() GoldbillState {
	if m != nil {
		return m.BillState
	}
	return GoldbillState_BS_UNKNOWN
}

func (m *GoldbillDetail) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *GoldbillDetail) GetPledgeAmount() int64 {
	if m != nil {
		return m.PledgeAmount
	}
	return 0
}

func (m *GoldbillDetail) GetOid() string {
	if m != nil {
		return m.Oid
	}
	return ""
}

func (m *GoldbillDetail) GetPubkey() []byte {
	if m != nil {
		return m.Pubkey
	}
	return nil
}

func (m *GoldbillDetail) GetIsPledge() bool {
	if m != nil {
		return m.IsPledge
	}
	return false
}

func (m *GoldbillDetail) GetWarName() string {
	if m != nil {
		return m.WarName
	}
	return ""
}

func (m *GoldbillDetail) GetCreateMan() string {
	if m != nil {
		return m.CreateMan
	}
	return ""
}

func (m *GoldbillDetail) GetEditMan() string {
	if m != nil {
		return m.EditMan
	}
	return ""
}

func (m *GoldbillDetail) GetAuditMan() string {
	if m != nil {
		return m.AuditMan
	}
	return ""
}

func (m *GoldbillDetail) GetWriteMan() string {
	if m != nil {
		return m.WriteMan
	}
	return ""
}

type GoldbillCommonInvoice struct {
	Company string `protobuf:"bytes,1,opt,name=company" json:"company,omitempty"`
	TaxNo   string `protobuf:"bytes,2,opt,name=taxNo" json:"taxNo,omitempty"`
}

func (m *GoldbillCommonInvoice) Reset()                    { *m = GoldbillCommonInvoice{} }
func (m *GoldbillCommonInvoice) String() string            { return proto.CompactTextString(m) }
func (*GoldbillCommonInvoice) ProtoMessage()               {}
func (*GoldbillCommonInvoice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{46} }

func (m *GoldbillCommonInvoice) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func (m *GoldbillCommonInvoice) GetTaxNo() string {
	if m != nil {
		return m.TaxNo
	}
	return ""
}

type GoldbillVATInvoice struct {
	Company     string `protobuf:"bytes,1,opt,name=company" json:"company,omitempty"`
	TaxNo       string `protobuf:"bytes,2,opt,name=taxNo" json:"taxNo,omitempty"`
	Bank        string `protobuf:"bytes,3,opt,name=bank" json:"bank,omitempty"`
	BankAccount string `protobuf:"bytes,4,opt,name=bankAccount" json:"bankAccount,omitempty"`
	Address     string `protobuf:"bytes,5,opt,name=address" json:"address,omitempty"`
	Contract    string `protobuf:"bytes,6,opt,name=contract" json:"contract,omitempty"`
}

func (m *GoldbillVATInvoice) Reset()                    { *m = GoldbillVATInvoice{} }
func (m *GoldbillVATInvoice) String() string            { return proto.CompactTextString(m) }
func (*GoldbillVATInvoice) ProtoMessage()               {}
func (*GoldbillVATInvoice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{47} }

func (m *GoldbillVATInvoice) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func (m *GoldbillVATInvoice) GetTaxNo() string {
	if m != nil {
		return m.TaxNo
	}
	return ""
}

func (m *GoldbillVATInvoice) GetBank() string {
	if m != nil {
		return m.Bank
	}
	return ""
}

func (m *GoldbillVATInvoice) GetBankAccount() string {
	if m != nil {
		return m.BankAccount
	}
	return ""
}

func (m *GoldbillVATInvoice) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *GoldbillVATInvoice) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

type GoldbillBatchSellList struct {
	Uid    string `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
	BillId string `protobuf:"bytes,2,opt,name=billId" json:"billId,omitempty"`
}

func (m *GoldbillBatchSellList) Reset()                    { *m = GoldbillBatchSellList{} }
func (m *GoldbillBatchSellList) String() string            { return proto.CompactTextString(m) }
func (*GoldbillBatchSellList) ProtoMessage()               {}
func (*GoldbillBatchSellList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{48} }

func (m *GoldbillBatchSellList) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *GoldbillBatchSellList) GetBillId() string {
	if m != nil {
		return m.BillId
	}
	return ""
}

type GoldbillPayTo struct {
	BillId string `protobuf:"bytes,1,opt,name=billId" json:"billId,omitempty"`
	Toid   string `protobuf:"bytes,2,opt,name=toid" json:"toid,omitempty"`
	Toaddr []byte `protobuf:"bytes,3,opt,name=toaddr,proto3" json:"toaddr,omitempty"`
}

func (m *GoldbillPayTo) Reset()                    { *m = GoldbillPayTo{} }
func (m *GoldbillPayTo) String() string            { return proto.CompactTextString(m) }
func (*GoldbillPayTo) ProtoMessage()               {}
func (*GoldbillPayTo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{49} }

func (m *GoldbillPayTo) GetBillId() string {
	if m != nil {
		return m.BillId
	}
	return ""
}

func (m *GoldbillPayTo) GetToid() string {
	if m != nil {
		return m.Toid
	}
	return ""
}

func (m *GoldbillPayTo) GetToaddr() []byte {
	if m != nil {
		return m.Toaddr
	}
	return nil
}

type GoldbillSmall struct {
	BillId  string `protobuf:"bytes,1,opt,name=billId" json:"billId,omitempty"`
	BillNum int64  `protobuf:"varint,2,opt,name=billNum" json:"billNum,omitempty"`
}

func (m *GoldbillSmall) Reset()                    { *m = GoldbillSmall{} }
func (m *GoldbillSmall) String() string            { return proto.CompactTextString(m) }
func (*GoldbillSmall) ProtoMessage()               {}
func (*GoldbillSmall) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{50} }

func (m *GoldbillSmall) GetBillId() string {
	if m != nil {
		return m.BillId
	}
	return ""
}

func (m *GoldbillSmall) GetBillNum() int64 {
	if m != nil {
		return m.BillNum
	}
	return 0
}

type GoldbillUserState struct {
	Usernum  int64 `protobuf:"varint,1,opt,name=usernum" json:"usernum,omitempty"`
	Adminnum int64 `protobuf:"varint,2,opt,name=adminnum" json:"adminnum,omitempty"`
}

func (m *GoldbillUserState) Reset()                    { *m = GoldbillUserState{} }
func (m *GoldbillUserState) String() string            { return proto.CompactTextString(m) }
func (*GoldbillUserState) ProtoMessage()               {}
func (*GoldbillUserState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{51} }

func (m *GoldbillUserState) GetUsernum() int64 {
	if m != nil {
		return m.Usernum
	}
	return 0
}

func (m *GoldbillUserState) GetAdminnum() int64 {
	if m != nil {
		return m.Adminnum
	}
	return 0
}

func init() {
	proto.RegisterType((*GoldbillAction)(nil), "goldbill.GoldbillAction")
	proto.RegisterType((*GoldbillInitPlatform)(nil), "goldbill.GoldbillInitPlatform")
	proto.RegisterType((*GoldbillRegisterUser)(nil), "goldbill.GoldbillRegisterUser")
	proto.RegisterType((*GoldbillSetFee)(nil), "goldbill.GoldbillSetFee")
	proto.RegisterType((*GoldbillSetStamps)(nil), "goldbill.GoldbillSetStamps")
	proto.RegisterType((*GoldbillSetBail)(nil), "goldbill.GoldbillSetBail")
	proto.RegisterType((*GoldbillWithdraw)(nil), "goldbill.GoldbillWithdraw")
	proto.RegisterType((*GoldbillDeposit)(nil), "goldbill.GoldbillDeposit")
	proto.RegisterType((*GoldbillPayKCoin)(nil), "goldbill.GoldbillPayKCoin")
	proto.RegisterType((*GoldbillInvoice)(nil), "goldbill.GoldbillInvoice")
	proto.RegisterType((*GoldbillAddBill)(nil), "goldbill.GoldbillAddBill")
	proto.RegisterType((*GoldbillWithdrawKcoin)(nil), "goldbill.GoldbillWithdrawKcoin")
	proto.RegisterType((*GoldbillDepositKcoin)(nil), "goldbill.GoldbillDepositKcoin")
	proto.RegisterType((*GoldbillBatchSell)(nil), "goldbill.GoldbillBatchSell")
	proto.RegisterType((*GoldbillBatchCancelSell)(nil), "goldbill.GoldbillBatchCancelSell")
	proto.RegisterType((*GoldbillBatchBuy)(nil), "goldbill.GoldbillBatchBuy")
	proto.RegisterType((*GoldbillBatchPay)(nil), "goldbill.GoldbillBatchPay")
	proto.RegisterType((*GoldbillBatchTakeOut)(nil), "goldbill.GoldbillBatchTakeOut")
	proto.RegisterType((*GoldbillSliceBill)(nil), "goldbill.GoldbillSliceBill")
	proto.RegisterType((*GoldbillBatchRegUser)(nil), "goldbill.GoldbillBatchRegUser")
	proto.RegisterType((*GoldbillResponseInitPlatform)(nil), "goldbill.GoldbillResponseInitPlatform")
	proto.RegisterType((*GoldbillResponseRegisterUser)(nil), "goldbill.GoldbillResponseRegisterUser")
	proto.RegisterType((*GoldbillResponseSetFee)(nil), "goldbill.GoldbillResponseSetFee")
	proto.RegisterType((*GoldbillResponseSetStamps)(nil), "goldbill.GoldbillResponseSetStamps")
	proto.RegisterType((*GoldbillResponseSetBail)(nil), "goldbill.GoldbillResponseSetBail")
	proto.RegisterType((*GoldbillResponseWithdraw)(nil), "goldbill.GoldbillResponseWithdraw")
	proto.RegisterType((*GoldbillResponseDeposit)(nil), "goldbill.GoldbillResponseDeposit")
	proto.RegisterType((*GoldbillResponsePayKCoin)(nil), "goldbill.GoldbillResponsePayKCoin")
	proto.RegisterType((*GoldbillResponseInvoice)(nil), "goldbill.GoldbillResponseInvoice")
	proto.RegisterType((*GoldbillResponseAddBill)(nil), "goldbill.GoldbillResponseAddBill")
	proto.RegisterType((*GoldbillResponseWithdrawKcoin)(nil), "goldbill.GoldbillResponseWithdrawKcoin")
	proto.RegisterType((*GoldbillResponseDepositKcoin)(nil), "goldbill.GoldbillResponseDepositKcoin")
	proto.RegisterType((*GoldbillResponseBatchSell)(nil), "goldbill.GoldbillResponseBatchSell")
	proto.RegisterType((*GoldbillResponseBatchCancelSell)(nil), "goldbill.GoldbillResponseBatchCancelSell")
	proto.RegisterType((*GoldbillResponseBatchBuy)(nil), "goldbill.GoldbillResponseBatchBuy")
	proto.RegisterType((*GoldbillResponseBatchPay)(nil), "goldbill.GoldbillResponseBatchPay")
	proto.RegisterType((*GoldbillResponseSliceBill)(nil), "goldbill.GoldbillResponseSliceBill")
	proto.RegisterType((*GoldbillResponseBatchTakeOut)(nil), "goldbill.GoldbillResponseBatchTakeOut")
	proto.RegisterType((*GoldbillResponseBatchRegUser)(nil), "goldbill.GoldbillResponseBatchRegUser")
	proto.RegisterType((*GoldbillPlatform)(nil), "goldbill.GoldbillPlatform")
	proto.RegisterType((*GoldbillUser)(nil), "goldbill.GoldbillUser")
	proto.RegisterType((*GoldbillAdmin)(nil), "goldbill.GoldbillAdmin")
	proto.RegisterType((*GoldbillKeyUid)(nil), "goldbill.GoldbillKeyUid")
	proto.RegisterType((*GoldbillPickUp)(nil), "goldbill.GoldbillPickUp")
	proto.RegisterType((*GoldbillTakeDelivery)(nil), "goldbill.GoldbillTakeDelivery")
	proto.RegisterType((*GoldbillDetail)(nil), "goldbill.GoldbillDetail")
	proto.RegisterType((*GoldbillCommonInvoice)(nil), "goldbill.GoldbillCommonInvoice")
	proto.RegisterType((*GoldbillVATInvoice)(nil), "goldbill.GoldbillVATInvoice")
	proto.RegisterType((*GoldbillBatchSellList)(nil), "goldbill.GoldbillBatchSellList")
	proto.RegisterType((*GoldbillPayTo)(nil), "goldbill.GoldbillPayTo")
	proto.RegisterType((*GoldbillSmall)(nil), "goldbill.GoldbillSmall")
	proto.RegisterType((*GoldbillUserState)(nil), "goldbill.GoldbillUserState")
	proto.RegisterEnum("goldbill.GoldbillActionType", GoldbillActionType_name, GoldbillActionType_value)
	proto.RegisterEnum("goldbill.GoldbillUserType", GoldbillUserType_name, GoldbillUserType_value)
	proto.RegisterEnum("goldbill.GoldbillTakeOutType", GoldbillTakeOutType_name, GoldbillTakeOutType_value)
	proto.RegisterEnum("goldbill.GoldbillDeliveryFeeType", GoldbillDeliveryFeeType_name, GoldbillDeliveryFeeType_value)
	proto.RegisterEnum("goldbill.GoldbillState", GoldbillState_name, GoldbillState_value)
	proto.RegisterEnum("goldbill.GoldbillInvoiceType", GoldbillInvoiceType_name, GoldbillInvoiceType_value)
}

func init() { proto.RegisterFile("goldbill.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 2295 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x59, 0xdd, 0x72, 0xe3, 0x48,
	0x15, 0x8e, 0x64, 0xc7, 0x3f, 0xc7, 0x8e, 0xa3, 0xe9, 0x19, 0x66, 0xbd, 0xc3, 0xec, 0x6c, 0x56,
	0x14, 0x5b, 0x43, 0x80, 0x14, 0x15, 0x76, 0x76, 0x61, 0x61, 0x8b, 0xb2, 0x13, 0x67, 0x62, 0xf2,
	0xe7, 0x52, 0x9c, 0x59, 0x76, 0x6f, 0xb2, 0x8a, 0xdc, 0xf1, 0xa8, 0x62, 0x4b, 0x2e, 0x49, 0x9e,
	0x60, 0x6e, 0xa9, 0xe2, 0x9a, 0x17, 0x80, 0x0b, 0x78, 0x01, 0x78, 0x00, 0x9e, 0x83, 0x2a, 0xee,
	0xb9, 0xe3, 0x19, 0x28, 0xea, 0xf4, 0x8f, 0xba, 0x65, 0x4b, 0x19, 0x66, 0x6b, 0x2e, 0xe6, 0xca,
	0x7d, 0x5a, 0xdf, 0xf9, 0xe9, 0xee, 0xd3, 0xe7, 0xa7, 0x0d, 0xad, 0x71, 0x38, 0x19, 0x5d, 0xf9,
	0x93, 0xc9, 0xce, 0x2c, 0x0a, 0x93, 0x90, 0xd4, 0x24, 0x6d, 0xff, 0xa7, 0x0e, 0xad, 0xe7, 0x82,
	0xe8, 0x78, 0x89, 0x1f, 0x06, 0x64, 0x1f, 0x9a, 0x7e, 0xe0, 0x27, 0x83, 0x89, 0x9b, 0x5c, 0x87,
	0xd1, 0xb4, 0x6d, 0x6c, 0x19, 0x4f, 0x1b, 0xbb, 0x4f, 0x76, 0x52, 0x19, 0x12, 0xdf, 0xd7, 0x50,
	0x87, 0x6b, 0x4e, 0x86, 0x0b, 0xa5, 0x44, 0x74, 0xec, 0xc7, 0x09, 0x8d, 0x2e, 0x62, 0x1a, 0xb5,
	0xcd, 0x22, 0x29, 0x8e, 0x86, 0x42, 0x29, 0x3a, 0x17, 0xd9, 0x85, 0x4a, 0x4c, 0x93, 0x03, 0x4a,
	0xdb, 0x25, 0xc6, 0xdf, 0x5e, 0xe5, 0x3f, 0x67, 0xdf, 0x0f, 0xd7, 0x1c, 0x81, 0x24, 0xbf, 0x80,
	0x7a, 0x4c, 0x93, 0xf3, 0xc4, 0x9d, 0xce, 0xe2, 0x76, 0x99, 0xb1, 0x7d, 0x37, 0x97, 0x8d, 0x43,
	0x0e, 0xd7, 0x1c, 0x85, 0x27, 0xcf, 0xa0, 0x1a, 0xd3, 0xa4, 0xeb, 0xfa, 0x93, 0xf6, 0x3a, 0x63,
	0x7d, 0x3f, 0x97, 0x15, 0x01, 0x87, 0x6b, 0x8e, 0xc4, 0x92, 0x9f, 0x41, 0xed, 0xd6, 0x4f, 0x5e,
	0x8e, 0x22, 0xf7, 0xb6, 0x5d, 0x61, 0x7c, 0x8f, 0x56, 0xf9, 0xbe, 0x14, 0x88, 0xc3, 0x35, 0x27,
	0x45, 0xa3, 0xc2, 0x11, 0x9d, 0x85, 0xb1, 0x9f, 0xb4, 0xab, 0x45, 0x0a, 0xf7, 0x39, 0x00, 0x15,
	0x0a, 0x2c, 0x79, 0x0e, 0x1b, 0x52, 0xc4, 0x91, 0x17, 0xfa, 0x41, 0xbb, 0xc6, 0x98, 0x3f, 0x2c,
	0xd6, 0xca, 0x60, 0x87, 0x6b, 0x4e, 0x96, 0x0f, 0xcf, 0x49, 0xc8, 0xe4, 0x72, 0xea, 0x45, 0xe7,
	0xb4, 0xaf, 0xa1, 0xf0, 0x9c, 0x74, 0x2e, 0x5c, 0xff, 0xcc, 0x5d, 0x1c, 0xed, 0xa1, 0x04, 0x28,
	0x5a, 0xff, 0x40, 0x20, 0x70, 0xfd, 0x12, 0x8d, 0xeb, 0xf7, 0x83, 0x57, 0xa1, 0xef, 0xd1, 0x76,
	0xa3, 0x68, 0xfd, 0x7d, 0x0e, 0xc0, 0xf5, 0x0b, 0x2c, 0xb2, 0xb9, 0xa3, 0x51, 0xd7, 0x9f, 0x4c,
	0xda, 0xcd, 0x22, 0xb6, 0x0e, 0x07, 0x20, 0x9b, 0xc0, 0xa2, 0x6f, 0x5c, 0xb9, 0x89, 0xf7, 0xf2,
	0x9c, 0x4e, 0x26, 0xed, 0x8d, 0x22, 0xdf, 0xe8, 0x4a, 0x08, 0xfa, 0x46, 0x8a, 0x27, 0x27, 0xb0,
	0xc9, 0x88, 0x3d, 0x37, 0xf0, 0xe8, 0x84, 0x89, 0x68, 0x31, 0x11, 0x1f, 0x15, 0x88, 0x50, 0xc0,
	0xc3, 0x35, 0x67, 0x99, 0x17, 0xf7, 0x8c, 0x4d, 0x75, 0xe7, 0x8b, 0xf6, 0x66, 0xd1, 0x9e, 0x75,
	0x05, 0x02, 0xf7, 0x4c, 0xa2, 0x53, 0xce, 0x81, 0xbb, 0x68, 0x5b, 0x77, 0x72, 0x0e, 0x5c, 0xc5,
	0x39, 0x70, 0x17, 0x78, 0xda, 0x6c, 0x3c, 0x74, 0x6f, 0xe8, 0xd9, 0x3c, 0x69, 0xdf, 0x2b, 0x3a,
	0xed, 0xae, 0x86, 0xc2, 0xd3, 0xd6, 0xb9, 0xd8, 0x0d, 0x9b, 0xf8, 0x1e, 0x65, 0xdb, 0x4f, 0x0a,
	0x6f, 0x98, 0x84, 0xb0, 0x1b, 0x26, 0x89, 0xd4, 0x04, 0x87, 0x8e, 0x59, 0x60, 0xb8, 0x7f, 0xa7,
	0x09, 0x02, 0x95, 0x9a, 0x20, 0x68, 0xf2, 0x23, 0x30, 0x93, 0x45, 0xfb, 0x7b, 0x5b, 0xc6, 0xd3,
	0xd6, 0xee, 0xe3, 0x9c, 0xa3, 0x67, 0xa1, 0x6c, 0xb8, 0x98, 0x51, 0xc7, 0x4c, 0x16, 0xdd, 0x2a,
	0xac, 0xbf, 0x72, 0x27, 0x73, 0x6a, 0x1f, 0xc3, 0x83, 0xbc, 0xe8, 0x45, 0xb6, 0xa0, 0x31, 0x13,
	0xe3, 0x23, 0xba, 0x60, 0x21, 0xaf, 0xe9, 0xe8, 0x53, 0x84, 0x40, 0xd9, 0x0f, 0xae, 0x43, 0x16,
	0xc7, 0xea, 0x0e, 0x1b, 0xdb, 0x7f, 0x30, 0x94, 0x38, 0x3d, 0x8c, 0x91, 0x27, 0x00, 0xf3, 0x98,
	0x46, 0x83, 0xf9, 0xd5, 0x4d, 0x2a, 0x4d, 0x9b, 0x21, 0x0f, 0xa1, 0x82, 0x54, 0x7f, 0x24, 0xc4,
	0x09, 0x8a, 0x7c, 0x0a, 0x35, 0x1c, 0xa1, 0xdd, 0x2c, 0xe0, 0xb5, 0xf2, 0x0e, 0xf6, 0x42, 0x20,
	0x9c, 0x14, 0x6b, 0xdb, 0x2a, 0x88, 0xf3, 0x70, 0x48, 0x2c, 0x28, 0x5d, 0x53, 0xca, 0x54, 0x97,
	0x1c, 0x1c, 0xda, 0x3f, 0x84, 0x7b, 0x2b, 0xb1, 0x0f, 0x0d, 0x89, 0x79, 0xa0, 0xe4, 0x48, 0x41,
	0xd9, 0xdf, 0x87, 0xcd, 0xa5, 0x68, 0x87, 0x1b, 0x70, 0x85, 0x61, 0x91, 0x03, 0xd9, 0xd8, 0x1e,
	0x82, 0xb5, 0x1c, 0x66, 0x50, 0xa4, 0x3b, 0x0d, 0xe7, 0x41, 0x22, 0x45, 0x72, 0x0a, 0x2d, 0x9a,
	0xfb, 0x72, 0xc1, 0x38, 0x44, 0xe4, 0x8c, 0xef, 0x50, 0x89, 0xed, 0x90, 0xa0, 0xec, 0x1f, 0x28,
	0xe5, 0x22, 0xe8, 0x14, 0x09, 0xb5, 0x67, 0xca, 0x00, 0x19, 0x5d, 0x0a, 0x0d, 0x78, 0x00, 0xeb,
	0xb3, 0x97, 0x61, 0x40, 0x99, 0x09, 0x25, 0x87, 0x13, 0xb8, 0xac, 0xc0, 0x9d, 0xf2, 0xed, 0xae,
	0x3b, 0x6c, 0x4c, 0x1e, 0x41, 0x2d, 0x09, 0x85, 0x69, 0x65, 0x66, 0x5a, 0x4a, 0xdb, 0xff, 0x34,
	0x94, 0x75, 0x22, 0x2e, 0x91, 0x5f, 0x41, 0x43, 0xc4, 0x25, 0x76, 0x72, 0x06, 0x3b, 0xb9, 0x0f,
	0x0a, 0xe3, 0x18, 0x3b, 0x3c, 0x9d, 0x83, 0xf4, 0x60, 0xc3, 0x0b, 0xa7, 0xd3, 0x30, 0x10, 0x08,
	0x91, 0x2d, 0x73, 0xa2, 0xf9, 0x9e, 0x0e, 0x73, 0xb2, 0x5c, 0xe4, 0x97, 0x00, 0xaf, 0xdc, 0x44,
	0xca, 0xe0, 0x19, 0x33, 0xe7, 0x72, 0xbc, 0xe8, 0x0c, 0xa5, 0x00, 0x0d, 0x6f, 0x3f, 0x57, 0x0b,
	0x13, 0x91, 0x93, 0x7c, 0x02, 0x35, 0x24, 0x8f, 0xfd, 0x18, 0x37, 0xb3, 0x94, 0x9f, 0x80, 0xf7,
	0x69, 0xe2, 0xfa, 0x13, 0x27, 0x45, 0xda, 0x1d, 0xf8, 0x4e, 0x6e, 0xf2, 0x91, 0x2e, 0x60, 0x64,
	0x5c, 0x40, 0x9c, 0x95, 0x99, 0x39, 0xd7, 0x1d, 0x75, 0xb1, 0xf4, 0xbc, 0x53, 0xe8, 0x07, 0x7d,
	0xe5, 0xdc, 0x69, 0xf0, 0xfe, 0x96, 0xd6, 0x3f, 0x83, 0xf7, 0x0a, 0x82, 0x38, 0xfa, 0x45, 0x2a,
	0xd0, 0xdc, 0x2a, 0x3d, 0xad, 0x6b, 0x6c, 0x3b, 0xca, 0x13, 0x65, 0xcc, 0xce, 0xe0, 0x4b, 0x4b,
	0xf8, 0xce, 0x12, 0x1e, 0xa3, 0xf3, 0x8f, 0x61, 0x7d, 0xe6, 0x2e, 0x86, 0x21, 0x13, 0xde, 0xd8,
	0x7d, 0x2f, 0x37, 0x85, 0x0e, 0x43, 0x87, 0xa3, 0xec, 0x7f, 0x6b, 0xe1, 0x47, 0x8f, 0xd7, 0xb8,
	0x4b, 0xcc, 0xdd, 0x46, 0x6c, 0xd9, 0x75, 0x47, 0x50, 0xe8, 0xa7, 0x09, 0x87, 0x30, 0x3f, 0x35,
	0x8b, 0xfc, 0x74, 0xa8, 0x40, 0x8e, 0xce, 0x41, 0x7e, 0x02, 0x95, 0x99, 0xef, 0xdd, 0x5c, 0xcc,
	0x8a, 0xcb, 0xb1, 0x01, 0xfb, 0xee, 0x08, 0x1c, 0xe9, 0x42, 0x13, 0x05, 0xec, 0xd3, 0x89, 0xff,
	0x8a, 0x46, 0x0b, 0x51, 0x8f, 0x3d, 0xc9, 0xd7, 0x29, 0x51, 0x4e, 0x86, 0xc7, 0xfe, 0x46, 0x8b,
	0x5c, 0x69, 0x1a, 0x79, 0x00, 0xeb, 0x57, 0xfe, 0xb8, 0x2f, 0xbd, 0x89, 0x13, 0xe4, 0x19, 0xd4,
	0xe3, 0xa9, 0x3b, 0x99, 0xb0, 0xcc, 0x54, 0xb8, 0x8b, 0xe7, 0x08, 0x71, 0x14, 0x52, 0x4f, 0x0b,
	0x7a, 0xd6, 0x41, 0x0f, 0xc2, 0x18, 0x7b, 0xb7, 0x07, 0x1d, 0xd1, 0xc5, 0x85, 0x3f, 0x72, 0x52,
	0xa4, 0x7d, 0x0d, 0x8f, 0x55, 0x56, 0x88, 0x67, 0x61, 0x10, 0xd3, 0x4c, 0xb2, 0x39, 0x00, 0x4b,
	0x0a, 0x59, 0x2a, 0xb2, 0xf3, 0x8a, 0x26, 0x81, 0x70, 0x56, 0x78, 0xec, 0xaf, 0x57, 0xf5, 0x64,
	0xb2, 0xd0, 0xe7, 0xd0, 0x1c, 0x6b, 0x39, 0x43, 0xe8, 0x78, 0x98, 0x9f, 0x51, 0x9c, 0x0c, 0xd6,
	0xfe, 0x06, 0x1e, 0x2e, 0xcb, 0x16, 0x99, 0xe5, 0x6d, 0x59, 0xef, 0xc1, 0xfb, 0x39, 0x1a, 0x44,
	0x5e, 0x7a, 0x5b, 0x4a, 0x5c, 0x75, 0x99, 0x35, 0x25, 0x2c, 0x9f, 0xbd, 0x2d, 0x15, 0x7f, 0x36,
	0xa0, 0xbd, 0xac, 0x23, 0x4d, 0x86, 0x6f, 0x49, 0xc9, 0xca, 0x51, 0x9a, 0x6f, 0x70, 0x94, 0x7f,
	0x32, 0x56, 0x37, 0x41, 0xe6, 0xd5, 0x77, 0xc1, 0xbe, 0x60, 0x75, 0xff, 0xd2, 0x5c, 0xbe, 0x0d,
	0xe5, 0xeb, 0x28, 0x9c, 0xbe, 0xc6, 0x75, 0x19, 0x86, 0x7c, 0x0c, 0x66, 0x12, 0xbe, 0x46, 0xb3,
	0x99, 0x84, 0xf6, 0x67, 0xab, 0xdb, 0x21, 0x13, 0xe8, 0x63, 0xa8, 0x8b, 0xb4, 0x9c, 0x06, 0x16,
	0x35, 0xa1, 0x67, 0x06, 0xc9, 0x28, 0x13, 0xe5, 0xa3, 0xa5, 0x54, 0xa3, 0x47, 0xfa, 0xbf, 0x1a,
	0xf0, 0x41, 0x91, 0x83, 0xf0, 0xac, 0xf6, 0x2e, 0x9c, 0xc2, 0x5f, 0x8c, 0xd5, 0x68, 0x92, 0x49,
	0xbd, 0xef, 0x82, 0x91, 0x9f, 0xad, 0xc6, 0x0c, 0x95, 0xee, 0x1f, 0x41, 0x2d, 0xa6, 0xd9, 0x33,
	0x90, 0xb4, 0xdd, 0x81, 0x0f, 0x73, 0x19, 0xb5, 0xe4, 0xfe, 0x04, 0xc0, 0x63, 0x94, 0x26, 0x40,
	0x9b, 0xb1, 0x3f, 0x59, 0x75, 0xd3, 0x34, 0xd1, 0xb7, 0xa1, 0x7a, 0x35, 0x5f, 0x68, 0x8c, 0x92,
	0xb4, 0xaf, 0x0a, 0xb8, 0x30, 0xdd, 0xbf, 0x89, 0x73, 0xdf, 0x55, 0x7a, 0xfc, 0xde, 0xc8, 0x09,
	0xa5, 0x69, 0xa2, 0xdc, 0x85, 0x6a, 0x38, 0xe1, 0x9d, 0xb2, 0x51, 0x94, 0xb4, 0x45, 0x11, 0x24,
	0x81, 0xc8, 0x13, 0xd0, 0x5b, 0x2d, 0x89, 0xde, 0xc1, 0x23, 0x80, 0xf6, 0xa7, 0xab, 0xfe, 0xf3,
	0xff, 0x14, 0x25, 0xf6, 0x41, 0x01, 0x9f, 0xcc, 0xc1, 0x04, 0xca, 0xf1, 0xdc, 0xf3, 0x04, 0x17,
	0x1b, 0xe3, 0xdc, 0x35, 0xf6, 0x22, 0x7c, 0x27, 0xd8, 0xd8, 0xfe, 0x97, 0xa9, 0xf5, 0x02, 0xd2,
	0xd9, 0x54, 0x8b, 0x61, 0xe8, 0x2d, 0x46, 0x5e, 0x37, 0x87, 0x97, 0xff, 0x9a, 0xd2, 0x0e, 0x2f,
	0x2f, 0x4b, 0xac, 0xbc, 0x54, 0x13, 0xb2, 0xa1, 0x2a, 0xa7, 0x0d, 0x15, 0xb1, 0xa1, 0xc9, 0xbb,
	0x25, 0xc1, 0xb2, 0xce, 0x3e, 0x65, 0xe6, 0xb4, 0xfe, 0xaa, 0xa2, 0xf7, 0x57, 0xe8, 0x6c, 0xd8,
	0x40, 0x09, 0xce, 0x2a, 0xfb, 0xa6, 0xcd, 0xa4, 0xcd, 0x56, 0x4d, 0x35, 0x5b, 0x19, 0xff, 0xae,
	0x67, 0xfd, 0x1b, 0x6d, 0x99, 0x4d, 0xe8, 0x68, 0x2c, 0xcd, 0x07, 0x6e, 0x8b, 0x3e, 0x87, 0x2b,
	0x88, 0xa6, 0x57, 0xec, 0x95, 0xa5, 0xe4, 0xe0, 0x10, 0x6b, 0xa8, 0x1b, 0xf6, 0xe8, 0xd3, 0xe4,
	0x1d, 0x11, 0x23, 0x50, 0x77, 0xe4, 0x26, 0x94, 0x3d, 0x8f, 0x94, 0x1c, 0x36, 0xb6, 0xff, 0x6b,
	0x40, 0x53, 0xf7, 0xca, 0x9c, 0x52, 0x5e, 0x88, 0x37, 0x95, 0xf8, 0x87, 0x50, 0xb9, 0x8e, 0xc2,
	0xdf, 0xd1, 0x40, 0xec, 0xa6, 0xa0, 0x94, 0xda, 0xf2, 0x92, 0x5a, 0xd6, 0x88, 0xad, 0x6b, 0x8d,
	0x58, 0xda, 0xb2, 0x55, 0x96, 0x5a, 0xb6, 0x29, 0x6e, 0x4e, 0x95, 0x23, 0x71, 0x8c, 0xba, 0x6e,
	0x79, 0x9d, 0x56, 0xe3, 0xde, 0xc5, 0x29, 0xcd, 0x01, 0xea, 0x19, 0x07, 0xd8, 0x81, 0x72, 0x82,
	0x35, 0x30, 0xbc, 0xb6, 0xcb, 0x66, 0x38, 0xfb, 0xe7, 0xb0, 0xa1, 0x9a, 0xa3, 0x69, 0x51, 0x2f,
	0x23, 0x54, 0x99, 0x99, 0x76, 0xf6, 0x73, 0xd5, 0x9c, 0xf3, 0x52, 0xf1, 0x0d, 0x78, 0x3f, 0x56,
	0xbc, 0xbc, 0xb0, 0x56, 0x5b, 0x62, 0x68, 0x5b, 0x62, 0xff, 0x43, 0x6b, 0x05, 0xf4, 0x4a, 0x1a,
	0x9d, 0x26, 0xa2, 0x1e, 0x45, 0x42, 0xe8, 0x4b, 0x69, 0xb2, 0x05, 0x0d, 0x31, 0xee, 0x8c, 0x46,
	0x91, 0xb8, 0x0b, 0xfa, 0x14, 0x72, 0x7b, 0x61, 0x90, 0x44, 0xae, 0x97, 0x88, 0x06, 0x39, 0xa5,
	0xc9, 0x11, 0x6c, 0x8e, 0x84, 0x96, 0x03, 0xca, 0x1b, 0xdf, 0x32, 0xdb, 0xcc, 0x8f, 0xf2, 0x62,
	0x45, 0x06, 0xe8, 0x2c, 0x73, 0xda, 0x7f, 0x2f, 0xab, 0x85, 0xf2, 0xc0, 0x92, 0x89, 0x17, 0x86,
	0xd6, 0xc4, 0x88, 0x48, 0x98, 0x76, 0x30, 0x22, 0x12, 0xb2, 0xfe, 0x44, 0x7c, 0x3b, 0x55, 0x0d,
	0x7d, 0x4a, 0xcb, 0x6f, 0x5d, 0x37, 0x18, 0x31, 0x43, 0xc5, 0x37, 0xa4, 0xf1, 0xea, 0xb3, 0xbe,
	0x20, 0xc1, 0x8f, 0xdc, 0x01, 0xd5, 0x84, 0xe4, 0x1c, 0xb8, 0xde, 0x0d, 0x73, 0x44, 0xc1, 0x89,
	0x34, 0x8b, 0xfc, 0xa8, 0x61, 0x3e, 0x15, 0xb7, 0x58, 0x92, 0x52, 0xe6, 0x20, 0xc2, 0x5e, 0x9c,
	0xdf, 0x63, 0x35, 0x81, 0x8d, 0x8a, 0x50, 0x90, 0x50, 0xe6, 0x9a, 0xad, 0xdc, 0x46, 0x05, 0x3f,
	0x3b, 0x0a, 0xa9, 0xf5, 0xbf, 0x90, 0x79, 0xdb, 0x58, 0xbe, 0xff, 0x8d, 0xfc, 0xfb, 0x1f, 0xfa,
	0x23, 0x76, 0xd7, 0xeb, 0x0e, 0x0e, 0x35, 0xaf, 0xdb, 0xc8, 0x5c, 0x8e, 0x47, 0x50, 0xf3, 0xe3,
	0x01, 0xe3, 0x65, 0x2f, 0x9c, 0x35, 0x27, 0xa5, 0x71, 0xc1, 0xb7, 0x6e, 0xc4, 0x76, 0x78, 0x93,
	0x49, 0x92, 0x24, 0x2e, 0xd8, 0x8b, 0xa8, 0x9b, 0xd0, 0x13, 0x37, 0x60, 0xcf, 0x92, 0x75, 0x47,
	0x4d, 0x20, 0x1f, 0x1d, 0xf9, 0x09, 0x7e, 0xbb, 0xc7, 0xf9, 0x04, 0x89, 0xda, 0xdc, 0xb9, 0xf8,
	0x44, 0xf8, 0xf6, 0x4a, 0x1a, 0xbf, 0xdd, 0x46, 0x3e, 0x17, 0x79, 0x9f, 0x7f, 0x93, 0xb4, 0xfd,
	0x5c, 0x3d, 0x33, 0x64, 0x5e, 0x45, 0x50, 0x95, 0x17, 0x4e, 0x67, 0x6e, 0xb0, 0x10, 0xae, 0x23,
	0x49, 0xbc, 0x3c, 0x89, 0xfb, 0xdb, 0x53, 0x19, 0xf7, 0x39, 0x61, 0xff, 0xcd, 0x00, 0xb2, 0xfa,
	0x36, 0xf2, 0xa6, 0x62, 0x78, 0xcc, 0x0e, 0x6e, 0xe4, 0x4b, 0x12, 0x8e, 0xf1, 0x8a, 0xe1, 0x6f,
	0xc7, 0xf3, 0xd8, 0xb1, 0x70, 0xbf, 0xd3, 0xa7, 0x50, 0x8b, 0x3b, 0x1a, 0x45, 0x34, 0x8e, 0x85,
	0xe3, 0x49, 0x32, 0x73, 0xf9, 0x2a, 0xd9, 0xcb, 0xa7, 0x3f, 0xb1, 0xa4, 0x05, 0x10, 0x8b, 0x77,
	0xb9, 0xa1, 0x45, 0xdc, 0x23, 0x53, 0xbf, 0x47, 0xf6, 0xb9, 0x8a, 0x68, 0xec, 0x55, 0xa1, 0xf0,
	0xc2, 0x11, 0x28, 0x27, 0x61, 0xfa, 0x72, 0xc7, 0xc6, 0x88, 0x4d, 0x42, 0x34, 0x54, 0x3e, 0xdd,
	0x71, 0xca, 0xee, 0x28, 0xa1, 0xac, 0xc9, 0x2e, 0x14, 0xaa, 0xdd, 0x1b, 0x33, 0x73, 0x6f, 0xf4,
	0xa7, 0x1c, 0x8c, 0xc1, 0xdc, 0xef, 0xdb, 0x50, 0xc5, 0xf6, 0x3a, 0x98, 0x4f, 0x45, 0xdc, 0x93,
	0x24, 0xf3, 0x1e, 0x0c, 0xc8, 0x41, 0x2a, 0x29, 0xa5, 0xb7, 0xff, 0x58, 0x52, 0x07, 0xab, 0x5e,
	0x84, 0x49, 0x13, 0x6a, 0x27, 0xf1, 0xb8, 0x17, 0x45, 0x61, 0x64, 0xad, 0x91, 0xfb, 0xb0, 0x79,
	0x12, 0x8f, 0xf5, 0x06, 0xdd, 0x32, 0xc4, 0xa4, 0xde, 0x4d, 0x5b, 0x26, 0xd9, 0x80, 0xfa, 0x49,
	0x3c, 0xe6, 0x6d, 0xb0, 0x55, 0x22, 0x16, 0x34, 0x39, 0xc9, 0x7b, 0x56, 0xab, 0x4c, 0x5a, 0x00,
	0x7c, 0x06, 0x1b, 0x4c, 0x6b, 0x9d, 0x6c, 0x42, 0xe3, 0x24, 0x1e, 0xcb, 0x5a, 0xdf, 0xaa, 0x08,
	0x80, 0x28, 0xab, 0xad, 0xaa, 0x50, 0xa3, 0x97, 0xd9, 0x56, 0x8d, 0x3c, 0x00, 0x4b, 0xe3, 0xe2,
	0xb3, 0x75, 0x21, 0x4b, 0x36, 0x46, 0x16, 0x08, 0x59, 0xc2, 0x59, 0xad, 0x86, 0xa0, 0x45, 0x43,
	0x62, 0x35, 0x85, 0x79, 0xa9, 0x77, 0x58, 0x1b, 0xe4, 0x21, 0x10, 0x39, 0xa3, 0xea, 0x5e, 0xab,
	0x25, 0x44, 0xcb, 0x62, 0xd6, 0xda, 0xd4, 0x27, 0x06, 0xee, 0xc2, 0xb2, 0x84, 0x9d, 0x7a, 0x39,
	0x67, 0xdd, 0x93, 0xeb, 0x97, 0x85, 0xa6, 0x45, 0x74, 0x98, 0xa8, 0xde, 0xac, 0xfb, 0x62, 0xb7,
	0xf7, 0xd0, 0xd9, 0x2d, 0x6f, 0xfb, 0x0b, 0x55, 0xa4, 0xc9, 0x0c, 0x8b, 0x96, 0x5f, 0x0c, 0x2f,
	0x2f, 0x4e, 0x8f, 0x4e, 0xcf, 0xbe, 0x3c, 0xb5, 0xd6, 0x48, 0x03, 0xaa, 0x48, 0x9f, 0xf7, 0x1c,
	0xcb, 0x40, 0xf6, 0x8b, 0xe1, 0x65, 0x67, 0xff, 0xa4, 0x7f, 0x6a, 0x99, 0xdb, 0xc7, 0x70, 0x3f,
	0xe7, 0x91, 0x0a, 0x0d, 0x1e, 0x9e, 0xe9, 0x22, 0x5a, 0x00, 0x38, 0x31, 0xe8, 0xef, 0x1d, 0x5d,
	0x0c, 0x2c, 0x03, 0xf7, 0x14, 0xe9, 0x61, 0xe7, 0xa8, 0xb7, 0xdf, 0x3b, 0xee, 0xbf, 0xe8, 0x39,
	0x5f, 0x59, 0xe6, 0x76, 0x57, 0x35, 0x74, 0x4b, 0x19, 0x0a, 0x25, 0xee, 0x1f, 0xe8, 0x12, 0x01,
	0x2a, 0x38, 0xb1, 0x7f, 0x60, 0x19, 0x72, 0xfc, 0xd5, 0xaf, 0x2d, 0x73, 0xfb, 0x37, 0x9a, 0xc7,
	0x33, 0x57, 0x6d, 0x01, 0x74, 0xcf, 0xb3, 0xab, 0xe9, 0x9e, 0x5f, 0x1e, 0x38, 0xbd, 0x9e, 0x65,
	0xa0, 0x0b, 0x31, 0xe2, 0xec, 0xeb, 0xde, 0xa9, 0x65, 0x8a, 0x6f, 0xe7, 0xbd, 0xe3, 0x63, 0xab,
	0x24, 0x18, 0xd1, 0xc4, 0xb3, 0x8b, 0xa1, 0x55, 0xde, 0xfe, 0x42, 0xad, 0x55, 0x7b, 0x38, 0x46,
	0x58, 0x7f, 0xc9, 0xb0, 0xfe, 0xf0, 0x72, 0xef, 0xec, 0x84, 0x1b, 0xd6, 0x1f, 0x5e, 0xbe, 0xe8,
	0x0c, 0x2d, 0xf3, 0xaa, 0xc2, 0xfe, 0xea, 0xfd, 0xe9, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xf3,
	0x74, 0x0b, 0x41, 0xfc, 0x1d, 0x00, 0x00,
}
